from ..grpc_session_options import GrpcSessionOptions
from ..constants import (
    Coupling,
    FilterType,
    UsageTypeAI,
    TriggerUsage,
    AcquisitionType,
    UsageTypeAO,
    BusType,
    UsageTypeCI,
    UsageTypeCO,
    IDPinStatus,
)
from ..system._collections.physical_channel_collection import (
    AIPhysicalChannelCollection,
    AOPhysicalChannelCollection,
    CIPhysicalChannelCollection,
    COPhysicalChannelCollection,
    DILinesCollection,
    DIPortsCollection,
    DOLinesCollection,
    DOPortsCollection,
)

class Device:
    def __init__(
        self, name: str, *, grpc_options: GrpcSessionOptions | None = ...
    ) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def ai_physical_chans(self) -> AIPhysicalChannelCollection: ...
    @property
    def ao_physical_chans(self) -> AOPhysicalChannelCollection: ...
    @property
    def ci_physical_chans(self) -> CIPhysicalChannelCollection: ...
    @property
    def co_physical_chans(self) -> COPhysicalChannelCollection: ...
    @property
    def di_lines(self) -> DILinesCollection: ...
    @property
    def di_ports(self) -> DIPortsCollection: ...
    @property
    def do_lines(self) -> DOLinesCollection: ...
    @property
    def do_ports(self) -> DOPortsCollection: ...
    @property
    def accessory_product_nums(self) -> list[int]: ...
    @property
    def accessory_product_types(self) -> list[str]: ...
    @property
    def accessory_serial_nums(self) -> list[int]: ...
    @property
    def ai_bridge_rngs(self) -> list[float]: ...
    @property
    def ai_charge_rngs(self) -> list[float]: ...
    @property
    def ai_couplings(self) -> list[Coupling]: ...
    @property
    def ai_current_int_excit_discrete_vals(self) -> list[float]: ...
    @property
    def ai_current_rngs(self) -> list[float]: ...
    @property
    def ai_dig_fltr_lowpass_cutoff_freq_discrete_vals(self) -> list[float]: ...
    @property
    def ai_dig_fltr_lowpass_cutoff_freq_range_vals(self) -> list[float]: ...
    @property
    def ai_dig_fltr_types(self) -> list[FilterType]: ...
    @property
    def ai_freq_rngs(self) -> list[float]: ...
    @property
    def ai_gains(self) -> list[float]: ...
    @property
    def ai_lowpass_cutoff_freq_discrete_vals(self) -> list[float]: ...
    @property
    def ai_lowpass_cutoff_freq_range_vals(self) -> list[float]: ...
    @property
    def ai_max_multi_chan_rate(self) -> float: ...
    @property
    def ai_max_single_chan_rate(self) -> float: ...
    @property
    def ai_meas_types(self) -> list[UsageTypeAI]: ...
    @property
    def ai_min_rate(self) -> float: ...
    @property
    def ai_num_samp_timing_engines(self) -> int: ...
    @property
    def ai_num_sync_pulse_srcs(self) -> int: ...
    @property
    def ai_resistance_rngs(self) -> list[float]: ...
    @property
    def ai_samp_modes(self) -> list[AcquisitionType]: ...
    @property
    def ai_simultaneous_sampling_supported(self) -> bool: ...
    @property
    def ai_trig_usage(self) -> list[TriggerUsage]: ...
    @property
    def ai_voltage_int_excit_discrete_vals(self) -> list[float]: ...
    @property
    def ai_voltage_int_excit_range_vals(self) -> list[float]: ...
    @property
    def ai_voltage_rngs(self) -> list[float]: ...
    @property
    def anlg_trig_supported(self) -> bool: ...
    @property
    def ao_current_rngs(self) -> list[float]: ...
    @property
    def ao_gains(self) -> list[float]: ...
    @property
    def ao_max_rate(self) -> float: ...
    @property
    def ao_min_rate(self) -> float: ...
    @property
    def ao_num_samp_timing_engines(self) -> int: ...
    @property
    def ao_num_sync_pulse_srcs(self) -> int: ...
    @property
    def ao_output_types(self) -> list[UsageTypeAO]: ...
    @property
    def ao_samp_clk_supported(self) -> bool: ...
    @property
    def ao_samp_modes(self) -> list[AcquisitionType]: ...
    @property
    def ao_trig_usage(self) -> list[TriggerUsage]: ...
    @property
    def ao_voltage_rngs(self) -> list[float]: ...
    @property
    def bus_type(self) -> BusType: ...
    @property
    def cal_acc_connection_count(self) -> int: ...
    @cal_acc_connection_count.setter
    def cal_acc_connection_count(self, val: int) -> None: ...
    @property
    def cal_dev_temp(self) -> float: ...
    @property
    def cal_recommended_acc_connection_count_limit(self) -> int: ...
    @property
    def cal_user_defined_info(self) -> str: ...
    @cal_user_defined_info.setter
    def cal_user_defined_info(self, val: str) -> None: ...
    @property
    def cal_user_defined_info_max_size(self) -> int: ...
    @property
    def carrier_serial_num(self) -> int: ...
    @property
    def chassis_module_devices(self) -> list[Device]: ...
    @property
    def ci_max_size(self) -> int: ...
    @property
    def ci_max_timebase(self) -> float: ...
    @property
    def ci_meas_types(self) -> list[UsageTypeCI]: ...
    @property
    def ci_samp_clk_supported(self) -> bool: ...
    @property
    def ci_samp_modes(self) -> list[AcquisitionType]: ...
    @property
    def ci_trig_usage(self) -> list[TriggerUsage]: ...
    @property
    def co_max_size(self) -> int: ...
    @property
    def co_max_timebase(self) -> float: ...
    @property
    def co_output_types(self) -> list[UsageTypeCO]: ...
    @property
    def co_samp_clk_supported(self) -> bool: ...
    @property
    def co_samp_modes(self) -> list[AcquisitionType]: ...
    @property
    def co_trig_usage(self) -> list[TriggerUsage]: ...
    @property
    def compact_daq_chassis_device(self) -> Device: ...
    @property
    def compact_daq_slot_num(self) -> int: ...
    @property
    def compact_rio_chassis_device(self) -> Device: ...
    @property
    def compact_rio_slot_num(self) -> int: ...
    @property
    def di_max_rate(self) -> float: ...
    @property
    def di_num_samp_timing_engines(self) -> int: ...
    @property
    def di_trig_usage(self) -> list[TriggerUsage]: ...
    @property
    def dig_trig_supported(self) -> bool: ...
    @property
    def do_max_rate(self) -> float: ...
    @property
    def do_num_samp_timing_engines(self) -> int: ...
    @property
    def do_trig_usage(self) -> list[TriggerUsage]: ...
    @property
    def ext_cal_last_temp(self) -> float: ...
    @property
    def ext_cal_recommended_interval(self) -> int: ...
    @property
    def field_daq_bank_devices(self) -> list[Device]: ...
    @property
    def field_daq_device(self) -> Device: ...
    @property
    def hwteds_supported(self) -> bool: ...
    @property
    def id_pin_mem_family_codes(self) -> list[int]: ...
    @property
    def id_pin_mem_sizes(self) -> list[int]: ...
    @property
    def id_pin_pin_names(self) -> list[str]: ...
    @property
    def id_pin_pin_statuses(self) -> list[IDPinStatus]: ...
    @property
    def is_simulated(self) -> bool: ...
    @property
    def num_dma_chans(self) -> int: ...
    @property
    def num_time_trigs(self) -> int: ...
    @property
    def num_timestamp_engines(self) -> int: ...
    @property
    def pci_bus_num(self) -> int: ...
    @property
    def pci_dev_num(self) -> int: ...
    @property
    def product_num(self) -> int: ...
    @property
    def product_type(self) -> str: ...
    @property
    def pxi_chassis_num(self) -> int: ...
    @property
    def pxi_slot_num(self) -> int: ...
    @property
    def self_cal_last_temp(self) -> float: ...
    @property
    def self_cal_supported(self) -> bool: ...
    @property
    def serial_num(self) -> int: ...
    @property
    def tcpip_ethernet_ip(self) -> str: ...
    @property
    def tcpip_hostname(self) -> str: ...
    @property
    def tcpip_wireless_ip(self) -> str: ...
    @property
    def terminals(self) -> list[str]: ...
    @property
    def time_trig_supported(self) -> bool: ...
    @property
    def dev_is_simulated(self) -> bool: ...
    @property
    def dev_serial_num(self) -> int: ...
    @property
    def tedshwteds_supported(self) -> bool: ...
    def reset_device(self) -> None: ...

    # region ID Pin Hand-written Functions

    def read_id_pin_memory(self, id_pin_name: str) -> None: ...

    # endregion

    # region Network Device Functions

    @staticmethod
    def add_network_device(
        ip_address_str: str,
        device_name: str = "",
        attempt_reservation: bool = False,
        timeout: float = 10.0,
        *,
        grpc_options: GrpcSessionOptions | None = None,
    ) -> Device: ...
    def delete_network_device(self) -> None: ...
    def reserve_network_device(
        self, override_reservation: bool | None = None
    ) -> None: ...
    def unreserve_network_device(self) -> None: ...

    # endregion

class _DeviceAlternateConstructor(Device):
    def __init__(
        self, name: str, *, grpc_options: GrpcSessionOptions | None = ...
    ) -> None: ...
