from ..system._watchdog_modules.expiration_state import ExpirationState

from ..system._watchdog_modules.expiration_states_collection import (
    ExpirationStatesCollection,
)

from ..types import AOExpirationState, COExpirationState, DOExpirationState
from ..grpc_session_options import GrpcSessionOptions

from ..constants import (
    Edge,
    TaskMode,
    TriggerType,
    WDTTaskAction,
)

class WatchdogTask:
    def __init__(
        self,
        device_name: str,
        task_name: str,
        timeout: float,
        grpc_options: GrpcSessionOptions,
    ) -> None: ...
    @property
    def expiration_states(self) -> ExpirationStatesCollection: ...
    @property
    def expir_trig_dig_edge_edge(self) -> Edge: ...
    @expir_trig_dig_edge_edge.setter
    def expir_trig_dig_edge_edge(self, val: Edge) -> None: ...
    @expir_trig_dig_edge_edge.deleter
    def expir_trig_dig_edge_edge(self) -> None: ...
    @property
    def expir_trig_dig_edge_src(self) -> str: ...
    @expir_trig_dig_edge_src.setter
    def expir_trig_dig_edge_src(self, val: str) -> None: ...
    @expir_trig_dig_edge_src.deleter
    def expir_trig_dig_edge_src(self) -> None: ...
    @property
    def expir_trig_trig_on_network_conn_loss(self) -> bool: ...
    @expir_trig_trig_on_network_conn_loss.setter
    def expir_trig_trig_on_network_conn_loss(self, val: bool) -> None: ...
    @expir_trig_trig_on_network_conn_loss.deleter
    def expir_trig_trig_on_network_conn_loss(self) -> None: ...
    @property
    def expir_trig_trig_type(self) -> TriggerType: ...
    @expir_trig_trig_type.setter
    def expir_trig_trig_type(self, val: TriggerType) -> None: ...
    @expir_trig_trig_type.deleter
    def expir_trig_trig_type(self) -> None: ...
    @property
    def expired(self) -> bool: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, val: float) -> None: ...
    @timeout.deleter
    def timeout(self) -> None: ...
    @property
    def name(self) -> str: ...
    def _control_watchdog_task(self, action: WDTTaskAction) -> None: ...
    def cfg_watchdog_ao_expir_states(
        self, expiration_states: list[AOExpirationState]
    ) -> list[ExpirationState]: ...
    def cfg_watchdog_co_expir_states(
        self, expiration_states: list[COExpirationState]
    ) -> list[ExpirationState]: ...
    def cfg_watchdog_do_expir_states(
        self, expiration_states: list[DOExpirationState]
    ) -> list[ExpirationState]: ...
    def clear_expiration(self) -> None: ...
    def close(self) -> None: ...
    def control(self, action: TaskMode) -> None: ...
    def reset_timer(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
