from ._channel import Channel

from ...scale import Scale
from ...constants import (
    ACExcitWireMode,
    ADCTimingMode,
    AccelChargeSensitivityUnits,
    AccelSensitivityUnits,
    AccelUnits,
    AngleUnits,
    AutoZeroType,
    BridgeConfiguration,
    BridgeElectricalUnits,
    BridgePhysicalUnits,
    BridgeShuntCalSource,
    BridgeUnits,
    CJCSource,
    ChargeUnits,
    Coupling,
    CurrentShuntResistorLocation,
    CurrentUnits,
    DataJustification,
    DataTransferActiveTransferMode,
    DigitalWidthUnits,
    EddyCurrentProxProbeSensitivityUnits,
    ExcitationDCorAC,
    ExcitationIdleOutputBehavior,
    ExcitationSource,
    ExcitationVoltageOrCurrent,
    FilterResponse,
    FilterType,
    ForceIEPESensorSensitivityUnits,
    ForceUnits,
    FrequencyUnits,
    Impedance1,
    InputDataTransferCondition,
    LVDTSensitivityUnits,
    LengthUnits,
    PowerIdleOutputBehavior,
    PowerOutputState,
    PressureUnits,
    RTDType,
    RVDTSensitivityUnits,
    RawDataCompressionType,
    ResistanceConfiguration,
    ResistanceUnits,
    ResolutionType,
    ScaleType,
    Sense,
    SensorPowerCfg,
    SensorPowerType,
    ShuntCalSelect,
    SoundPressureUnits,
    SourceSelection,
    StrainGageBridgeType,
    StrainGageRosetteMeasurementType,
    StrainGageRosetteType,
    StrainUnits,
    TemperatureUnits,
    TerminalConfiguration,
    ThermocoupleType,
    TorqueUnits,
    UsageTypeAI,
    VelocityIEPESensorSensitivityUnits,
    VelocityUnits,
    VoltageUnits,
)

class AIChannel(Channel):
    @property
    def ai_ac_excit_freq(self) -> float: ...
    @ai_ac_excit_freq.setter
    def ai_ac_excit_freq(self, val: float) -> None: ...
    @ai_ac_excit_freq.deleter
    def ai_ac_excit_freq(self) -> None: ...
    @property
    def ai_ac_excit_sync_enable(self) -> bool: ...
    @ai_ac_excit_sync_enable.setter
    def ai_ac_excit_sync_enable(self, val: bool) -> None: ...
    @ai_ac_excit_sync_enable.deleter
    def ai_ac_excit_sync_enable(self) -> None: ...
    @property
    def ai_ac_excit_wire_mode(self) -> ACExcitWireMode: ...
    @ai_ac_excit_wire_mode.setter
    def ai_ac_excit_wire_mode(self, val: ACExcitWireMode) -> None: ...
    @ai_ac_excit_wire_mode.deleter
    def ai_ac_excit_wire_mode(self) -> None: ...
    @property
    def ai_accel_4_wire_dc_voltage_sensitivity(self) -> float: ...
    @ai_accel_4_wire_dc_voltage_sensitivity.setter
    def ai_accel_4_wire_dc_voltage_sensitivity(self, val: float) -> None: ...
    @ai_accel_4_wire_dc_voltage_sensitivity.deleter
    def ai_accel_4_wire_dc_voltage_sensitivity(self) -> None: ...
    @property
    def ai_accel_4_wire_dc_voltage_sensitivity_units(self) -> AccelSensitivityUnits: ...
    @ai_accel_4_wire_dc_voltage_sensitivity_units.setter
    def ai_accel_4_wire_dc_voltage_sensitivity_units(
        self, val: AccelSensitivityUnits
    ) -> None: ...
    @ai_accel_4_wire_dc_voltage_sensitivity_units.deleter
    def ai_accel_4_wire_dc_voltage_sensitivity_units(self) -> None: ...
    @property
    def ai_accel_charge_sensitivity(self) -> float: ...
    @ai_accel_charge_sensitivity.setter
    def ai_accel_charge_sensitivity(self, val: float) -> None: ...
    @ai_accel_charge_sensitivity.deleter
    def ai_accel_charge_sensitivity(self) -> None: ...
    @property
    def ai_accel_charge_sensitivity_units(self) -> AccelChargeSensitivityUnits: ...
    @ai_accel_charge_sensitivity_units.setter
    def ai_accel_charge_sensitivity_units(
        self, val: AccelChargeSensitivityUnits
    ) -> None: ...
    @ai_accel_charge_sensitivity_units.deleter
    def ai_accel_charge_sensitivity_units(self) -> None: ...
    @property
    def ai_accel_db_ref(self) -> float: ...
    @ai_accel_db_ref.setter
    def ai_accel_db_ref(self, val: float) -> None: ...
    @ai_accel_db_ref.deleter
    def ai_accel_db_ref(self) -> None: ...
    @property
    def ai_accel_sensitivity(self) -> float: ...
    @ai_accel_sensitivity.setter
    def ai_accel_sensitivity(self, val: float) -> None: ...
    @ai_accel_sensitivity.deleter
    def ai_accel_sensitivity(self) -> None: ...
    @property
    def ai_accel_sensitivity_units(self) -> AccelChargeSensitivityUnits: ...
    @ai_accel_sensitivity_units.setter
    def ai_accel_sensitivity_units(self, val: AccelChargeSensitivityUnits) -> None: ...
    @ai_accel_sensitivity_units.deleter
    def ai_accel_sensitivity_units(self) -> None: ...
    @property
    def ai_accel_units(self) -> AccelUnits: ...
    @ai_accel_units.setter
    def ai_accel_units(self, val: AccelUnits) -> None: ...
    @ai_accel_units.deleter
    def ai_accel_units(self) -> None: ...
    @property
    def ai_adc_custom_timing_mode(self) -> int: ...
    @ai_adc_custom_timing_mode.setter
    def ai_adc_custom_timing_mode(self, val: int) -> None: ...
    @ai_adc_custom_timing_mode.deleter
    def ai_adc_custom_timing_mode(self) -> None: ...
    @property
    def ai_adc_timing_mode(self) -> ADCTimingMode: ...
    @ai_adc_timing_mode.setter
    def ai_adc_timing_mode(self, val: ADCTimingMode) -> None: ...
    @ai_adc_timing_mode.deleter
    def ai_adc_timing_mode(self) -> None: ...
    @property
    def ai_atten(self) -> float: ...
    @ai_atten.setter
    def ai_atten(self, val: float) -> None: ...
    @ai_atten.deleter
    def ai_atten(self) -> None: ...
    @property
    def ai_auto_zero_mode(self) -> AutoZeroType: ...
    @ai_auto_zero_mode.setter
    def ai_auto_zero_mode(self, val: AutoZeroType) -> None: ...
    @ai_auto_zero_mode.deleter
    def ai_auto_zero_mode(self) -> None: ...
    @property
    def ai_averaging_win_size(self) -> int: ...
    @ai_averaging_win_size.setter
    def ai_averaging_win_size(self, val: int) -> None: ...
    @ai_averaging_win_size.deleter
    def ai_averaging_win_size(self) -> None: ...
    @property
    def ai_bridge_balance_coarse_pot(self) -> int: ...
    @ai_bridge_balance_coarse_pot.setter
    def ai_bridge_balance_coarse_pot(self, val: int) -> None: ...
    @ai_bridge_balance_coarse_pot.deleter
    def ai_bridge_balance_coarse_pot(self) -> None: ...
    @property
    def ai_bridge_balance_fine_pot(self) -> int: ...
    @ai_bridge_balance_fine_pot.setter
    def ai_bridge_balance_fine_pot(self, val: int) -> None: ...
    @ai_bridge_balance_fine_pot.deleter
    def ai_bridge_balance_fine_pot(self) -> None: ...
    @property
    def ai_bridge_cfg(self) -> BridgeConfiguration: ...
    @ai_bridge_cfg.setter
    def ai_bridge_cfg(self, val: BridgeConfiguration) -> None: ...
    @ai_bridge_cfg.deleter
    def ai_bridge_cfg(self) -> None: ...
    @property
    def ai_bridge_electrical_units(self) -> BridgeElectricalUnits: ...
    @ai_bridge_electrical_units.setter
    def ai_bridge_electrical_units(self, val: BridgeElectricalUnits) -> None: ...
    @ai_bridge_electrical_units.deleter
    def ai_bridge_electrical_units(self) -> None: ...
    @property
    def ai_bridge_initial_ratio(self) -> float: ...
    @ai_bridge_initial_ratio.setter
    def ai_bridge_initial_ratio(self, val: float) -> None: ...
    @ai_bridge_initial_ratio.deleter
    def ai_bridge_initial_ratio(self) -> None: ...
    @property
    def ai_bridge_initial_voltage(self) -> float: ...
    @ai_bridge_initial_voltage.setter
    def ai_bridge_initial_voltage(self, val: float) -> None: ...
    @ai_bridge_initial_voltage.deleter
    def ai_bridge_initial_voltage(self) -> None: ...
    @property
    def ai_bridge_nom_resistance(self) -> float: ...
    @ai_bridge_nom_resistance.setter
    def ai_bridge_nom_resistance(self, val: float) -> None: ...
    @ai_bridge_nom_resistance.deleter
    def ai_bridge_nom_resistance(self) -> None: ...
    @property
    def ai_bridge_physical_units(self) -> BridgePhysicalUnits: ...
    @ai_bridge_physical_units.setter
    def ai_bridge_physical_units(self, val: BridgePhysicalUnits) -> None: ...
    @ai_bridge_physical_units.deleter
    def ai_bridge_physical_units(self) -> None: ...
    @property
    def ai_bridge_poly_forward_coeff(self) -> list[float]: ...
    @ai_bridge_poly_forward_coeff.setter
    def ai_bridge_poly_forward_coeff(self, val: list[float]) -> None: ...
    @ai_bridge_poly_forward_coeff.deleter
    def ai_bridge_poly_forward_coeff(self) -> None: ...
    @property
    def ai_bridge_poly_reverse_coeff(self) -> list[float]: ...
    @ai_bridge_poly_reverse_coeff.setter
    def ai_bridge_poly_reverse_coeff(self, val: list[float]) -> None: ...
    @ai_bridge_poly_reverse_coeff.deleter
    def ai_bridge_poly_reverse_coeff(self) -> None: ...
    @property
    def ai_bridge_scale_type(self) -> ScaleType: ...
    @ai_bridge_scale_type.setter
    def ai_bridge_scale_type(self, val: ScaleType) -> None: ...
    @ai_bridge_scale_type.deleter
    def ai_bridge_scale_type(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_enable(self) -> bool: ...
    @ai_bridge_shunt_cal_enable.setter
    def ai_bridge_shunt_cal_enable(self, val: bool) -> None: ...
    @ai_bridge_shunt_cal_enable.deleter
    def ai_bridge_shunt_cal_enable(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_gain_adjust(self) -> float: ...
    @ai_bridge_shunt_cal_gain_adjust.setter
    def ai_bridge_shunt_cal_gain_adjust(self, val: float) -> None: ...
    @ai_bridge_shunt_cal_gain_adjust.deleter
    def ai_bridge_shunt_cal_gain_adjust(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_select(self) -> ShuntCalSelect: ...
    @ai_bridge_shunt_cal_select.setter
    def ai_bridge_shunt_cal_select(self, val: ShuntCalSelect) -> None: ...
    @ai_bridge_shunt_cal_select.deleter
    def ai_bridge_shunt_cal_select(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_shunt_cal_a_actual_resistance(self) -> float: ...
    @ai_bridge_shunt_cal_shunt_cal_a_actual_resistance.setter
    def ai_bridge_shunt_cal_shunt_cal_a_actual_resistance(self, val: float) -> None: ...
    @ai_bridge_shunt_cal_shunt_cal_a_actual_resistance.deleter
    def ai_bridge_shunt_cal_shunt_cal_a_actual_resistance(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_shunt_cal_a_resistance(self) -> float: ...
    @ai_bridge_shunt_cal_shunt_cal_a_resistance.setter
    def ai_bridge_shunt_cal_shunt_cal_a_resistance(self, val: float) -> None: ...
    @ai_bridge_shunt_cal_shunt_cal_a_resistance.deleter
    def ai_bridge_shunt_cal_shunt_cal_a_resistance(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_shunt_cal_a_src(self) -> BridgeShuntCalSource: ...
    @ai_bridge_shunt_cal_shunt_cal_a_src.setter
    def ai_bridge_shunt_cal_shunt_cal_a_src(
        self, val: BridgeShuntCalSource
    ) -> None: ...
    @ai_bridge_shunt_cal_shunt_cal_a_src.deleter
    def ai_bridge_shunt_cal_shunt_cal_a_src(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_shunt_cal_b_actual_resistance(self) -> float: ...
    @ai_bridge_shunt_cal_shunt_cal_b_actual_resistance.setter
    def ai_bridge_shunt_cal_shunt_cal_b_actual_resistance(self, val: float) -> None: ...
    @ai_bridge_shunt_cal_shunt_cal_b_actual_resistance.deleter
    def ai_bridge_shunt_cal_shunt_cal_b_actual_resistance(self) -> None: ...
    @property
    def ai_bridge_shunt_cal_shunt_cal_b_resistance(self) -> float: ...
    @ai_bridge_shunt_cal_shunt_cal_b_resistance.setter
    def ai_bridge_shunt_cal_shunt_cal_b_resistance(self, val: float) -> None: ...
    @ai_bridge_shunt_cal_shunt_cal_b_resistance.deleter
    def ai_bridge_shunt_cal_shunt_cal_b_resistance(self) -> None: ...
    @property
    def ai_bridge_table_electrical_vals(self) -> list[float]: ...
    @ai_bridge_table_electrical_vals.setter
    def ai_bridge_table_electrical_vals(self, val: list[float]) -> None: ...
    @ai_bridge_table_electrical_vals.deleter
    def ai_bridge_table_electrical_vals(self) -> None: ...
    @property
    def ai_bridge_table_physical_vals(self) -> list[float]: ...
    @ai_bridge_table_physical_vals.setter
    def ai_bridge_table_physical_vals(self, val: list[float]) -> None: ...
    @ai_bridge_table_physical_vals.deleter
    def ai_bridge_table_physical_vals(self) -> None: ...
    @property
    def ai_bridge_two_point_lin_first_electrical_val(self) -> float: ...
    @ai_bridge_two_point_lin_first_electrical_val.setter
    def ai_bridge_two_point_lin_first_electrical_val(self, val: float) -> None: ...
    @ai_bridge_two_point_lin_first_electrical_val.deleter
    def ai_bridge_two_point_lin_first_electrical_val(self) -> None: ...
    @property
    def ai_bridge_two_point_lin_first_physical_val(self) -> float: ...
    @ai_bridge_two_point_lin_first_physical_val.setter
    def ai_bridge_two_point_lin_first_physical_val(self, val: float) -> None: ...
    @ai_bridge_two_point_lin_first_physical_val.deleter
    def ai_bridge_two_point_lin_first_physical_val(self) -> None: ...
    @property
    def ai_bridge_two_point_lin_second_electrical_val(self) -> float: ...
    @ai_bridge_two_point_lin_second_electrical_val.setter
    def ai_bridge_two_point_lin_second_electrical_val(self, val: float) -> None: ...
    @ai_bridge_two_point_lin_second_electrical_val.deleter
    def ai_bridge_two_point_lin_second_electrical_val(self) -> None: ...
    @property
    def ai_bridge_two_point_lin_second_physical_val(self) -> float: ...
    @ai_bridge_two_point_lin_second_physical_val.setter
    def ai_bridge_two_point_lin_second_physical_val(self, val: float) -> None: ...
    @ai_bridge_two_point_lin_second_physical_val.deleter
    def ai_bridge_two_point_lin_second_physical_val(self) -> None: ...
    @property
    def ai_bridge_units(self) -> BridgeUnits: ...
    @ai_bridge_units.setter
    def ai_bridge_units(self, val: BridgeUnits) -> None: ...
    @ai_bridge_units.deleter
    def ai_bridge_units(self) -> None: ...
    @property
    def ai_charge_units(self) -> ChargeUnits: ...
    @ai_charge_units.setter
    def ai_charge_units(self, val: ChargeUnits) -> None: ...
    @ai_charge_units.deleter
    def ai_charge_units(self) -> None: ...
    @property
    def ai_chop_enable(self) -> bool: ...
    @ai_chop_enable.setter
    def ai_chop_enable(self, val: bool) -> None: ...
    @ai_chop_enable.deleter
    def ai_chop_enable(self) -> None: ...
    @property
    def ai_coupling(self) -> Coupling: ...
    @ai_coupling.setter
    def ai_coupling(self, val: Coupling) -> None: ...
    @ai_coupling.deleter
    def ai_coupling(self) -> None: ...
    @property
    def ai_current_acrms_units(self) -> CurrentUnits: ...
    @ai_current_acrms_units.setter
    def ai_current_acrms_units(self, val: CurrentUnits) -> None: ...
    @ai_current_acrms_units.deleter
    def ai_current_acrms_units(self) -> None: ...
    @property
    def ai_current_shunt_loc(self) -> CurrentShuntResistorLocation: ...
    @ai_current_shunt_loc.setter
    def ai_current_shunt_loc(self, val: CurrentShuntResistorLocation) -> None: ...
    @ai_current_shunt_loc.deleter
    def ai_current_shunt_loc(self) -> None: ...
    @property
    def ai_current_shunt_resistance(self) -> float: ...
    @ai_current_shunt_resistance.setter
    def ai_current_shunt_resistance(self, val: float) -> None: ...
    @ai_current_shunt_resistance.deleter
    def ai_current_shunt_resistance(self) -> None: ...
    @property
    def ai_current_units(self) -> CurrentUnits: ...
    @ai_current_units.setter
    def ai_current_units(self, val: CurrentUnits) -> None: ...
    @ai_current_units.deleter
    def ai_current_units(self) -> None: ...
    @property
    def ai_custom_scale(self) -> Scale: ...
    @ai_custom_scale.setter
    def ai_custom_scale(self, val: Scale) -> None: ...
    @ai_custom_scale.deleter
    def ai_custom_scale(self) -> None: ...
    @property
    def ai_data_xfer_custom_threshold(self) -> int: ...
    @ai_data_xfer_custom_threshold.setter
    def ai_data_xfer_custom_threshold(self, val: int) -> None: ...
    @ai_data_xfer_custom_threshold.deleter
    def ai_data_xfer_custom_threshold(self) -> None: ...
    @property
    def ai_data_xfer_max_rate(self) -> float: ...
    @ai_data_xfer_max_rate.setter
    def ai_data_xfer_max_rate(self, val: float) -> None: ...
    @ai_data_xfer_max_rate.deleter
    def ai_data_xfer_max_rate(self) -> None: ...
    @property
    def ai_data_xfer_mech(self) -> DataTransferActiveTransferMode: ...
    @ai_data_xfer_mech.setter
    def ai_data_xfer_mech(self, val: DataTransferActiveTransferMode) -> None: ...
    @ai_data_xfer_mech.deleter
    def ai_data_xfer_mech(self) -> None: ...
    @property
    def ai_data_xfer_req_cond(self) -> InputDataTransferCondition: ...
    @ai_data_xfer_req_cond.setter
    def ai_data_xfer_req_cond(self, val: InputDataTransferCondition) -> None: ...
    @ai_data_xfer_req_cond.deleter
    def ai_data_xfer_req_cond(self) -> None: ...
    @property
    def ai_dc_offset(self) -> float: ...
    @ai_dc_offset.setter
    def ai_dc_offset(self, val: float) -> None: ...
    @ai_dc_offset.deleter
    def ai_dc_offset(self) -> None: ...
    @property
    def ai_dev_scaling_coeff(self) -> list[float]: ...
    @property
    def ai_dig_fltr_bandpass_center_freq(self) -> float: ...
    @ai_dig_fltr_bandpass_center_freq.setter
    def ai_dig_fltr_bandpass_center_freq(self, val: float) -> None: ...
    @ai_dig_fltr_bandpass_center_freq.deleter
    def ai_dig_fltr_bandpass_center_freq(self) -> None: ...
    @property
    def ai_dig_fltr_bandpass_width(self) -> float: ...
    @ai_dig_fltr_bandpass_width.setter
    def ai_dig_fltr_bandpass_width(self, val: float) -> None: ...
    @ai_dig_fltr_bandpass_width.deleter
    def ai_dig_fltr_bandpass_width(self) -> None: ...
    @property
    def ai_dig_fltr_coeff(self) -> list[float]: ...
    @ai_dig_fltr_coeff.setter
    def ai_dig_fltr_coeff(self, val: list[float]) -> None: ...
    @ai_dig_fltr_coeff.deleter
    def ai_dig_fltr_coeff(self) -> None: ...
    @property
    def ai_dig_fltr_enable(self) -> bool: ...
    @ai_dig_fltr_enable.setter
    def ai_dig_fltr_enable(self, val: bool) -> None: ...
    @ai_dig_fltr_enable.deleter
    def ai_dig_fltr_enable(self) -> None: ...
    @property
    def ai_dig_fltr_highpass_cutoff_freq(self) -> float: ...
    @ai_dig_fltr_highpass_cutoff_freq.setter
    def ai_dig_fltr_highpass_cutoff_freq(self, val: float) -> None: ...
    @ai_dig_fltr_highpass_cutoff_freq.deleter
    def ai_dig_fltr_highpass_cutoff_freq(self) -> None: ...
    @property
    def ai_dig_fltr_lowpass_cutoff_freq(self) -> float: ...
    @ai_dig_fltr_lowpass_cutoff_freq.setter
    def ai_dig_fltr_lowpass_cutoff_freq(self, val: float) -> None: ...
    @ai_dig_fltr_lowpass_cutoff_freq.deleter
    def ai_dig_fltr_lowpass_cutoff_freq(self) -> None: ...
    @property
    def ai_dig_fltr_notch_center_freq(self) -> float: ...
    @ai_dig_fltr_notch_center_freq.setter
    def ai_dig_fltr_notch_center_freq(self, val: float) -> None: ...
    @ai_dig_fltr_notch_center_freq.deleter
    def ai_dig_fltr_notch_center_freq(self) -> None: ...
    @property
    def ai_dig_fltr_notch_width(self) -> float: ...
    @ai_dig_fltr_notch_width.setter
    def ai_dig_fltr_notch_width(self, val: float) -> None: ...
    @ai_dig_fltr_notch_width.deleter
    def ai_dig_fltr_notch_width(self) -> None: ...
    @property
    def ai_dig_fltr_order(self) -> int: ...
    @ai_dig_fltr_order.setter
    def ai_dig_fltr_order(self, val: int) -> None: ...
    @ai_dig_fltr_order.deleter
    def ai_dig_fltr_order(self) -> None: ...
    @property
    def ai_dig_fltr_response(self) -> FilterResponse: ...
    @ai_dig_fltr_response.setter
    def ai_dig_fltr_response(self, val: FilterResponse) -> None: ...
    @ai_dig_fltr_response.deleter
    def ai_dig_fltr_response(self) -> None: ...
    @property
    def ai_dig_fltr_type(self) -> FilterType: ...
    @ai_dig_fltr_type.setter
    def ai_dig_fltr_type(self, val: FilterType) -> None: ...
    @ai_dig_fltr_type.deleter
    def ai_dig_fltr_type(self) -> None: ...
    @property
    def ai_dither_enable(self) -> bool: ...
    @ai_dither_enable.setter
    def ai_dither_enable(self, val: bool) -> None: ...
    @ai_dither_enable.deleter
    def ai_dither_enable(self) -> None: ...
    @property
    def ai_eddy_current_prox_sensitivity(self) -> float: ...
    @ai_eddy_current_prox_sensitivity.setter
    def ai_eddy_current_prox_sensitivity(self, val: float) -> None: ...
    @ai_eddy_current_prox_sensitivity.deleter
    def ai_eddy_current_prox_sensitivity(self) -> None: ...
    @property
    def ai_eddy_current_prox_sensitivity_units(
        self,
    ) -> EddyCurrentProxProbeSensitivityUnits: ...
    @ai_eddy_current_prox_sensitivity_units.setter
    def ai_eddy_current_prox_sensitivity_units(
        self, val: EddyCurrentProxProbeSensitivityUnits
    ) -> None: ...
    @ai_eddy_current_prox_sensitivity_units.deleter
    def ai_eddy_current_prox_sensitivity_units(self) -> None: ...
    @property
    def ai_eddy_current_prox_units(self) -> LengthUnits: ...
    @ai_eddy_current_prox_units.setter
    def ai_eddy_current_prox_units(self, val: LengthUnits) -> None: ...
    @ai_eddy_current_prox_units.deleter
    def ai_eddy_current_prox_units(self) -> None: ...
    @property
    def ai_enhanced_alias_rejection_enable(self) -> bool: ...
    @ai_enhanced_alias_rejection_enable.setter
    def ai_enhanced_alias_rejection_enable(self, val: bool) -> None: ...
    @ai_enhanced_alias_rejection_enable.deleter
    def ai_enhanced_alias_rejection_enable(self) -> None: ...
    @property
    def ai_excit_actual_val(self) -> float: ...
    @ai_excit_actual_val.setter
    def ai_excit_actual_val(self, val: float) -> None: ...
    @ai_excit_actual_val.deleter
    def ai_excit_actual_val(self) -> None: ...
    @property
    def ai_excit_d_cor_ac(self) -> ExcitationDCorAC: ...
    @ai_excit_d_cor_ac.setter
    def ai_excit_d_cor_ac(self, val: ExcitationDCorAC) -> None: ...
    @ai_excit_d_cor_ac.deleter
    def ai_excit_d_cor_ac(self) -> None: ...
    @property
    def ai_excit_idle_output_behavior(self) -> ExcitationIdleOutputBehavior: ...
    @ai_excit_idle_output_behavior.setter
    def ai_excit_idle_output_behavior(
        self, val: ExcitationIdleOutputBehavior
    ) -> None: ...
    @ai_excit_idle_output_behavior.deleter
    def ai_excit_idle_output_behavior(self) -> None: ...
    @property
    def ai_excit_sense(self) -> Sense: ...
    @ai_excit_sense.setter
    def ai_excit_sense(self, val: Sense) -> None: ...
    @ai_excit_sense.deleter
    def ai_excit_sense(self) -> None: ...
    @property
    def ai_excit_src(self) -> ExcitationSource: ...
    @ai_excit_src.setter
    def ai_excit_src(self, val: ExcitationSource) -> None: ...
    @ai_excit_src.deleter
    def ai_excit_src(self) -> None: ...
    @property
    def ai_excit_use_for_scaling(self) -> bool: ...
    @ai_excit_use_for_scaling.setter
    def ai_excit_use_for_scaling(self, val: bool) -> None: ...
    @ai_excit_use_for_scaling.deleter
    def ai_excit_use_for_scaling(self) -> None: ...
    @property
    def ai_excit_use_multiplexed(self) -> bool: ...
    @ai_excit_use_multiplexed.setter
    def ai_excit_use_multiplexed(self, val: bool) -> None: ...
    @ai_excit_use_multiplexed.deleter
    def ai_excit_use_multiplexed(self) -> None: ...
    @property
    def ai_excit_val(self) -> float: ...
    @ai_excit_val.setter
    def ai_excit_val(self, val: float) -> None: ...
    @ai_excit_val.deleter
    def ai_excit_val(self) -> None: ...
    @property
    def ai_excit_voltage_or_current(self) -> ExcitationVoltageOrCurrent: ...
    @ai_excit_voltage_or_current.setter
    def ai_excit_voltage_or_current(self, val: ExcitationVoltageOrCurrent) -> None: ...
    @ai_excit_voltage_or_current.deleter
    def ai_excit_voltage_or_current(self) -> None: ...
    @property
    def ai_filter_delay(self) -> float: ...
    @property
    def ai_filter_delay_adjustment(self) -> float: ...
    @ai_filter_delay_adjustment.setter
    def ai_filter_delay_adjustment(self, val: float) -> None: ...
    @ai_filter_delay_adjustment.deleter
    def ai_filter_delay_adjustment(self) -> None: ...
    @property
    def ai_filter_delay_units(self) -> DigitalWidthUnits: ...
    @ai_filter_delay_units.setter
    def ai_filter_delay_units(self, val: DigitalWidthUnits) -> None: ...
    @ai_filter_delay_units.deleter
    def ai_filter_delay_units(self) -> None: ...
    @property
    def ai_filter_enable(self) -> bool: ...
    @ai_filter_enable.setter
    def ai_filter_enable(self, val: bool) -> None: ...
    @ai_filter_enable.deleter
    def ai_filter_enable(self) -> None: ...
    @property
    def ai_filter_freq(self) -> float: ...
    @ai_filter_freq.setter
    def ai_filter_freq(self, val: float) -> None: ...
    @ai_filter_freq.deleter
    def ai_filter_freq(self) -> None: ...
    @property
    def ai_filter_order(self) -> int: ...
    @ai_filter_order.setter
    def ai_filter_order(self, val: int) -> None: ...
    @ai_filter_order.deleter
    def ai_filter_order(self) -> None: ...
    @property
    def ai_filter_response(self) -> FilterResponse: ...
    @ai_filter_response.setter
    def ai_filter_response(self, val: FilterResponse) -> None: ...
    @ai_filter_response.deleter
    def ai_filter_response(self) -> None: ...
    @property
    def ai_force_iepe_sensor_sensitivity(self) -> float: ...
    @ai_force_iepe_sensor_sensitivity.setter
    def ai_force_iepe_sensor_sensitivity(self, val: float) -> None: ...
    @ai_force_iepe_sensor_sensitivity.deleter
    def ai_force_iepe_sensor_sensitivity(self) -> None: ...
    @property
    def ai_force_iepe_sensor_sensitivity_units(
        self,
    ) -> ForceIEPESensorSensitivityUnits: ...
    @ai_force_iepe_sensor_sensitivity_units.setter
    def ai_force_iepe_sensor_sensitivity_units(
        self, val: ForceIEPESensorSensitivityUnits
    ) -> None: ...
    @ai_force_iepe_sensor_sensitivity_units.deleter
    def ai_force_iepe_sensor_sensitivity_units(self) -> None: ...
    @property
    def ai_force_read_from_chan(self) -> bool: ...
    @ai_force_read_from_chan.setter
    def ai_force_read_from_chan(self, val: bool) -> None: ...
    @ai_force_read_from_chan.deleter
    def ai_force_read_from_chan(self) -> None: ...
    @property
    def ai_force_units(self) -> ForceUnits: ...
    @ai_force_units.setter
    def ai_force_units(self, val: ForceUnits) -> None: ...
    @ai_force_units.deleter
    def ai_force_units(self) -> None: ...
    @property
    def ai_freq_hyst(self) -> float: ...
    @ai_freq_hyst.setter
    def ai_freq_hyst(self, val: float) -> None: ...
    @ai_freq_hyst.deleter
    def ai_freq_hyst(self) -> None: ...
    @property
    def ai_freq_thresh_voltage(self) -> float: ...
    @ai_freq_thresh_voltage.setter
    def ai_freq_thresh_voltage(self, val: float) -> None: ...
    @ai_freq_thresh_voltage.deleter
    def ai_freq_thresh_voltage(self) -> None: ...
    @property
    def ai_freq_units(self) -> FrequencyUnits: ...
    @ai_freq_units.setter
    def ai_freq_units(self, val: FrequencyUnits) -> None: ...
    @ai_freq_units.deleter
    def ai_freq_units(self) -> None: ...
    @property
    def ai_gain(self) -> float: ...
    @ai_gain.setter
    def ai_gain(self, val: float) -> None: ...
    @ai_gain.deleter
    def ai_gain(self) -> None: ...
    @property
    def ai_impedance(self) -> Impedance1: ...
    @ai_impedance.setter
    def ai_impedance(self, val: Impedance1) -> None: ...
    @ai_impedance.deleter
    def ai_impedance(self) -> None: ...
    @property
    def ai_input_limits_fault_detect_enable(self) -> bool: ...
    @ai_input_limits_fault_detect_enable.setter
    def ai_input_limits_fault_detect_enable(self, val: bool) -> None: ...
    @ai_input_limits_fault_detect_enable.deleter
    def ai_input_limits_fault_detect_enable(self) -> None: ...
    @property
    def ai_input_limits_fault_detect_lower_limit(self) -> float: ...
    @ai_input_limits_fault_detect_lower_limit.setter
    def ai_input_limits_fault_detect_lower_limit(self, val: float) -> None: ...
    @ai_input_limits_fault_detect_lower_limit.deleter
    def ai_input_limits_fault_detect_lower_limit(self) -> None: ...
    @property
    def ai_input_limits_fault_detect_upper_limit(self) -> float: ...
    @ai_input_limits_fault_detect_upper_limit.setter
    def ai_input_limits_fault_detect_upper_limit(self, val: float) -> None: ...
    @ai_input_limits_fault_detect_upper_limit.deleter
    def ai_input_limits_fault_detect_upper_limit(self) -> None: ...
    @property
    def ai_input_src(self) -> str: ...
    @ai_input_src.setter
    def ai_input_src(self, val: str) -> None: ...
    @ai_input_src.deleter
    def ai_input_src(self) -> None: ...
    @property
    def ai_lead_wire_resistance(self) -> float: ...
    @ai_lead_wire_resistance.setter
    def ai_lead_wire_resistance(self, val: float) -> None: ...
    @ai_lead_wire_resistance.deleter
    def ai_lead_wire_resistance(self) -> None: ...
    @property
    def ai_lossy_lsb_removal_compressed_samp_size(self) -> int: ...
    @ai_lossy_lsb_removal_compressed_samp_size.setter
    def ai_lossy_lsb_removal_compressed_samp_size(self, val: int) -> None: ...
    @ai_lossy_lsb_removal_compressed_samp_size.deleter
    def ai_lossy_lsb_removal_compressed_samp_size(self) -> None: ...
    @property
    def ai_lowpass_cutoff_freq(self) -> float: ...
    @ai_lowpass_cutoff_freq.setter
    def ai_lowpass_cutoff_freq(self, val: float) -> None: ...
    @ai_lowpass_cutoff_freq.deleter
    def ai_lowpass_cutoff_freq(self) -> None: ...
    @property
    def ai_lowpass_enable(self) -> bool: ...
    @ai_lowpass_enable.setter
    def ai_lowpass_enable(self, val: bool) -> None: ...
    @ai_lowpass_enable.deleter
    def ai_lowpass_enable(self) -> None: ...
    @property
    def ai_lowpass_switch_cap_clk_src(self) -> SourceSelection: ...
    @ai_lowpass_switch_cap_clk_src.setter
    def ai_lowpass_switch_cap_clk_src(self, val: SourceSelection) -> None: ...
    @ai_lowpass_switch_cap_clk_src.deleter
    def ai_lowpass_switch_cap_clk_src(self) -> None: ...
    @property
    def ai_lowpass_switch_cap_ext_clk_div(self) -> int: ...
    @ai_lowpass_switch_cap_ext_clk_div.setter
    def ai_lowpass_switch_cap_ext_clk_div(self, val: int) -> None: ...
    @ai_lowpass_switch_cap_ext_clk_div.deleter
    def ai_lowpass_switch_cap_ext_clk_div(self) -> None: ...
    @property
    def ai_lowpass_switch_cap_ext_clk_freq(self) -> float: ...
    @ai_lowpass_switch_cap_ext_clk_freq.setter
    def ai_lowpass_switch_cap_ext_clk_freq(self, val: float) -> None: ...
    @ai_lowpass_switch_cap_ext_clk_freq.deleter
    def ai_lowpass_switch_cap_ext_clk_freq(self) -> None: ...
    @property
    def ai_lowpass_switch_cap_out_clk_div(self) -> int: ...
    @ai_lowpass_switch_cap_out_clk_div.setter
    def ai_lowpass_switch_cap_out_clk_div(self, val: int) -> None: ...
    @ai_lowpass_switch_cap_out_clk_div.deleter
    def ai_lowpass_switch_cap_out_clk_div(self) -> None: ...
    @property
    def ai_lvdt_sensitivity(self) -> float: ...
    @ai_lvdt_sensitivity.setter
    def ai_lvdt_sensitivity(self, val: float) -> None: ...
    @ai_lvdt_sensitivity.deleter
    def ai_lvdt_sensitivity(self) -> None: ...
    @property
    def ai_lvdt_sensitivity_units(self) -> LVDTSensitivityUnits: ...
    @ai_lvdt_sensitivity_units.setter
    def ai_lvdt_sensitivity_units(self, val: LVDTSensitivityUnits) -> None: ...
    @ai_lvdt_sensitivity_units.deleter
    def ai_lvdt_sensitivity_units(self) -> None: ...
    @property
    def ai_lvdt_units(self) -> LengthUnits: ...
    @ai_lvdt_units.setter
    def ai_lvdt_units(self, val: LengthUnits) -> None: ...
    @ai_lvdt_units.deleter
    def ai_lvdt_units(self) -> None: ...
    @property
    def ai_max(self) -> float: ...
    @ai_max.setter
    def ai_max(self, val: float) -> None: ...
    @ai_max.deleter
    def ai_max(self) -> None: ...
    @property
    def ai_meas_type(self) -> UsageTypeAI: ...
    @property
    def ai_mem_map_enable(self) -> bool: ...
    @ai_mem_map_enable.setter
    def ai_mem_map_enable(self, val: bool) -> None: ...
    @ai_mem_map_enable.deleter
    def ai_mem_map_enable(self) -> None: ...
    @property
    def ai_microphone_sensitivity(self) -> float: ...
    @ai_microphone_sensitivity.setter
    def ai_microphone_sensitivity(self, val: float) -> None: ...
    @ai_microphone_sensitivity.deleter
    def ai_microphone_sensitivity(self) -> None: ...
    @property
    def ai_min(self) -> float: ...
    @ai_min.setter
    def ai_min(self, val: float) -> None: ...
    @ai_min.deleter
    def ai_min(self) -> None: ...
    @property
    def ai_open_chan_detect_enable(self) -> bool: ...
    @ai_open_chan_detect_enable.setter
    def ai_open_chan_detect_enable(self, val: bool) -> None: ...
    @ai_open_chan_detect_enable.deleter
    def ai_open_chan_detect_enable(self) -> None: ...
    @property
    def ai_open_thrmcpl_detect_enable(self) -> bool: ...
    @ai_open_thrmcpl_detect_enable.setter
    def ai_open_thrmcpl_detect_enable(self, val: bool) -> None: ...
    @ai_open_thrmcpl_detect_enable.deleter
    def ai_open_thrmcpl_detect_enable(self) -> None: ...
    @property
    def ai_overcurrent_detect_enable(self) -> bool: ...
    @ai_overcurrent_detect_enable.setter
    def ai_overcurrent_detect_enable(self, val: bool) -> None: ...
    @ai_overcurrent_detect_enable.deleter
    def ai_overcurrent_detect_enable(self) -> None: ...
    @property
    def ai_power_supply_fault_detect_enable(self) -> bool: ...
    @ai_power_supply_fault_detect_enable.setter
    def ai_power_supply_fault_detect_enable(self, val: bool) -> None: ...
    @ai_power_supply_fault_detect_enable.deleter
    def ai_power_supply_fault_detect_enable(self) -> None: ...
    @property
    def ai_pressure_units(self) -> PressureUnits: ...
    @ai_pressure_units.setter
    def ai_pressure_units(self, val: PressureUnits) -> None: ...
    @ai_pressure_units.deleter
    def ai_pressure_units(self) -> None: ...
    @property
    def ai_probe_atten(self) -> float: ...
    @ai_probe_atten.setter
    def ai_probe_atten(self, val: float) -> None: ...
    @ai_probe_atten.deleter
    def ai_probe_atten(self) -> None: ...
    @property
    def ai_raw_data_compression_type(self) -> RawDataCompressionType: ...
    @ai_raw_data_compression_type.setter
    def ai_raw_data_compression_type(self, val: RawDataCompressionType) -> None: ...
    @ai_raw_data_compression_type.deleter
    def ai_raw_data_compression_type(self) -> None: ...
    @property
    def ai_raw_samp_justification(self) -> DataJustification: ...
    @property
    def ai_raw_samp_size(self) -> int: ...
    @property
    def ai_remove_filter_delay(self) -> bool: ...
    @ai_remove_filter_delay.setter
    def ai_remove_filter_delay(self, val: bool) -> None: ...
    @ai_remove_filter_delay.deleter
    def ai_remove_filter_delay(self) -> None: ...
    @property
    def ai_resistance_cfg(self) -> ResistanceConfiguration: ...
    @ai_resistance_cfg.setter
    def ai_resistance_cfg(self, val: ResistanceConfiguration) -> None: ...
    @ai_resistance_cfg.deleter
    def ai_resistance_cfg(self) -> None: ...
    @property
    def ai_resistance_units(self) -> ResistanceUnits: ...
    @ai_resistance_units.setter
    def ai_resistance_units(self, val: ResistanceUnits) -> None: ...
    @ai_resistance_units.deleter
    def ai_resistance_units(self) -> None: ...
    @property
    def ai_resolution(self) -> float: ...
    @property
    def ai_resolution_units(self) -> ResolutionType: ...
    @property
    def ai_rng_high(self) -> float: ...
    @ai_rng_high.setter
    def ai_rng_high(self, val: float) -> None: ...
    @ai_rng_high.deleter
    def ai_rng_high(self) -> None: ...
    @property
    def ai_rng_low(self) -> float: ...
    @ai_rng_low.setter
    def ai_rng_low(self, val: float) -> None: ...
    @ai_rng_low.deleter
    def ai_rng_low(self) -> None: ...
    @property
    def ai_rosette_strain_gage_gage_orientation(self) -> float: ...
    @ai_rosette_strain_gage_gage_orientation.setter
    def ai_rosette_strain_gage_gage_orientation(self, val: float) -> None: ...
    @ai_rosette_strain_gage_gage_orientation.deleter
    def ai_rosette_strain_gage_gage_orientation(self) -> None: ...
    @property
    def ai_rosette_strain_gage_rosette_meas_type(
        self,
    ) -> StrainGageRosetteMeasurementType: ...
    @ai_rosette_strain_gage_rosette_meas_type.setter
    def ai_rosette_strain_gage_rosette_meas_type(
        self, val: StrainGageRosetteMeasurementType
    ) -> None: ...
    @ai_rosette_strain_gage_rosette_meas_type.deleter
    def ai_rosette_strain_gage_rosette_meas_type(self) -> None: ...
    @property
    def ai_rosette_strain_gage_rosette_type(self) -> StrainGageRosetteType: ...
    @property
    def ai_rosette_strain_gage_strain_chans(self) -> list[str]: ...
    @property
    def ai_rtd_a(self) -> float: ...
    @ai_rtd_a.setter
    def ai_rtd_a(self, val: float) -> None: ...
    @ai_rtd_a.deleter
    def ai_rtd_a(self) -> None: ...
    @property
    def ai_rtd_b(self) -> float: ...
    @ai_rtd_b.setter
    def ai_rtd_b(self, val: float) -> None: ...
    @ai_rtd_b.deleter
    def ai_rtd_b(self) -> None: ...
    @property
    def ai_rtd_c(self) -> float: ...
    @ai_rtd_c.setter
    def ai_rtd_c(self, val: float) -> None: ...
    @ai_rtd_c.deleter
    def ai_rtd_c(self) -> None: ...
    @property
    def ai_rtd_r0(self) -> float: ...
    @ai_rtd_r0.setter
    def ai_rtd_r0(self, val: float) -> None: ...
    @ai_rtd_r0.deleter
    def ai_rtd_r0(self) -> None: ...
    @property
    def ai_rtd_type(self) -> RTDType: ...
    @ai_rtd_type.setter
    def ai_rtd_type(self, val: RTDType) -> None: ...
    @ai_rtd_type.deleter
    def ai_rtd_type(self) -> None: ...
    @property
    def ai_rvdt_sensitivity(self) -> float: ...
    @ai_rvdt_sensitivity.setter
    def ai_rvdt_sensitivity(self, val: float) -> None: ...
    @ai_rvdt_sensitivity.deleter
    def ai_rvdt_sensitivity(self) -> None: ...
    @property
    def ai_rvdt_sensitivity_units(self) -> RVDTSensitivityUnits: ...
    @ai_rvdt_sensitivity_units.setter
    def ai_rvdt_sensitivity_units(self, val: RVDTSensitivityUnits) -> None: ...
    @ai_rvdt_sensitivity_units.deleter
    def ai_rvdt_sensitivity_units(self) -> None: ...
    @property
    def ai_rvdt_units(self) -> AngleUnits: ...
    @ai_rvdt_units.setter
    def ai_rvdt_units(self, val: AngleUnits) -> None: ...
    @ai_rvdt_units.deleter
    def ai_rvdt_units(self) -> None: ...
    @property
    def ai_samp_and_hold_enable(self) -> bool: ...
    @ai_samp_and_hold_enable.setter
    def ai_samp_and_hold_enable(self, val: bool) -> None: ...
    @ai_samp_and_hold_enable.deleter
    def ai_samp_and_hold_enable(self) -> None: ...
    @property
    def ai_sensor_power_cfg(self) -> SensorPowerCfg: ...
    @ai_sensor_power_cfg.setter
    def ai_sensor_power_cfg(self, val: SensorPowerCfg) -> None: ...
    @ai_sensor_power_cfg.deleter
    def ai_sensor_power_cfg(self) -> None: ...
    @property
    def ai_sensor_power_type(self) -> SensorPowerType: ...
    @ai_sensor_power_type.setter
    def ai_sensor_power_type(self, val: SensorPowerType) -> None: ...
    @ai_sensor_power_type.deleter
    def ai_sensor_power_type(self) -> None: ...
    @property
    def ai_sensor_power_voltage(self) -> float: ...
    @ai_sensor_power_voltage.setter
    def ai_sensor_power_voltage(self, val: float) -> None: ...
    @ai_sensor_power_voltage.deleter
    def ai_sensor_power_voltage(self) -> None: ...
    @property
    def ai_sound_pressure_db_ref(self) -> float: ...
    @ai_sound_pressure_db_ref.setter
    def ai_sound_pressure_db_ref(self, val: float) -> None: ...
    @ai_sound_pressure_db_ref.deleter
    def ai_sound_pressure_db_ref(self) -> None: ...
    @property
    def ai_sound_pressure_max_sound_pressure_lvl(self) -> float: ...
    @ai_sound_pressure_max_sound_pressure_lvl.setter
    def ai_sound_pressure_max_sound_pressure_lvl(self, val: float) -> None: ...
    @ai_sound_pressure_max_sound_pressure_lvl.deleter
    def ai_sound_pressure_max_sound_pressure_lvl(self) -> None: ...
    @property
    def ai_sound_pressure_units(self) -> SoundPressureUnits: ...
    @ai_sound_pressure_units.setter
    def ai_sound_pressure_units(self, val: SoundPressureUnits) -> None: ...
    @ai_sound_pressure_units.deleter
    def ai_sound_pressure_units(self) -> None: ...
    @property
    def ai_strain_force_read_from_chan(self) -> bool: ...
    @ai_strain_force_read_from_chan.setter
    def ai_strain_force_read_from_chan(self, val: bool) -> None: ...
    @ai_strain_force_read_from_chan.deleter
    def ai_strain_force_read_from_chan(self) -> None: ...
    @property
    def ai_strain_gage_cfg(self) -> StrainGageBridgeType: ...
    @ai_strain_gage_cfg.setter
    def ai_strain_gage_cfg(self, val: StrainGageBridgeType) -> None: ...
    @ai_strain_gage_cfg.deleter
    def ai_strain_gage_cfg(self) -> None: ...
    @property
    def ai_strain_gage_gage_factor(self) -> float: ...
    @ai_strain_gage_gage_factor.setter
    def ai_strain_gage_gage_factor(self, val: float) -> None: ...
    @ai_strain_gage_gage_factor.deleter
    def ai_strain_gage_gage_factor(self) -> None: ...
    @property
    def ai_strain_gage_poisson_ratio(self) -> float: ...
    @ai_strain_gage_poisson_ratio.setter
    def ai_strain_gage_poisson_ratio(self, val: float) -> None: ...
    @ai_strain_gage_poisson_ratio.deleter
    def ai_strain_gage_poisson_ratio(self) -> None: ...
    @property
    def ai_strain_units(self) -> StrainUnits: ...
    @ai_strain_units.setter
    def ai_strain_units(self, val: StrainUnits) -> None: ...
    @ai_strain_units.deleter
    def ai_strain_units(self) -> None: ...
    @property
    def ai_teds_is_teds(self) -> bool: ...
    @property
    def ai_teds_units(self) -> str: ...
    @property
    def ai_temp_units(self) -> TemperatureUnits: ...
    @ai_temp_units.setter
    def ai_temp_units(self, val: TemperatureUnits) -> None: ...
    @ai_temp_units.deleter
    def ai_temp_units(self) -> None: ...
    @property
    def ai_term_cfg(self) -> TerminalConfiguration: ...
    @ai_term_cfg.setter
    def ai_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ai_term_cfg.deleter
    def ai_term_cfg(self) -> None: ...
    @property
    def ai_thrmcpl_cjc_chan(self) -> Channel: ...
    @property
    def ai_thrmcpl_cjc_src(self) -> CJCSource: ...
    @property
    def ai_thrmcpl_cjc_val(self) -> float: ...
    @ai_thrmcpl_cjc_val.setter
    def ai_thrmcpl_cjc_val(self, val: float) -> None: ...
    @ai_thrmcpl_cjc_val.deleter
    def ai_thrmcpl_cjc_val(self) -> None: ...
    @property
    def ai_thrmcpl_lead_offset_voltage(self) -> float: ...
    @ai_thrmcpl_lead_offset_voltage.setter
    def ai_thrmcpl_lead_offset_voltage(self, val: float) -> None: ...
    @ai_thrmcpl_lead_offset_voltage.deleter
    def ai_thrmcpl_lead_offset_voltage(self) -> None: ...
    @property
    def ai_thrmcpl_scale_type(self) -> ScaleType: ...
    @ai_thrmcpl_scale_type.setter
    def ai_thrmcpl_scale_type(self, val: ScaleType) -> None: ...
    @ai_thrmcpl_scale_type.deleter
    def ai_thrmcpl_scale_type(self) -> None: ...
    @property
    def ai_thrmcpl_type(self) -> ThermocoupleType: ...
    @ai_thrmcpl_type.setter
    def ai_thrmcpl_type(self, val: ThermocoupleType) -> None: ...
    @ai_thrmcpl_type.deleter
    def ai_thrmcpl_type(self) -> None: ...
    @property
    def ai_thrmstr_a(self) -> float: ...
    @ai_thrmstr_a.setter
    def ai_thrmstr_a(self, val: float) -> None: ...
    @ai_thrmstr_a.deleter
    def ai_thrmstr_a(self) -> None: ...
    @property
    def ai_thrmstr_b(self) -> float: ...
    @ai_thrmstr_b.setter
    def ai_thrmstr_b(self, val: float) -> None: ...
    @ai_thrmstr_b.deleter
    def ai_thrmstr_b(self) -> None: ...
    @property
    def ai_thrmstr_c(self) -> float: ...
    @ai_thrmstr_c.setter
    def ai_thrmstr_c(self, val: float) -> None: ...
    @ai_thrmstr_c.deleter
    def ai_thrmstr_c(self) -> None: ...
    @property
    def ai_thrmstr_r1(self) -> float: ...
    @ai_thrmstr_r1.setter
    def ai_thrmstr_r1(self, val: float) -> None: ...
    @ai_thrmstr_r1.deleter
    def ai_thrmstr_r1(self) -> None: ...
    @property
    def ai_torque_units(self) -> TorqueUnits: ...
    @ai_torque_units.setter
    def ai_torque_units(self, val: TorqueUnits) -> None: ...
    @ai_torque_units.deleter
    def ai_torque_units(self) -> None: ...
    @property
    def ai_usb_xfer_req_count(self) -> int: ...
    @ai_usb_xfer_req_count.setter
    def ai_usb_xfer_req_count(self, val: int) -> None: ...
    @ai_usb_xfer_req_count.deleter
    def ai_usb_xfer_req_count(self) -> None: ...
    @property
    def ai_usb_xfer_req_size(self) -> int: ...
    @ai_usb_xfer_req_size.setter
    def ai_usb_xfer_req_size(self, val: int) -> None: ...
    @ai_usb_xfer_req_size.deleter
    def ai_usb_xfer_req_size(self) -> None: ...
    @property
    def ai_velocity_iepe_sensor_db_ref(self) -> float: ...
    @ai_velocity_iepe_sensor_db_ref.setter
    def ai_velocity_iepe_sensor_db_ref(self, val: float) -> None: ...
    @ai_velocity_iepe_sensor_db_ref.deleter
    def ai_velocity_iepe_sensor_db_ref(self) -> None: ...
    @property
    def ai_velocity_iepe_sensor_sensitivity(self) -> float: ...
    @ai_velocity_iepe_sensor_sensitivity.setter
    def ai_velocity_iepe_sensor_sensitivity(self, val: float) -> None: ...
    @ai_velocity_iepe_sensor_sensitivity.deleter
    def ai_velocity_iepe_sensor_sensitivity(self) -> None: ...
    @property
    def ai_velocity_iepe_sensor_sensitivity_units(
        self,
    ) -> VelocityIEPESensorSensitivityUnits: ...
    @ai_velocity_iepe_sensor_sensitivity_units.setter
    def ai_velocity_iepe_sensor_sensitivity_units(
        self, val: VelocityIEPESensorSensitivityUnits
    ) -> None: ...
    @ai_velocity_iepe_sensor_sensitivity_units.deleter
    def ai_velocity_iepe_sensor_sensitivity_units(self) -> None: ...
    @property
    def ai_velocity_units(self) -> VelocityUnits: ...
    @ai_velocity_units.setter
    def ai_velocity_units(self, val: VelocityUnits) -> None: ...
    @ai_velocity_units.deleter
    def ai_velocity_units(self) -> None: ...
    @property
    def ai_voltage_acrms_units(self) -> VoltageUnits: ...
    @ai_voltage_acrms_units.setter
    def ai_voltage_acrms_units(self, val: VoltageUnits) -> None: ...
    @ai_voltage_acrms_units.deleter
    def ai_voltage_acrms_units(self) -> None: ...
    @property
    def ai_voltage_db_ref(self) -> float: ...
    @ai_voltage_db_ref.setter
    def ai_voltage_db_ref(self, val: float) -> None: ...
    @ai_voltage_db_ref.deleter
    def ai_voltage_db_ref(self) -> None: ...
    @property
    def ai_voltage_units(self) -> VoltageUnits: ...
    @ai_voltage_units.setter
    def ai_voltage_units(self, val: VoltageUnits) -> None: ...
    @ai_voltage_units.deleter
    def ai_voltage_units(self) -> None: ...
    @property
    def pwr_current_dev_scaling_coeff(self) -> list[float]: ...
    @property
    def pwr_current_setpoint(self) -> float: ...
    @pwr_current_setpoint.setter
    def pwr_current_setpoint(self, val: float) -> None: ...
    @pwr_current_setpoint.deleter
    def pwr_current_setpoint(self) -> None: ...
    @property
    def pwr_idle_output_behavior(self) -> PowerIdleOutputBehavior: ...
    @pwr_idle_output_behavior.setter
    def pwr_idle_output_behavior(self, val: PowerIdleOutputBehavior) -> None: ...
    @pwr_idle_output_behavior.deleter
    def pwr_idle_output_behavior(self) -> None: ...
    @property
    def pwr_output_enable(self) -> bool: ...
    @pwr_output_enable.setter
    def pwr_output_enable(self, val: bool) -> None: ...
    @pwr_output_enable.deleter
    def pwr_output_enable(self) -> None: ...
    @property
    def pwr_output_state(self) -> PowerOutputState: ...
    @property
    def pwr_remote_sense(self) -> Sense: ...
    @pwr_remote_sense.setter
    def pwr_remote_sense(self, val: Sense) -> None: ...
    @pwr_remote_sense.deleter
    def pwr_remote_sense(self) -> None: ...
    @property
    def pwr_voltage_dev_scaling_coeff(self) -> list[float]: ...
    @property
    def pwr_voltage_setpoint(self) -> float: ...
    @pwr_voltage_setpoint.setter
    def pwr_voltage_setpoint(self, val: float) -> None: ...
    @pwr_voltage_setpoint.deleter
    def pwr_voltage_setpoint(self) -> None: ...
    @property
    def ai_rtd_r_0(self) -> float: ...
    @ai_rtd_r_0.setter
    def ai_rtd_r_0(self, val: float) -> None: ...
    @ai_rtd_r_0.deleter
    def ai_rtd_r_0(self) -> None: ...
    @property
    def ai_sound_pressured_b_ref(self) -> float: ...
    @ai_sound_pressured_b_ref.setter
    def ai_sound_pressured_b_ref(self, val: float) -> None: ...
    @ai_sound_pressured_b_ref.deleter
    def ai_sound_pressured_b_ref(self) -> None: ...
    @property
    def ai_thrmstr_r_1(self) -> float: ...
    @ai_thrmstr_r_1.setter
    def ai_thrmstr_r_1(self, val: float) -> None: ...
    @ai_thrmstr_r_1.deleter
    def ai_thrmstr_r_1(self) -> None: ...
    @property
    def ai_acceld_b_ref(self) -> None: ...
    @ai_acceld_b_ref.setter
    def ai_acceld_b_ref(self, val: float) -> None: ...
    @ai_acceld_b_ref.deleter
    def ai_acceld_b_ref(self) -> None: ...
    @property
    def ai_voltaged_b_ref(self) -> None: ...
    @ai_voltaged_b_ref.setter
    def ai_voltaged_b_ref(self, val: float) -> None: ...
    @ai_voltaged_b_ref.deleter
    def ai_voltaged_b_ref(self) -> None: ...
    @property
    def ai_velocity_iepe_sensord_b_ref(self) -> None: ...
    @ai_velocity_iepe_sensord_b_ref.setter
    def ai_velocity_iepe_sensord_b_ref(self, val: float) -> None: ...
    @ai_velocity_iepe_sensord_b_ref.deleter
    def ai_velocity_iepe_sensord_b_ref(self) -> None: ...
