from ...task.channels._channel import Channel
from ...constants import (
    AOIdleOutputBehavior,
    CurrentUnits,
    DataTransferActiveTransferMode,
    DigitalWidthUnits,
    FuncGenType,
    ModulationType,
    OutputDataTransferCondition,
    ResolutionType,
    SourceSelection,
    TerminalConfiguration,
    UsageTypeAO,
    VoltageUnits,
)
from ...scale import Scale

class AOChannel(Channel):
    """
    Represents one or more analog output virtual channels and their properties.
    """

    __slots__ = ()

    def __repr__(self) -> str: ...
    @property
    def ao_common_mode_offset(self) -> float: ...
    @ao_common_mode_offset.setter
    def ao_common_mode_offset(self, val: float) -> None: ...
    @ao_common_mode_offset.deleter
    def ao_common_mode_offset(self) -> None: ...
    @property
    def ao_current_units(self) -> CurrentUnits: ...
    @ao_current_units.setter
    def ao_current_units(self, val: CurrentUnits) -> None: ...
    @ao_current_units.deleter
    def ao_current_units(self) -> None: ...
    @property
    def ao_custom_scale(self) -> Scale: ...
    @ao_custom_scale.setter
    def ao_custom_scale(self, val: Scale) -> None: ...
    @ao_custom_scale.deleter
    def ao_custom_scale(self) -> None: ...
    @property
    def ao_dac_offset_ext_src(self) -> str: ...
    @ao_dac_offset_ext_src.setter
    def ao_dac_offset_ext_src(self, val: str) -> None: ...
    @ao_dac_offset_ext_src.deleter
    def ao_dac_offset_ext_src(self) -> None: ...
    @property
    def ao_dac_offset_src(self) -> SourceSelection: ...
    @ao_dac_offset_src.setter
    def ao_dac_offset_src(self, val: SourceSelection) -> None: ...
    @ao_dac_offset_src.deleter
    def ao_dac_offset_src(self) -> None: ...
    @property
    def ao_dac_offset_val(self) -> float: ...
    @ao_dac_offset_val.setter
    def ao_dac_offset_val(self, val: float) -> None: ...
    @ao_dac_offset_val.deleter
    def ao_dac_offset_val(self) -> None: ...
    @property
    def ao_dac_ref_allow_conn_to_gnd(self) -> bool: ...
    @ao_dac_ref_allow_conn_to_gnd.setter
    def ao_dac_ref_allow_conn_to_gnd(self, val: bool) -> None: ...
    @ao_dac_ref_allow_conn_to_gnd.deleter
    def ao_dac_ref_allow_conn_to_gnd(self) -> None: ...
    @property
    def ao_dac_ref_conn_to_gnd(self) -> bool: ...
    @ao_dac_ref_conn_to_gnd.setter
    def ao_dac_ref_conn_to_gnd(self, val: bool) -> None: ...
    @ao_dac_ref_conn_to_gnd.deleter
    def ao_dac_ref_conn_to_gnd(self) -> None: ...
    @property
    def ao_dac_ref_ext_src(self) -> str: ...
    @ao_dac_ref_ext_src.setter
    def ao_dac_ref_ext_src(self, val: str) -> None: ...
    @ao_dac_ref_ext_src.deleter
    def ao_dac_ref_ext_src(self) -> None: ...
    @property
    def ao_dac_ref_src(self) -> SourceSelection: ...
    @ao_dac_ref_src.setter
    def ao_dac_ref_src(self, val: SourceSelection) -> None: ...
    @ao_dac_ref_src.deleter
    def ao_dac_ref_src(self) -> None: ...
    @property
    def ao_dac_ref_val(self) -> float: ...
    @ao_dac_ref_val.setter
    def ao_dac_ref_val(self, val: float) -> None: ...
    @ao_dac_ref_val.deleter
    def ao_dac_ref_val(self) -> None: ...
    @property
    def ao_dac_rng_high(self) -> float: ...
    @ao_dac_rng_high.setter
    def ao_dac_rng_high(self, val: float) -> None: ...
    @ao_dac_rng_high.deleter
    def ao_dac_rng_high(self) -> None: ...
    @property
    def ao_dac_rng_low(self) -> float: ...
    @ao_dac_rng_low.setter
    def ao_dac_rng_low(self, val: float) -> None: ...
    @ao_dac_rng_low.deleter
    def ao_dac_rng_low(self) -> None: ...
    @property
    def ao_data_xfer_mech(self) -> DataTransferActiveTransferMode: ...
    @ao_data_xfer_mech.setter
    def ao_data_xfer_mech(self, val: DataTransferActiveTransferMode) -> None: ...
    @ao_data_xfer_mech.deleter
    def ao_data_xfer_mech(self) -> None: ...
    @property
    def ao_data_xfer_req_cond(self) -> OutputDataTransferCondition: ...
    @ao_data_xfer_req_cond.setter
    def ao_data_xfer_req_cond(self, val: OutputDataTransferCondition) -> None: ...
    @ao_data_xfer_req_cond.deleter
    def ao_data_xfer_req_cond(self) -> None: ...
    @property
    def ao_dev_scaling_coeff(self) -> list[float]: ...
    @property
    def ao_enhanced_image_rejection_enable(self) -> bool: ...
    @ao_enhanced_image_rejection_enable.setter
    def ao_enhanced_image_rejection_enable(self, val: bool) -> None: ...
    @ao_enhanced_image_rejection_enable.deleter
    def ao_enhanced_image_rejection_enable(self) -> None: ...
    @property
    def ao_filter_delay(self) -> float: ...
    @ao_filter_delay.setter
    def ao_filter_delay(self, val: float) -> None: ...
    @ao_filter_delay.deleter
    def ao_filter_delay(self) -> None: ...
    @property
    def ao_filter_delay_adjustment(self) -> float: ...
    @ao_filter_delay_adjustment.setter
    def ao_filter_delay_adjustment(self, val: float) -> None: ...
    @ao_filter_delay_adjustment.deleter
    def ao_filter_delay_adjustment(self) -> None: ...
    @property
    def ao_filter_delay_units(self) -> DigitalWidthUnits: ...
    @ao_filter_delay_units.setter
    def ao_filter_delay_units(self, val: DigitalWidthUnits) -> None: ...
    @ao_filter_delay_units.deleter
    def ao_filter_delay_units(self) -> None: ...
    @property
    def ao_func_gen_amplitude(self) -> float: ...
    @ao_func_gen_amplitude.setter
    def ao_func_gen_amplitude(self, val: float) -> None: ...
    @ao_func_gen_amplitude.deleter
    def ao_func_gen_amplitude(self) -> None: ...
    @property
    def ao_func_gen_fm_deviation(self) -> float: ...
    @ao_func_gen_fm_deviation.setter
    def ao_func_gen_fm_deviation(self, val: float) -> None: ...
    @ao_func_gen_fm_deviation.deleter
    def ao_func_gen_fm_deviation(self) -> None: ...
    @property
    def ao_func_gen_freq(self) -> float: ...
    @ao_func_gen_freq.setter
    def ao_func_gen_freq(self, val: float) -> None: ...
    @ao_func_gen_freq.deleter
    def ao_func_gen_freq(self) -> None: ...
    @property
    def ao_func_gen_modulation_type(self) -> ModulationType: ...
    @ao_func_gen_modulation_type.setter
    def ao_func_gen_modulation_type(self, val: ModulationType) -> None: ...
    @ao_func_gen_modulation_type.deleter
    def ao_func_gen_modulation_type(self) -> None: ...
    @property
    def ao_func_gen_offset(self) -> float: ...
    @ao_func_gen_offset.setter
    def ao_func_gen_offset(self, val: float) -> None: ...
    @ao_func_gen_offset.deleter
    def ao_func_gen_offset(self) -> None: ...
    @property
    def ao_func_gen_square_duty_cycle(self) -> float: ...
    @ao_func_gen_square_duty_cycle.setter
    def ao_func_gen_square_duty_cycle(self, val: float) -> None: ...
    @ao_func_gen_square_duty_cycle.deleter
    def ao_func_gen_square_duty_cycle(self) -> None: ...
    @property
    def ao_func_gen_start_phase(self) -> float: ...
    @ao_func_gen_start_phase.setter
    def ao_func_gen_start_phase(self, val: float) -> None: ...
    @ao_func_gen_start_phase.deleter
    def ao_func_gen_start_phase(self) -> None: ...
    @property
    def ao_func_gen_type(self) -> FuncGenType: ...
    @ao_func_gen_type.setter
    def ao_func_gen_type(self, val: FuncGenType) -> None: ...
    @ao_func_gen_type.deleter
    def ao_func_gen_type(self) -> None: ...
    @property
    def ao_gain(self) -> float: ...
    @ao_gain.setter
    def ao_gain(self, val: float) -> None: ...
    @ao_gain.deleter
    def ao_gain(self) -> None: ...
    @property
    def ao_idle_output_behavior(self) -> AOIdleOutputBehavior: ...
    @ao_idle_output_behavior.setter
    def ao_idle_output_behavior(self, val: AOIdleOutputBehavior) -> None: ...
    @ao_idle_output_behavior.deleter
    def ao_idle_output_behavior(self) -> None: ...
    @property
    def ao_load_impedance(self) -> float: ...
    @ao_load_impedance.setter
    def ao_load_impedance(self, val: float) -> None: ...
    @ao_load_impedance.deleter
    def ao_load_impedance(self) -> None: ...
    @property
    def ao_max(self) -> float: ...
    @ao_max.setter
    def ao_max(self, val: float) -> None: ...
    @ao_max.deleter
    def ao_max(self) -> None: ...
    @property
    def ao_mem_map_enable(self) -> bool: ...
    @ao_mem_map_enable.setter
    def ao_mem_map_enable(self, val: bool) -> None: ...
    @ao_mem_map_enable.deleter
    def ao_mem_map_enable(self) -> None: ...
    @property
    def ao_min(self) -> float: ...
    @ao_min.setter
    def ao_min(self, val: float) -> None: ...
    @ao_min.deleter
    def ao_min(self) -> None: ...
    @property
    def ao_output_impedance(self) -> float: ...
    @ao_output_impedance.setter
    def ao_output_impedance(self, val: float) -> None: ...
    @ao_output_impedance.deleter
    def ao_output_impedance(self) -> None: ...
    @property
    def ao_output_type(self) -> UsageTypeAO: ...
    @property
    def ao_reglitch_enable(self) -> bool: ...
    @ao_reglitch_enable.setter
    def ao_reglitch_enable(self, val: bool) -> None: ...
    @ao_reglitch_enable.deleter
    def ao_reglitch_enable(self) -> None: ...
    @property
    def ao_resolution(self) -> float: ...
    @property
    def ao_resolution_units(self) -> ResolutionType: ...
    @ao_resolution_units.setter
    def ao_resolution_units(self, val: ResolutionType) -> None: ...
    @ao_resolution_units.deleter
    def ao_resolution_units(self) -> None: ...
    @property
    def ao_term_cfg(self) -> TerminalConfiguration: ...
    @ao_term_cfg.setter
    def ao_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ao_term_cfg.deleter
    def ao_term_cfg(self) -> None: ...
    @property
    def ao_usb_xfer_req_count(self) -> int: ...
    @ao_usb_xfer_req_count.setter
    def ao_usb_xfer_req_count(self, val: int) -> None: ...
    @ao_usb_xfer_req_count.deleter
    def ao_usb_xfer_req_count(self) -> None: ...
    @property
    def ao_usb_xfer_req_size(self) -> int: ...
    @ao_usb_xfer_req_size.setter
    def ao_usb_xfer_req_size(self, val: int) -> None: ...
    @ao_usb_xfer_req_size.deleter
    def ao_usb_xfer_req_size(self) -> None: ...
    @property
    def ao_use_only_on_brd_mem(self) -> bool: ...
    @ao_use_only_on_brd_mem.setter
    def ao_use_only_on_brd_mem(self, val: bool) -> None: ...
    @ao_use_only_on_brd_mem.deleter
    def ao_use_only_on_brd_mem(self) -> None: ...
    @property
    def ao_voltage_current_limit(self) -> float: ...
    @ao_voltage_current_limit.setter
    def ao_voltage_current_limit(self, val: float) -> None: ...
    @ao_voltage_current_limit.deleter
    def ao_voltage_current_limit(self) -> None: ...
    @property
    def ao_voltage_units(self) -> VoltageUnits: ...
    @ao_voltage_units.setter
    def ao_voltage_units(self, val: VoltageUnits) -> None: ...
    @ao_voltage_units.deleter
    def ao_voltage_units(self) -> None: ...
