from ...task.channels._channel import Channel
from ...constants import (
    AngleUnits,
    AngularVelocityUnits,
    CountDirection,
    CounterFrequencyMethod,
    DataTransferActiveTransferMode,
    DigitalWidthUnits,
    Edge,
    EncoderType,
    EncoderZIndexPhase,
    FilterResponse,
    FrequencyUnits,
    GpsSignalType,
    InputDataTransferCondition,
    LengthUnits,
    Level,
    LogicLvlBehavior,
    SampClkOverrunBehavior,
    TerminalConfiguration,
    TimeUnits,
    UsageTypeCI,
    VelocityUnits,
)
from ...scale import Scale

class CIChannel(Channel):
    def __repr__(self) -> str: ...
    @property
    def ci_ang_encoder_initial_angle(self) -> float: ...
    @ci_ang_encoder_initial_angle.setter
    def ci_ang_encoder_initial_angle(self, val: float) -> None: ...
    @ci_ang_encoder_initial_angle.deleter
    def ci_ang_encoder_initial_angle(self) -> None: ...
    @property
    def ci_ang_encoder_pulses_per_rev(self) -> int: ...
    @ci_ang_encoder_pulses_per_rev.setter
    def ci_ang_encoder_pulses_per_rev(self, val: int) -> None: ...
    @ci_ang_encoder_pulses_per_rev.deleter
    def ci_ang_encoder_pulses_per_rev(self) -> None: ...
    @property
    def ci_ang_encoder_units(self) -> AngleUnits: ...
    @ci_ang_encoder_units.setter
    def ci_ang_encoder_units(self, val: AngleUnits) -> None: ...
    @ci_ang_encoder_units.deleter
    def ci_ang_encoder_units(self) -> None: ...
    @property
    def ci_count(self) -> int: ...
    @property
    def ci_count_edges_active_edge(selfint) -> Edge: ...
    @ci_count_edges_active_edge.setter
    def ci_count_edges_active_edge(self, val: Edge) -> None: ...
    @ci_count_edges_active_edge.deleter
    def ci_count_edges_active_edge(self) -> None: ...
    @property
    def ci_count_edges_count_dir_dig_fltr_enable(self) -> bool: ...
    @ci_count_edges_count_dir_dig_fltr_enable.setter
    def ci_count_edges_count_dir_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_count_edges_count_dir_dig_fltr_enable.deleter
    def ci_count_edges_count_dir_dig_fltr_enable(self) -> None: ...
    @property
    def ci_count_edges_count_dir_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_count_edges_count_dir_dig_fltr_min_pulse_width.setter
    def ci_count_edges_count_dir_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_count_edges_count_dir_dig_fltr_min_pulse_width.deleter
    def ci_count_edges_count_dir_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_count_edges_count_dir_dig_fltr_timebase_rate(self) -> float: ...
    @ci_count_edges_count_dir_dig_fltr_timebase_rate.setter
    def ci_count_edges_count_dir_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_count_edges_count_dir_dig_fltr_timebase_rate.deleter
    def ci_count_edges_count_dir_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_count_edges_count_dir_dig_fltr_timebase_src(self) -> str: ...
    @ci_count_edges_count_dir_dig_fltr_timebase_src.setter
    def ci_count_edges_count_dir_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_count_edges_count_dir_dig_fltr_timebase_src.deleter
    def ci_count_edges_count_dir_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_count_edges_count_dir_dig_sync_enable(self) -> bool: ...
    @ci_count_edges_count_dir_dig_sync_enable.setter
    def ci_count_edges_count_dir_dig_sync_enable(self, val: bool) -> None: ...
    @ci_count_edges_count_dir_dig_sync_enable.deleter
    def ci_count_edges_count_dir_dig_sync_enable(self) -> None: ...
    @property
    def ci_count_edges_count_dir_hyst(self) -> float: ...
    @ci_count_edges_count_dir_hyst.setter
    def ci_count_edges_count_dir_hyst(self, val: float) -> None: ...
    @ci_count_edges_count_dir_hyst.deleter
    def ci_count_edges_count_dir_hyst(self) -> None: ...
    @property
    def ci_count_edges_count_dir_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_count_edges_count_dir_logic_lvl_behavior.setter
    def ci_count_edges_count_dir_logic_lvl_behavior(
        self, val: LogicLvlBehavior
    ) -> None: ...
    @ci_count_edges_count_dir_logic_lvl_behavior.deleter
    def ci_count_edges_count_dir_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_count_edges_count_dir_term_cfg(self) -> TerminalConfiguration: ...
    @ci_count_edges_count_dir_term_cfg.setter
    def ci_count_edges_count_dir_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_count_edges_count_dir_term_cfg.deleter
    def ci_count_edges_count_dir_term_cfg(self) -> None: ...
    @property
    def ci_count_edges_count_dir_thresh_voltage(self) -> float: ...
    @ci_count_edges_count_dir_thresh_voltage.setter
    def ci_count_edges_count_dir_thresh_voltage(self, val: float) -> None: ...
    @ci_count_edges_count_dir_thresh_voltage.deleter
    def ci_count_edges_count_dir_thresh_voltage(self) -> None: ...
    @property
    def ci_count_edges_count_reset_active_edge(self) -> Edge: ...
    @ci_count_edges_count_reset_active_edge.setter
    def ci_count_edges_count_reset_active_edge(self, val: Edge) -> None: ...
    @ci_count_edges_count_reset_active_edge.deleter
    def ci_count_edges_count_reset_active_edge(self) -> None: ...
    @property
    def ci_count_edges_count_reset_dig_fltr_enable(self) -> bool: ...
    @ci_count_edges_count_reset_dig_fltr_enable.setter
    def ci_count_edges_count_reset_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_count_edges_count_reset_dig_fltr_enable.deleter
    def ci_count_edges_count_reset_dig_fltr_enable(self) -> None: ...
    @property
    def ci_count_edges_count_reset_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_count_edges_count_reset_dig_fltr_min_pulse_width.setter
    def ci_count_edges_count_reset_dig_fltr_min_pulse_width(
        self, val: float
    ) -> None: ...
    @ci_count_edges_count_reset_dig_fltr_min_pulse_width.deleter
    def ci_count_edges_count_reset_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_count_edges_count_reset_dig_fltr_timebase_rate(self) -> float: ...
    @ci_count_edges_count_reset_dig_fltr_timebase_rate.setter
    def ci_count_edges_count_reset_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_count_edges_count_reset_dig_fltr_timebase_rate.deleter
    def ci_count_edges_count_reset_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_count_edges_count_reset_dig_fltr_timebase_src(self) -> str: ...
    @ci_count_edges_count_reset_dig_fltr_timebase_src.setter
    def ci_count_edges_count_reset_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_count_edges_count_reset_dig_fltr_timebase_src.deleter
    def ci_count_edges_count_reset_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_count_edges_count_reset_dig_sync_enable(self) -> bool: ...
    @ci_count_edges_count_reset_dig_sync_enable.setter
    def ci_count_edges_count_reset_dig_sync_enable(self, val: bool) -> None: ...
    @ci_count_edges_count_reset_dig_sync_enable.deleter
    def ci_count_edges_count_reset_dig_sync_enable(self) -> None: ...
    @property
    def ci_count_edges_count_reset_enable(self) -> bool: ...
    @ci_count_edges_count_reset_enable.setter
    def ci_count_edges_count_reset_enable(self, val: bool) -> None: ...
    @ci_count_edges_count_reset_enable.deleter
    def ci_count_edges_count_reset_enable(self) -> None: ...
    @property
    def ci_count_edges_count_reset_hyst(self) -> float: ...
    @ci_count_edges_count_reset_hyst.setter
    def ci_count_edges_count_reset_hyst(self, val: float) -> None: ...
    @ci_count_edges_count_reset_hyst.deleter
    def ci_count_edges_count_reset_hyst(self) -> None: ...
    @property
    def ci_count_edges_count_reset_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_count_edges_count_reset_logic_lvl_behavior.setter
    def ci_count_edges_count_reset_logic_lvl_behavior(
        self, val: LogicLvlBehavior
    ) -> None: ...
    @ci_count_edges_count_reset_logic_lvl_behavior.deleter
    def ci_count_edges_count_reset_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_count_edges_count_reset_reset_cnt(self) -> int: ...
    @ci_count_edges_count_reset_reset_cnt.setter
    def ci_count_edges_count_reset_reset_cnt(self, val: int) -> None: ...
    @ci_count_edges_count_reset_reset_cnt.deleter
    def ci_count_edges_count_reset_reset_cnt(self) -> None: ...
    @property
    def ci_count_edges_count_reset_term(self) -> str: ...
    @ci_count_edges_count_reset_term.setter
    def ci_count_edges_count_reset_term(self, val: str) -> None: ...
    @ci_count_edges_count_reset_term.deleter
    def ci_count_edges_count_reset_term(self) -> None: ...
    @property
    def ci_count_edges_count_reset_term_cfg(self) -> TerminalConfiguration: ...
    @ci_count_edges_count_reset_term_cfg.setter
    def ci_count_edges_count_reset_term_cfg(
        self, val: TerminalConfiguration
    ) -> None: ...
    @ci_count_edges_count_reset_term_cfg.deleter
    def ci_count_edges_count_reset_term_cfg(self) -> None: ...
    @property
    def ci_count_edges_count_reset_thresh_voltage(self) -> float: ...
    @ci_count_edges_count_reset_thresh_voltage.setter
    def ci_count_edges_count_reset_thresh_voltage(self, val: float) -> None: ...
    @ci_count_edges_count_reset_thresh_voltage.deleter
    def ci_count_edges_count_reset_thresh_voltage(self) -> None: ...
    @property
    def ci_count_edges_dig_fltr_enable(self) -> bool: ...
    @ci_count_edges_dig_fltr_enable.setter
    def ci_count_edges_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_count_edges_dig_fltr_enable.deleter
    def ci_count_edges_dig_fltr_enable(self) -> None: ...
    @property
    def ci_count_edges_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_count_edges_dig_fltr_min_pulse_width.setter
    def ci_count_edges_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_count_edges_dig_fltr_min_pulse_width.deleter
    def ci_count_edges_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_count_edges_dig_fltr_timebase_rate(self) -> float: ...
    @ci_count_edges_dig_fltr_timebase_rate.setter
    def ci_count_edges_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_count_edges_dig_fltr_timebase_rate.deleter
    def ci_count_edges_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_count_edges_dig_fltr_timebase_src(self) -> str: ...
    @ci_count_edges_dig_fltr_timebase_src.setter
    def ci_count_edges_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_count_edges_dig_fltr_timebase_src.deleter
    def ci_count_edges_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_count_edges_dig_sync_enable(self) -> bool: ...
    @ci_count_edges_dig_sync_enable.setter
    def ci_count_edges_dig_sync_enable(self, val: bool) -> None: ...
    @ci_count_edges_dig_sync_enable.deleter
    def ci_count_edges_dig_sync_enable(self) -> None: ...
    @property
    def ci_count_edges_dir(self) -> CountDirection: ...
    @ci_count_edges_dir.setter
    def ci_count_edges_dir(self, val: CountDirection) -> None: ...
    @ci_count_edges_dir.deleter
    def ci_count_edges_dir(self) -> None: ...
    @property
    def ci_count_edges_dir_term(self) -> str: ...
    @ci_count_edges_dir_term.setter
    def ci_count_edges_dir_term(self, val: str) -> None: ...
    @ci_count_edges_dir_term.deleter
    def ci_count_edges_dir_term(self) -> None: ...
    @property
    def ci_count_edges_gate_dig_fltr_enable(self) -> bool: ...
    @ci_count_edges_gate_dig_fltr_enable.setter
    def ci_count_edges_gate_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_count_edges_gate_dig_fltr_enable.deleter
    def ci_count_edges_gate_dig_fltr_enable(self) -> None: ...
    @property
    def ci_count_edges_gate_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_count_edges_gate_dig_fltr_min_pulse_width.setter
    def ci_count_edges_gate_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_count_edges_gate_dig_fltr_min_pulse_width.deleter
    def ci_count_edges_gate_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_count_edges_gate_dig_fltr_timebase_rate(self) -> float: ...
    @ci_count_edges_gate_dig_fltr_timebase_rate.setter
    def ci_count_edges_gate_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_count_edges_gate_dig_fltr_timebase_rate.deleter
    def ci_count_edges_gate_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_count_edges_gate_dig_fltr_timebase_src(self) -> str: ...
    @ci_count_edges_gate_dig_fltr_timebase_src.setter
    def ci_count_edges_gate_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_count_edges_gate_dig_fltr_timebase_src.deleter
    def ci_count_edges_gate_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_count_edges_gate_enable(self) -> bool: ...
    @ci_count_edges_gate_enable.setter
    def ci_count_edges_gate_enable(self, val: bool) -> None: ...
    @ci_count_edges_gate_enable.deleter
    def ci_count_edges_gate_enable(self) -> None: ...
    @property
    def ci_count_edges_gate_hyst(self) -> float: ...
    @ci_count_edges_gate_hyst.setter
    def ci_count_edges_gate_hyst(self, val: float) -> None: ...
    @ci_count_edges_gate_hyst.deleter
    def ci_count_edges_gate_hyst(self) -> None: ...
    @property
    def ci_count_edges_gate_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_count_edges_gate_logic_lvl_behavior.setter
    def ci_count_edges_gate_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_count_edges_gate_logic_lvl_behavior.deleter
    def ci_count_edges_gate_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_count_edges_gate_term(self) -> str: ...
    @ci_count_edges_gate_term.setter
    def ci_count_edges_gate_term(self, val: str) -> None: ...
    @ci_count_edges_gate_term.deleter
    def ci_count_edges_gate_term(self) -> None: ...
    @property
    def ci_count_edges_gate_term_cfg(self) -> TerminalConfiguration: ...
    @ci_count_edges_gate_term_cfg.setter
    def ci_count_edges_gate_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_count_edges_gate_term_cfg.deleter
    def ci_count_edges_gate_term_cfg(self) -> None: ...
    @property
    def ci_count_edges_gate_thresh_voltage(self) -> float: ...
    @ci_count_edges_gate_thresh_voltage.setter
    def ci_count_edges_gate_thresh_voltage(self, val: float) -> None: ...
    @ci_count_edges_gate_thresh_voltage.deleter
    def ci_count_edges_gate_thresh_voltage(self) -> None: ...
    @property
    def ci_count_edges_gate_when(self) -> Level: ...
    @ci_count_edges_gate_when.setter
    def ci_count_edges_gate_when(self, val: Level) -> None: ...
    @ci_count_edges_gate_when.deleter
    def ci_count_edges_gate_when(self) -> None: ...
    @property
    def ci_count_edges_hyst(self) -> float: ...
    @ci_count_edges_hyst.setter
    def ci_count_edges_hyst(self, val: float) -> None: ...
    @ci_count_edges_hyst.deleter
    def ci_count_edges_hyst(self) -> None: ...
    @property
    def ci_count_edges_initial_cnt(self) -> int: ...
    @ci_count_edges_initial_cnt.setter
    def ci_count_edges_initial_cnt(self, val: int) -> None: ...
    @ci_count_edges_initial_cnt.deleter
    def ci_count_edges_initial_cnt(self) -> None: ...
    @property
    def ci_count_edges_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_count_edges_logic_lvl_behavior.setter
    def ci_count_edges_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_count_edges_logic_lvl_behavior.deleter
    def ci_count_edges_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_count_edges_term(self) -> str: ...
    @ci_count_edges_term.setter
    def ci_count_edges_term(self, val: str) -> None: ...
    @ci_count_edges_term.deleter
    def ci_count_edges_term(self) -> None: ...
    @property
    def ci_count_edges_term_cfg(self) -> TerminalConfiguration: ...
    @ci_count_edges_term_cfg.setter
    def ci_count_edges_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_count_edges_term_cfg.deleter
    def ci_count_edges_term_cfg(self) -> None: ...
    @property
    def ci_count_edges_thresh_voltage(self) -> float: ...
    @ci_count_edges_thresh_voltage.setter
    def ci_count_edges_thresh_voltage(self, val: float) -> None: ...
    @ci_count_edges_thresh_voltage.deleter
    def ci_count_edges_thresh_voltage(self) -> None: ...
    @property
    def ci_ctr_timebase_active_edge(self) -> Edge: ...
    @ci_ctr_timebase_active_edge.setter
    def ci_ctr_timebase_active_edge(self, val: Edge) -> None: ...
    @ci_ctr_timebase_active_edge.deleter
    def ci_ctr_timebase_active_edge(self) -> None: ...
    @property
    def ci_ctr_timebase_dig_fltr_enable(self) -> bool: ...
    @ci_ctr_timebase_dig_fltr_enable.setter
    def ci_ctr_timebase_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_ctr_timebase_dig_fltr_enable.deleter
    def ci_ctr_timebase_dig_fltr_enable(self) -> None: ...
    @property
    def ci_ctr_timebase_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_ctr_timebase_dig_fltr_min_pulse_width.setter
    def ci_ctr_timebase_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_ctr_timebase_dig_fltr_min_pulse_width.deleter
    def ci_ctr_timebase_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_ctr_timebase_dig_fltr_timebase_rate(self) -> float: ...
    @ci_ctr_timebase_dig_fltr_timebase_rate.setter
    def ci_ctr_timebase_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_ctr_timebase_dig_fltr_timebase_rate.deleter
    def ci_ctr_timebase_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_ctr_timebase_dig_fltr_timebase_src(self) -> str: ...
    @ci_ctr_timebase_dig_fltr_timebase_src.setter
    def ci_ctr_timebase_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_ctr_timebase_dig_fltr_timebase_src.deleter
    def ci_ctr_timebase_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_ctr_timebase_dig_sync_enable(self) -> bool: ...
    @ci_ctr_timebase_dig_sync_enable.setter
    def ci_ctr_timebase_dig_sync_enable(self, val: bool) -> None: ...
    @ci_ctr_timebase_dig_sync_enable.deleter
    def ci_ctr_timebase_dig_sync_enable(self) -> None: ...
    @property
    def ci_ctr_timebase_master_timebase_div(self) -> int: ...
    @ci_ctr_timebase_master_timebase_div.setter
    def ci_ctr_timebase_master_timebase_div(self, val: int) -> None: ...
    @ci_ctr_timebase_master_timebase_div.deleter
    def ci_ctr_timebase_master_timebase_div(self) -> None: ...
    @property
    def ci_ctr_timebase_rate(self) -> float: ...
    @ci_ctr_timebase_rate.setter
    def ci_ctr_timebase_rate(self, val: float) -> None: ...
    @ci_ctr_timebase_rate.deleter
    def ci_ctr_timebase_rate(self) -> None: ...
    @property
    def ci_ctr_timebase_src(self) -> str: ...
    @ci_ctr_timebase_src.setter
    def ci_ctr_timebase_src(self, val: str) -> None: ...
    @ci_ctr_timebase_src.deleter
    def ci_ctr_timebase_src(self) -> None: ...
    @property
    def ci_custom_scale(self) -> Scale: ...
    @ci_custom_scale.setter
    def ci_custom_scale(self, val: Scale) -> None: ...
    @ci_custom_scale.deleter
    def ci_custom_scale(self) -> None: ...
    @property
    def ci_data_xfer_mech(self) -> DataTransferActiveTransferMode: ...
    @ci_data_xfer_mech.setter
    def ci_data_xfer_mech(self, val: DataTransferActiveTransferMode) -> None: ...
    @ci_data_xfer_mech.deleter
    def ci_data_xfer_mech(self) -> None: ...
    @property
    def ci_data_xfer_req_cond(self) -> InputDataTransferCondition: ...
    @ci_data_xfer_req_cond.setter
    def ci_data_xfer_req_cond(self, val: InputDataTransferCondition) -> None: ...
    @ci_data_xfer_req_cond.deleter
    def ci_data_xfer_req_cond(self) -> None: ...
    @property
    def ci_dup_count_prevention(self) -> bool: ...
    @ci_dup_count_prevention.setter
    def ci_dup_count_prevention(self, val: bool) -> None: ...
    @ci_dup_count_prevention.deleter
    def ci_dup_count_prevention(self) -> None: ...
    @property
    def ci_duty_cycle_dig_fltr_enable(self) -> bool: ...
    @ci_duty_cycle_dig_fltr_enable.setter
    def ci_duty_cycle_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_duty_cycle_dig_fltr_enable.deleter
    def ci_duty_cycle_dig_fltr_enable(self) -> None: ...
    @property
    def ci_duty_cycle_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_duty_cycle_dig_fltr_min_pulse_width.setter
    def ci_duty_cycle_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_duty_cycle_dig_fltr_min_pulse_width.deleter
    def ci_duty_cycle_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_duty_cycle_dig_fltr_timebase_rate(self) -> float: ...
    @ci_duty_cycle_dig_fltr_timebase_rate.setter
    def ci_duty_cycle_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_duty_cycle_dig_fltr_timebase_rate.deleter
    def ci_duty_cycle_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_duty_cycle_dig_fltr_timebase_src(self) -> str: ...
    @ci_duty_cycle_dig_fltr_timebase_src.setter
    def ci_duty_cycle_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_duty_cycle_dig_fltr_timebase_src.deleter
    def ci_duty_cycle_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_duty_cycle_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_duty_cycle_logic_lvl_behavior.setter
    def ci_duty_cycle_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_duty_cycle_logic_lvl_behavior.deleter
    def ci_duty_cycle_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_duty_cycle_starting_edge(self) -> Edge: ...
    @ci_duty_cycle_starting_edge.setter
    def ci_duty_cycle_starting_edge(self, val: Edge) -> None: ...
    @ci_duty_cycle_starting_edge.deleter
    def ci_duty_cycle_starting_edge(self) -> None: ...
    @property
    def ci_duty_cycle_term(self) -> str: ...
    @ci_duty_cycle_term.setter
    def ci_duty_cycle_term(self, val: str) -> None: ...
    @ci_duty_cycle_term.deleter
    def ci_duty_cycle_term(self) -> None: ...
    @property
    def ci_duty_cycle_term_cfg(self) -> TerminalConfiguration: ...
    @ci_duty_cycle_term_cfg.setter
    def ci_duty_cycle_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_duty_cycle_term_cfg.deleter
    def ci_duty_cycle_term_cfg(self) -> None: ...
    @property
    def ci_encoder_a_input_dig_fltr_enable(self) -> bool: ...
    @ci_encoder_a_input_dig_fltr_enable.setter
    def ci_encoder_a_input_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_encoder_a_input_dig_fltr_enable.deleter
    def ci_encoder_a_input_dig_fltr_enable(self) -> None: ...
    @property
    def ci_encoder_a_input_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_encoder_a_input_dig_fltr_min_pulse_width.setter
    def ci_encoder_a_input_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_encoder_a_input_dig_fltr_min_pulse_width.deleter
    def ci_encoder_a_input_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_encoder_a_input_dig_fltr_timebase_rate(self) -> float: ...
    @ci_encoder_a_input_dig_fltr_timebase_rate.setter
    def ci_encoder_a_input_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_encoder_a_input_dig_fltr_timebase_rate.deleter
    def ci_encoder_a_input_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_encoder_a_input_dig_fltr_timebase_src(self) -> str: ...
    @ci_encoder_a_input_dig_fltr_timebase_src.setter
    def ci_encoder_a_input_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_encoder_a_input_dig_fltr_timebase_src.deleter
    def ci_encoder_a_input_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_encoder_a_input_dig_sync_enable(self) -> bool: ...
    @ci_encoder_a_input_dig_sync_enable.setter
    def ci_encoder_a_input_dig_sync_enable(self, val: bool) -> None: ...
    @ci_encoder_a_input_dig_sync_enable.deleter
    def ci_encoder_a_input_dig_sync_enable(self) -> None: ...
    @property
    def ci_encoder_a_input_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_encoder_a_input_logic_lvl_behavior.setter
    def ci_encoder_a_input_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_encoder_a_input_logic_lvl_behavior.deleter
    def ci_encoder_a_input_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_encoder_a_input_term(self) -> str: ...
    @ci_encoder_a_input_term.setter
    def ci_encoder_a_input_term(self, val: str) -> None: ...
    @ci_encoder_a_input_term.deleter
    def ci_encoder_a_input_term(self) -> None: ...
    @property
    def ci_encoder_a_input_term_cfg(self) -> TerminalConfiguration: ...
    @ci_encoder_a_input_term_cfg.setter
    def ci_encoder_a_input_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_encoder_a_input_term_cfg.deleter
    def ci_encoder_a_input_term_cfg(self) -> None: ...
    @property
    def ci_encoder_b_input_dig_fltr_enable(self) -> bool: ...
    @ci_encoder_b_input_dig_fltr_enable.setter
    def ci_encoder_b_input_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_encoder_b_input_dig_fltr_enable.deleter
    def ci_encoder_b_input_dig_fltr_enable(self) -> None: ...
    @property
    def ci_encoder_b_input_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_encoder_b_input_dig_fltr_min_pulse_width.setter
    def ci_encoder_b_input_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_encoder_b_input_dig_fltr_min_pulse_width.deleter
    def ci_encoder_b_input_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_encoder_b_input_dig_fltr_timebase_rate(self) -> float: ...
    @ci_encoder_b_input_dig_fltr_timebase_rate.setter
    def ci_encoder_b_input_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_encoder_b_input_dig_fltr_timebase_rate.deleter
    def ci_encoder_b_input_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_encoder_b_input_dig_fltr_timebase_src(self) -> str: ...
    @ci_encoder_b_input_dig_fltr_timebase_src.setter
    def ci_encoder_b_input_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_encoder_b_input_dig_fltr_timebase_src.deleter
    def ci_encoder_b_input_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_encoder_b_input_dig_sync_enable(self) -> bool: ...
    @ci_encoder_b_input_dig_sync_enable.setter
    def ci_encoder_b_input_dig_sync_enable(self, val: bool) -> None: ...
    @ci_encoder_b_input_dig_sync_enable.deleter
    def ci_encoder_b_input_dig_sync_enable(self) -> None: ...
    @property
    def ci_encoder_b_input_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_encoder_b_input_logic_lvl_behavior.setter
    def ci_encoder_b_input_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_encoder_b_input_logic_lvl_behavior.deleter
    def ci_encoder_b_input_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_encoder_b_input_term(self) -> str: ...
    @ci_encoder_b_input_term.setter
    def ci_encoder_b_input_term(self, val: str) -> None: ...
    @ci_encoder_b_input_term.deleter
    def ci_encoder_b_input_term(self) -> None: ...
    @property
    def ci_encoder_b_input_term_cfg(self) -> TerminalConfiguration: ...
    @ci_encoder_b_input_term_cfg.setter
    def ci_encoder_b_input_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_encoder_b_input_term_cfg.deleter
    def ci_encoder_b_input_term_cfg(self) -> None: ...
    @property
    def ci_encoder_decoding_type(self) -> EncoderType: ...
    @ci_encoder_decoding_type.setter
    def ci_encoder_decoding_type(self, val: EncoderType) -> None: ...
    @ci_encoder_decoding_type.deleter
    def ci_encoder_decoding_type(self) -> None: ...
    @property
    def ci_encoder_z_index_enable(self) -> bool: ...
    @ci_encoder_z_index_enable.setter
    def ci_encoder_z_index_enable(self, val: bool) -> None: ...
    @ci_encoder_z_index_enable.deleter
    def ci_encoder_z_index_enable(self) -> None: ...
    @property
    def ci_encoder_z_index_phase(self) -> EncoderZIndexPhase: ...
    @ci_encoder_z_index_phase.setter
    def ci_encoder_z_index_phase(self, val: EncoderZIndexPhase) -> None: ...
    @ci_encoder_z_index_phase.deleter
    def ci_encoder_z_index_phase(self) -> None: ...
    @property
    def ci_encoder_z_index_val(self) -> float: ...
    @ci_encoder_z_index_val.setter
    def ci_encoder_z_index_val(self, val: float) -> None: ...
    @ci_encoder_z_index_val.deleter
    def ci_encoder_z_index_val(self) -> None: ...
    @property
    def ci_encoder_z_input_dig_fltr_enable(self) -> bool: ...
    @ci_encoder_z_input_dig_fltr_enable.setter
    def ci_encoder_z_input_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_encoder_z_input_dig_fltr_enable.deleter
    def ci_encoder_z_input_dig_fltr_enable(self) -> None: ...
    @property
    def ci_encoder_z_input_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_encoder_z_input_dig_fltr_min_pulse_width.setter
    def ci_encoder_z_input_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_encoder_z_input_dig_fltr_min_pulse_width.deleter
    def ci_encoder_z_input_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_encoder_z_input_dig_fltr_timebase_rate(self) -> float: ...
    @ci_encoder_z_input_dig_fltr_timebase_rate.setter
    def ci_encoder_z_input_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_encoder_z_input_dig_fltr_timebase_rate.deleter
    def ci_encoder_z_input_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_encoder_z_input_dig_fltr_timebase_src(self) -> str: ...
    @ci_encoder_z_input_dig_fltr_timebase_src.setter
    def ci_encoder_z_input_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_encoder_z_input_dig_fltr_timebase_src.deleter
    def ci_encoder_z_input_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_encoder_z_input_dig_sync_enable(self) -> bool: ...
    @ci_encoder_z_input_dig_sync_enable.setter
    def ci_encoder_z_input_dig_sync_enable(self, val: bool) -> None: ...
    @ci_encoder_z_input_dig_sync_enable.deleter
    def ci_encoder_z_input_dig_sync_enable(self) -> None: ...
    @property
    def ci_encoder_z_input_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_encoder_z_input_logic_lvl_behavior.setter
    def ci_encoder_z_input_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_encoder_z_input_logic_lvl_behavior.deleter
    def ci_encoder_z_input_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_encoder_z_input_term(self) -> str: ...
    @ci_encoder_z_input_term.setter
    def ci_encoder_z_input_term(self, val: str) -> None: ...
    @ci_encoder_z_input_term.deleter
    def ci_encoder_z_input_term(self) -> None: ...
    @property
    def ci_encoder_z_input_term_cfg(self) -> TerminalConfiguration: ...
    @ci_encoder_z_input_term_cfg.setter
    def ci_encoder_z_input_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_encoder_z_input_term_cfg.deleter
    def ci_encoder_z_input_term_cfg(self) -> None: ...
    @property
    def ci_filter_delay(self) -> float: ...
    @property
    def ci_filter_delay_units(selffloat) -> DigitalWidthUnits: ...
    @ci_filter_delay_units.setter
    def ci_filter_delay_units(self, val: DigitalWidthUnits) -> None: ...
    @ci_filter_delay_units.deleter
    def ci_filter_delay_units(self) -> None: ...
    @property
    def ci_filter_enable(self) -> bool: ...
    @ci_filter_enable.setter
    def ci_filter_enable(self, val: bool) -> None: ...
    @ci_filter_enable.deleter
    def ci_filter_enable(self) -> None: ...
    @property
    def ci_filter_freq(self) -> float: ...
    @ci_filter_freq.setter
    def ci_filter_freq(self, val: float) -> None: ...
    @ci_filter_freq.deleter
    def ci_filter_freq(self) -> None: ...
    @property
    def ci_filter_order(self) -> int: ...
    @ci_filter_order.setter
    def ci_filter_order(self, val: int) -> None: ...
    @ci_filter_order.deleter
    def ci_filter_order(self) -> None: ...
    @property
    def ci_filter_response(self) -> FilterResponse: ...
    @ci_filter_response.setter
    def ci_filter_response(self, val: FilterResponse) -> None: ...
    @ci_filter_response.deleter
    def ci_filter_response(self) -> None: ...
    @property
    def ci_freq_dig_fltr_enable(self) -> bool: ...
    @ci_freq_dig_fltr_enable.setter
    def ci_freq_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_freq_dig_fltr_enable.deleter
    def ci_freq_dig_fltr_enable(self) -> None: ...
    @property
    def ci_freq_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_freq_dig_fltr_min_pulse_width.setter
    def ci_freq_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_freq_dig_fltr_min_pulse_width.deleter
    def ci_freq_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_freq_dig_fltr_timebase_rate(self) -> float: ...
    @ci_freq_dig_fltr_timebase_rate.setter
    def ci_freq_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_freq_dig_fltr_timebase_rate.deleter
    def ci_freq_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_freq_dig_fltr_timebase_src(self) -> str: ...
    @ci_freq_dig_fltr_timebase_src.setter
    def ci_freq_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_freq_dig_fltr_timebase_src.deleter
    def ci_freq_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_freq_dig_sync_enable(self) -> bool: ...
    @ci_freq_dig_sync_enable.setter
    def ci_freq_dig_sync_enable(self, val: bool) -> None: ...
    @ci_freq_dig_sync_enable.deleter
    def ci_freq_dig_sync_enable(self) -> None: ...
    @property
    def ci_freq_div(self) -> int: ...
    @ci_freq_div.setter
    def ci_freq_div(self, val: int) -> None: ...
    @ci_freq_div.deleter
    def ci_freq_div(self) -> None: ...
    @property
    def ci_freq_enable_averaging(self) -> bool: ...
    @ci_freq_enable_averaging.setter
    def ci_freq_enable_averaging(self, val: bool) -> None: ...
    @ci_freq_enable_averaging.deleter
    def ci_freq_enable_averaging(self) -> None: ...
    @property
    def ci_freq_hyst(self) -> float: ...
    @ci_freq_hyst.setter
    def ci_freq_hyst(self, val: float) -> None: ...
    @ci_freq_hyst.deleter
    def ci_freq_hyst(self) -> None: ...
    @property
    def ci_freq_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_freq_logic_lvl_behavior.setter
    def ci_freq_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_freq_logic_lvl_behavior.deleter
    def ci_freq_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_freq_meas_meth(self) -> CounterFrequencyMethod: ...
    @ci_freq_meas_meth.setter
    def ci_freq_meas_meth(self, val: CounterFrequencyMethod) -> None: ...
    @ci_freq_meas_meth.deleter
    def ci_freq_meas_meth(self) -> None: ...
    @property
    def ci_freq_meas_time(self) -> float: ...
    @ci_freq_meas_time.setter
    def ci_freq_meas_time(self, val: float) -> None: ...
    @ci_freq_meas_time.deleter
    def ci_freq_meas_time(self) -> None: ...
    @property
    def ci_freq_starting_edge(self) -> Edge: ...
    @ci_freq_starting_edge.setter
    def ci_freq_starting_edge(self, val: Edge) -> None: ...
    @ci_freq_starting_edge.deleter
    def ci_freq_starting_edge(self) -> None: ...
    @property
    def ci_freq_term(self) -> str: ...
    @ci_freq_term.setter
    def ci_freq_term(self, val: str) -> None: ...
    @ci_freq_term.deleter
    def ci_freq_term(self) -> None: ...
    @property
    def ci_freq_term_cfg(self) -> TerminalConfiguration: ...
    @ci_freq_term_cfg.setter
    def ci_freq_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_freq_term_cfg.deleter
    def ci_freq_term_cfg(self) -> None: ...
    @property
    def ci_freq_thresh_voltage(self) -> float: ...
    @ci_freq_thresh_voltage.setter
    def ci_freq_thresh_voltage(self, val: float) -> None: ...
    @ci_freq_thresh_voltage.deleter
    def ci_freq_thresh_voltage(self) -> None: ...
    @property
    def ci_freq_units(self) -> FrequencyUnits: ...
    @ci_freq_units.setter
    def ci_freq_units(self, val: FrequencyUnits) -> None: ...
    @ci_freq_units.deleter
    def ci_freq_units(self) -> None: ...
    @property
    def ci_gps_sync_method(self) -> GpsSignalType: ...
    @ci_gps_sync_method.setter
    def ci_gps_sync_method(self, val: GpsSignalType) -> None: ...
    @ci_gps_sync_method.deleter
    def ci_gps_sync_method(self) -> None: ...
    @property
    def ci_gps_sync_src(self) -> str: ...
    @ci_gps_sync_src.setter
    def ci_gps_sync_src(self, val: str) -> None: ...
    @ci_gps_sync_src.deleter
    def ci_gps_sync_src(self) -> None: ...
    @property
    def ci_lin_encoder_dist_per_pulse(self) -> float: ...
    @ci_lin_encoder_dist_per_pulse.setter
    def ci_lin_encoder_dist_per_pulse(self, val: float) -> None: ...
    @ci_lin_encoder_dist_per_pulse.deleter
    def ci_lin_encoder_dist_per_pulse(self) -> None: ...
    @property
    def ci_lin_encoder_initial_pos(self) -> float: ...
    @ci_lin_encoder_initial_pos.setter
    def ci_lin_encoder_initial_pos(self, val: float) -> None: ...
    @ci_lin_encoder_initial_pos.deleter
    def ci_lin_encoder_initial_pos(self) -> None: ...
    @property
    def ci_lin_encoder_units(self) -> LengthUnits: ...
    @ci_lin_encoder_units.setter
    def ci_lin_encoder_units(self, val: LengthUnits) -> None: ...
    @ci_lin_encoder_units.deleter
    def ci_lin_encoder_units(self) -> None: ...
    @property
    def ci_max(self) -> float: ...
    @ci_max.setter
    def ci_max(self, val: float) -> None: ...
    @ci_max.deleter
    def ci_max(self) -> None: ...
    @property
    def ci_max_meas_period(self) -> float: ...
    @ci_max_meas_period.setter
    def ci_max_meas_period(self, val: float) -> None: ...
    @ci_max_meas_period.deleter
    def ci_max_meas_period(self) -> None: ...
    @property
    def ci_meas_type(self) -> UsageTypeCI: ...
    @property
    def ci_mem_map_enable(selfUsageTypeCI) -> bool: ...
    @ci_mem_map_enable.setter
    def ci_mem_map_enable(self, val: bool) -> None: ...
    @ci_mem_map_enable.deleter
    def ci_mem_map_enable(self) -> None: ...
    @property
    def ci_min(self) -> float: ...
    @ci_min.setter
    def ci_min(self, val: float) -> None: ...
    @ci_min.deleter
    def ci_min(self) -> None: ...
    @property
    def ci_num_possibly_invalid_samps(self) -> int: ...
    @property
    def ci_output_state(selfint) -> Level: ...
    @property
    def ci_period_dig_fltr_enable(self) -> bool: ...
    @ci_period_dig_fltr_enable.setter
    def ci_period_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_period_dig_fltr_enable.deleter
    def ci_period_dig_fltr_enable(self) -> None: ...
    @property
    def ci_period_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_period_dig_fltr_min_pulse_width.setter
    def ci_period_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_period_dig_fltr_min_pulse_width.deleter
    def ci_period_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_period_dig_fltr_timebase_rate(self) -> float: ...
    @ci_period_dig_fltr_timebase_rate.setter
    def ci_period_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_period_dig_fltr_timebase_rate.deleter
    def ci_period_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_period_dig_fltr_timebase_src(self) -> str: ...
    @ci_period_dig_fltr_timebase_src.setter
    def ci_period_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_period_dig_fltr_timebase_src.deleter
    def ci_period_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_period_dig_sync_enable(self) -> bool: ...
    @ci_period_dig_sync_enable.setter
    def ci_period_dig_sync_enable(self, val: bool) -> None: ...
    @ci_period_dig_sync_enable.deleter
    def ci_period_dig_sync_enable(self) -> None: ...
    @property
    def ci_period_div(self) -> int: ...
    @ci_period_div.setter
    def ci_period_div(self, val: int) -> None: ...
    @ci_period_div.deleter
    def ci_period_div(self) -> None: ...
    @property
    def ci_period_enable_averaging(self) -> bool: ...
    @ci_period_enable_averaging.setter
    def ci_period_enable_averaging(self, val: bool) -> None: ...
    @ci_period_enable_averaging.deleter
    def ci_period_enable_averaging(self) -> None: ...
    @property
    def ci_period_hyst(self) -> float: ...
    @ci_period_hyst.setter
    def ci_period_hyst(self, val: float) -> None: ...
    @ci_period_hyst.deleter
    def ci_period_hyst(self) -> None: ...
    @property
    def ci_period_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_period_logic_lvl_behavior.setter
    def ci_period_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_period_logic_lvl_behavior.deleter
    def ci_period_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_period_meas_meth(self) -> CounterFrequencyMethod: ...
    @ci_period_meas_meth.setter
    def ci_period_meas_meth(self, val: CounterFrequencyMethod) -> None: ...
    @ci_period_meas_meth.deleter
    def ci_period_meas_meth(self) -> None: ...
    @property
    def ci_period_meas_time(self) -> float: ...
    @ci_period_meas_time.setter
    def ci_period_meas_time(self, val: float) -> None: ...
    @ci_period_meas_time.deleter
    def ci_period_meas_time(self) -> None: ...
    @property
    def ci_period_starting_edge(self) -> Edge: ...
    @ci_period_starting_edge.setter
    def ci_period_starting_edge(self, val: Edge) -> None: ...
    @ci_period_starting_edge.deleter
    def ci_period_starting_edge(self) -> None: ...
    @property
    def ci_period_term(self) -> str: ...
    @ci_period_term.setter
    def ci_period_term(self, val: str) -> None: ...
    @ci_period_term.deleter
    def ci_period_term(self) -> None: ...
    @property
    def ci_period_term_cfg(self) -> TerminalConfiguration: ...
    @ci_period_term_cfg.setter
    def ci_period_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_period_term_cfg.deleter
    def ci_period_term_cfg(self) -> None: ...
    @property
    def ci_period_thresh_voltage(self) -> float: ...
    @ci_period_thresh_voltage.setter
    def ci_period_thresh_voltage(self, val: float) -> None: ...
    @ci_period_thresh_voltage.deleter
    def ci_period_thresh_voltage(self) -> None: ...
    @property
    def ci_period_units(self) -> TimeUnits: ...
    @ci_period_units.setter
    def ci_period_units(self, val: TimeUnits) -> None: ...
    @ci_period_units.deleter
    def ci_period_units(self) -> None: ...
    @property
    def ci_prescaler(self) -> int: ...
    @ci_prescaler.setter
    def ci_prescaler(self, val: int) -> None: ...
    @ci_prescaler.deleter
    def ci_prescaler(self) -> None: ...
    @property
    def ci_pulse_freq_dig_fltr_enable(self) -> bool: ...
    @ci_pulse_freq_dig_fltr_enable.setter
    def ci_pulse_freq_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_pulse_freq_dig_fltr_enable.deleter
    def ci_pulse_freq_dig_fltr_enable(self) -> None: ...
    @property
    def ci_pulse_freq_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_pulse_freq_dig_fltr_min_pulse_width.setter
    def ci_pulse_freq_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_pulse_freq_dig_fltr_min_pulse_width.deleter
    def ci_pulse_freq_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_pulse_freq_dig_fltr_timebase_rate(self) -> float: ...
    @ci_pulse_freq_dig_fltr_timebase_rate.setter
    def ci_pulse_freq_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_pulse_freq_dig_fltr_timebase_rate.deleter
    def ci_pulse_freq_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_pulse_freq_dig_fltr_timebase_src(self) -> str: ...
    @ci_pulse_freq_dig_fltr_timebase_src.setter
    def ci_pulse_freq_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_pulse_freq_dig_fltr_timebase_src.deleter
    def ci_pulse_freq_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_pulse_freq_dig_sync_enable(self) -> bool: ...
    @ci_pulse_freq_dig_sync_enable.setter
    def ci_pulse_freq_dig_sync_enable(self, val: bool) -> None: ...
    @ci_pulse_freq_dig_sync_enable.deleter
    def ci_pulse_freq_dig_sync_enable(self) -> None: ...
    @property
    def ci_pulse_freq_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_pulse_freq_logic_lvl_behavior.setter
    def ci_pulse_freq_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_pulse_freq_logic_lvl_behavior.deleter
    def ci_pulse_freq_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_pulse_freq_starting_edge(self) -> Edge: ...
    @ci_pulse_freq_starting_edge.setter
    def ci_pulse_freq_starting_edge(self, val: Edge) -> None: ...
    @ci_pulse_freq_starting_edge.deleter
    def ci_pulse_freq_starting_edge(self) -> None: ...
    @property
    def ci_pulse_freq_term(self) -> str: ...
    @ci_pulse_freq_term.setter
    def ci_pulse_freq_term(self, val: str) -> None: ...
    @ci_pulse_freq_term.deleter
    def ci_pulse_freq_term(self) -> None: ...
    @property
    def ci_pulse_freq_term_cfg(self) -> TerminalConfiguration: ...
    @ci_pulse_freq_term_cfg.setter
    def ci_pulse_freq_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_pulse_freq_term_cfg.deleter
    def ci_pulse_freq_term_cfg(self) -> None: ...
    @property
    def ci_pulse_freq_units(self) -> FrequencyUnits: ...
    @ci_pulse_freq_units.setter
    def ci_pulse_freq_units(self, val: FrequencyUnits) -> None: ...
    @ci_pulse_freq_units.deleter
    def ci_pulse_freq_units(self) -> None: ...
    @property
    def ci_pulse_ticks_dig_fltr_enable(self) -> bool: ...
    @ci_pulse_ticks_dig_fltr_enable.setter
    def ci_pulse_ticks_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_pulse_ticks_dig_fltr_enable.deleter
    def ci_pulse_ticks_dig_fltr_enable(self) -> None: ...
    @property
    def ci_pulse_ticks_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_pulse_ticks_dig_fltr_min_pulse_width.setter
    def ci_pulse_ticks_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_pulse_ticks_dig_fltr_min_pulse_width.deleter
    def ci_pulse_ticks_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_pulse_ticks_dig_fltr_timebase_rate(self) -> float: ...
    @ci_pulse_ticks_dig_fltr_timebase_rate.setter
    def ci_pulse_ticks_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_pulse_ticks_dig_fltr_timebase_rate.deleter
    def ci_pulse_ticks_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_pulse_ticks_dig_fltr_timebase_src(self) -> str: ...
    @ci_pulse_ticks_dig_fltr_timebase_src.setter
    def ci_pulse_ticks_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_pulse_ticks_dig_fltr_timebase_src.deleter
    def ci_pulse_ticks_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_pulse_ticks_dig_sync_enable(self) -> bool: ...
    @ci_pulse_ticks_dig_sync_enable.setter
    def ci_pulse_ticks_dig_sync_enable(self, val: bool) -> None: ...
    @ci_pulse_ticks_dig_sync_enable.deleter
    def ci_pulse_ticks_dig_sync_enable(self) -> None: ...
    @property
    def ci_pulse_ticks_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_pulse_ticks_logic_lvl_behavior.setter
    def ci_pulse_ticks_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_pulse_ticks_logic_lvl_behavior.deleter
    def ci_pulse_ticks_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_pulse_ticks_starting_edge(self) -> Edge: ...
    @ci_pulse_ticks_starting_edge.setter
    def ci_pulse_ticks_starting_edge(self, val: Edge) -> None: ...
    @ci_pulse_ticks_starting_edge.deleter
    def ci_pulse_ticks_starting_edge(self) -> None: ...
    @property
    def ci_pulse_ticks_term(self) -> str: ...
    @ci_pulse_ticks_term.setter
    def ci_pulse_ticks_term(self, val: str) -> None: ...
    @ci_pulse_ticks_term.deleter
    def ci_pulse_ticks_term(self) -> None: ...
    @property
    def ci_pulse_ticks_term_cfg(self) -> TerminalConfiguration: ...
    @ci_pulse_ticks_term_cfg.setter
    def ci_pulse_ticks_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_pulse_ticks_term_cfg.deleter
    def ci_pulse_ticks_term_cfg(self) -> None: ...
    @property
    def ci_pulse_time_dig_fltr_enable(self) -> bool: ...
    @ci_pulse_time_dig_fltr_enable.setter
    def ci_pulse_time_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_pulse_time_dig_fltr_enable.deleter
    def ci_pulse_time_dig_fltr_enable(self) -> None: ...
    @property
    def ci_pulse_time_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_pulse_time_dig_fltr_min_pulse_width.setter
    def ci_pulse_time_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_pulse_time_dig_fltr_min_pulse_width.deleter
    def ci_pulse_time_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_pulse_time_dig_fltr_timebase_rate(self) -> float: ...
    @ci_pulse_time_dig_fltr_timebase_rate.setter
    def ci_pulse_time_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_pulse_time_dig_fltr_timebase_rate.deleter
    def ci_pulse_time_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_pulse_time_dig_fltr_timebase_src(self) -> str: ...
    @ci_pulse_time_dig_fltr_timebase_src.setter
    def ci_pulse_time_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_pulse_time_dig_fltr_timebase_src.deleter
    def ci_pulse_time_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_pulse_time_dig_sync_enable(self) -> bool: ...
    @ci_pulse_time_dig_sync_enable.setter
    def ci_pulse_time_dig_sync_enable(self, val: bool) -> None: ...
    @ci_pulse_time_dig_sync_enable.deleter
    def ci_pulse_time_dig_sync_enable(self) -> None: ...
    @property
    def ci_pulse_time_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_pulse_time_logic_lvl_behavior.setter
    def ci_pulse_time_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_pulse_time_logic_lvl_behavior.deleter
    def ci_pulse_time_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_pulse_time_starting_edge(self) -> Edge: ...
    @ci_pulse_time_starting_edge.setter
    def ci_pulse_time_starting_edge(self, val: Edge) -> None: ...
    @ci_pulse_time_starting_edge.deleter
    def ci_pulse_time_starting_edge(self) -> None: ...
    @property
    def ci_pulse_time_term(self) -> str: ...
    @ci_pulse_time_term.setter
    def ci_pulse_time_term(self, val: str) -> None: ...
    @ci_pulse_time_term.deleter
    def ci_pulse_time_term(self) -> None: ...
    @property
    def ci_pulse_time_term_cfg(self) -> TerminalConfiguration: ...
    @ci_pulse_time_term_cfg.setter
    def ci_pulse_time_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_pulse_time_term_cfg.deleter
    def ci_pulse_time_term_cfg(self) -> None: ...
    @property
    def ci_pulse_time_units(self) -> TimeUnits: ...
    @ci_pulse_time_units.setter
    def ci_pulse_time_units(self, val: TimeUnits) -> None: ...
    @ci_pulse_time_units.deleter
    def ci_pulse_time_units(self) -> None: ...
    @property
    def ci_pulse_width_dig_fltr_enable(self) -> bool: ...
    @ci_pulse_width_dig_fltr_enable.setter
    def ci_pulse_width_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_pulse_width_dig_fltr_enable.deleter
    def ci_pulse_width_dig_fltr_enable(self) -> None: ...
    @property
    def ci_pulse_width_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_pulse_width_dig_fltr_min_pulse_width.setter
    def ci_pulse_width_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_pulse_width_dig_fltr_min_pulse_width.deleter
    def ci_pulse_width_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_pulse_width_dig_fltr_timebase_rate(self) -> float: ...
    @ci_pulse_width_dig_fltr_timebase_rate.setter
    def ci_pulse_width_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_pulse_width_dig_fltr_timebase_rate.deleter
    def ci_pulse_width_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_pulse_width_dig_fltr_timebase_src(self) -> str: ...
    @ci_pulse_width_dig_fltr_timebase_src.setter
    def ci_pulse_width_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_pulse_width_dig_fltr_timebase_src.deleter
    def ci_pulse_width_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_pulse_width_dig_sync_enable(self) -> bool: ...
    @ci_pulse_width_dig_sync_enable.setter
    def ci_pulse_width_dig_sync_enable(self, val: bool) -> None: ...
    @ci_pulse_width_dig_sync_enable.deleter
    def ci_pulse_width_dig_sync_enable(self) -> None: ...
    @property
    def ci_pulse_width_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_pulse_width_logic_lvl_behavior.setter
    def ci_pulse_width_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_pulse_width_logic_lvl_behavior.deleter
    def ci_pulse_width_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_pulse_width_starting_edge(self) -> Edge: ...
    @ci_pulse_width_starting_edge.setter
    def ci_pulse_width_starting_edge(self, val: Edge) -> None: ...
    @ci_pulse_width_starting_edge.deleter
    def ci_pulse_width_starting_edge(self) -> None: ...
    @property
    def ci_pulse_width_term(self) -> str: ...
    @ci_pulse_width_term.setter
    def ci_pulse_width_term(self, val: str) -> None: ...
    @ci_pulse_width_term.deleter
    def ci_pulse_width_term(self) -> None: ...
    @property
    def ci_pulse_width_term_cfg(self) -> TerminalConfiguration: ...
    @ci_pulse_width_term_cfg.setter
    def ci_pulse_width_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_pulse_width_term_cfg.deleter
    def ci_pulse_width_term_cfg(self) -> None: ...
    @property
    def ci_pulse_width_units(self) -> TimeUnits: ...
    @ci_pulse_width_units.setter
    def ci_pulse_width_units(self, val: TimeUnits) -> None: ...
    @ci_pulse_width_units.deleter
    def ci_pulse_width_units(self) -> None: ...
    @property
    def ci_samp_clk_overrun_behavior(self) -> SampClkOverrunBehavior: ...
    @ci_samp_clk_overrun_behavior.setter
    def ci_samp_clk_overrun_behavior(self, val: SampClkOverrunBehavior) -> None: ...
    @ci_samp_clk_overrun_behavior.deleter
    def ci_samp_clk_overrun_behavior(self) -> None: ...
    @property
    def ci_samp_clk_overrun_sentinel_val(self) -> int: ...
    @ci_samp_clk_overrun_sentinel_val.setter
    def ci_samp_clk_overrun_sentinel_val(self, val: int) -> None: ...
    @ci_samp_clk_overrun_sentinel_val.deleter
    def ci_samp_clk_overrun_sentinel_val(self) -> None: ...
    @property
    def ci_semi_period_dig_fltr_enable(self) -> bool: ...
    @ci_semi_period_dig_fltr_enable.setter
    def ci_semi_period_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_semi_period_dig_fltr_enable.deleter
    def ci_semi_period_dig_fltr_enable(self) -> None: ...
    @property
    def ci_semi_period_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_semi_period_dig_fltr_min_pulse_width.setter
    def ci_semi_period_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_semi_period_dig_fltr_min_pulse_width.deleter
    def ci_semi_period_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_semi_period_dig_fltr_timebase_rate(self) -> float: ...
    @ci_semi_period_dig_fltr_timebase_rate.setter
    def ci_semi_period_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_semi_period_dig_fltr_timebase_rate.deleter
    def ci_semi_period_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_semi_period_dig_fltr_timebase_src(self) -> str: ...
    @ci_semi_period_dig_fltr_timebase_src.setter
    def ci_semi_period_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_semi_period_dig_fltr_timebase_src.deleter
    def ci_semi_period_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_semi_period_dig_sync_enable(self) -> bool: ...
    @ci_semi_period_dig_sync_enable.setter
    def ci_semi_period_dig_sync_enable(self, val: bool) -> None: ...
    @ci_semi_period_dig_sync_enable.deleter
    def ci_semi_period_dig_sync_enable(self) -> None: ...
    @property
    def ci_semi_period_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_semi_period_logic_lvl_behavior.setter
    def ci_semi_period_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_semi_period_logic_lvl_behavior.deleter
    def ci_semi_period_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_semi_period_starting_edge(self) -> Edge: ...
    @ci_semi_period_starting_edge.setter
    def ci_semi_period_starting_edge(self, val: Edge) -> None: ...
    @ci_semi_period_starting_edge.deleter
    def ci_semi_period_starting_edge(self) -> None: ...
    @property
    def ci_semi_period_term(self) -> str: ...
    @ci_semi_period_term.setter
    def ci_semi_period_term(self, val: str) -> None: ...
    @ci_semi_period_term.deleter
    def ci_semi_period_term(self) -> None: ...
    @property
    def ci_semi_period_term_cfg(self) -> TerminalConfiguration: ...
    @ci_semi_period_term_cfg.setter
    def ci_semi_period_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_semi_period_term_cfg.deleter
    def ci_semi_period_term_cfg(self) -> None: ...
    @property
    def ci_semi_period_units(self) -> TimeUnits: ...
    @ci_semi_period_units.setter
    def ci_semi_period_units(self, val: TimeUnits) -> None: ...
    @ci_semi_period_units.deleter
    def ci_semi_period_units(self) -> None: ...
    @property
    def ci_tc_reached(self) -> bool: ...
    @property
    def ci_thresh_voltage(selfbool) -> float: ...
    @ci_thresh_voltage.setter
    def ci_thresh_voltage(self, val: float) -> None: ...
    @ci_thresh_voltage.deleter
    def ci_thresh_voltage(self) -> None: ...
    @property
    def ci_timestamp_initial_seconds(self) -> int: ...
    @ci_timestamp_initial_seconds.setter
    def ci_timestamp_initial_seconds(self, val: int) -> None: ...
    @ci_timestamp_initial_seconds.deleter
    def ci_timestamp_initial_seconds(self) -> None: ...
    @property
    def ci_timestamp_units(self) -> TimeUnits: ...
    @ci_timestamp_units.setter
    def ci_timestamp_units(self, val: TimeUnits) -> None: ...
    @ci_timestamp_units.deleter
    def ci_timestamp_units(self) -> None: ...
    @property
    def ci_two_edge_sep_first_dig_fltr_enable(self) -> bool: ...
    @ci_two_edge_sep_first_dig_fltr_enable.setter
    def ci_two_edge_sep_first_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_two_edge_sep_first_dig_fltr_enable.deleter
    def ci_two_edge_sep_first_dig_fltr_enable(self) -> None: ...
    @property
    def ci_two_edge_sep_first_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_two_edge_sep_first_dig_fltr_min_pulse_width.setter
    def ci_two_edge_sep_first_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_two_edge_sep_first_dig_fltr_min_pulse_width.deleter
    def ci_two_edge_sep_first_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_two_edge_sep_first_dig_fltr_timebase_rate(self) -> float: ...
    @ci_two_edge_sep_first_dig_fltr_timebase_rate.setter
    def ci_two_edge_sep_first_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_two_edge_sep_first_dig_fltr_timebase_rate.deleter
    def ci_two_edge_sep_first_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_two_edge_sep_first_dig_fltr_timebase_src(self) -> str: ...
    @ci_two_edge_sep_first_dig_fltr_timebase_src.setter
    def ci_two_edge_sep_first_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_two_edge_sep_first_dig_fltr_timebase_src.deleter
    def ci_two_edge_sep_first_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_two_edge_sep_first_dig_sync_enable(self) -> bool: ...
    @ci_two_edge_sep_first_dig_sync_enable.setter
    def ci_two_edge_sep_first_dig_sync_enable(self, val: bool) -> None: ...
    @ci_two_edge_sep_first_dig_sync_enable.deleter
    def ci_two_edge_sep_first_dig_sync_enable(self) -> None: ...
    @property
    def ci_two_edge_sep_first_edge(self) -> Edge: ...
    @ci_two_edge_sep_first_edge.setter
    def ci_two_edge_sep_first_edge(self, val: Edge) -> None: ...
    @ci_two_edge_sep_first_edge.deleter
    def ci_two_edge_sep_first_edge(self) -> None: ...
    @property
    def ci_two_edge_sep_first_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_two_edge_sep_first_logic_lvl_behavior.setter
    def ci_two_edge_sep_first_logic_lvl_behavior(
        self, val: LogicLvlBehavior
    ) -> None: ...
    @ci_two_edge_sep_first_logic_lvl_behavior.deleter
    def ci_two_edge_sep_first_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_two_edge_sep_first_term(self) -> str: ...
    @ci_two_edge_sep_first_term.setter
    def ci_two_edge_sep_first_term(self, val: str) -> None: ...
    @ci_two_edge_sep_first_term.deleter
    def ci_two_edge_sep_first_term(self) -> None: ...
    @property
    def ci_two_edge_sep_first_term_cfg(self) -> TerminalConfiguration: ...
    @ci_two_edge_sep_first_term_cfg.setter
    def ci_two_edge_sep_first_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_two_edge_sep_first_term_cfg.deleter
    def ci_two_edge_sep_first_term_cfg(self) -> None: ...
    @property
    def ci_two_edge_sep_second_dig_fltr_enable(self) -> bool: ...
    @ci_two_edge_sep_second_dig_fltr_enable.setter
    def ci_two_edge_sep_second_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_two_edge_sep_second_dig_fltr_enable.deleter
    def ci_two_edge_sep_second_dig_fltr_enable(self) -> None: ...
    @property
    def ci_two_edge_sep_second_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_two_edge_sep_second_dig_fltr_min_pulse_width.setter
    def ci_two_edge_sep_second_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_two_edge_sep_second_dig_fltr_min_pulse_width.deleter
    def ci_two_edge_sep_second_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_two_edge_sep_second_dig_fltr_timebase_rate(self) -> float: ...
    @ci_two_edge_sep_second_dig_fltr_timebase_rate.setter
    def ci_two_edge_sep_second_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_two_edge_sep_second_dig_fltr_timebase_rate.deleter
    def ci_two_edge_sep_second_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_two_edge_sep_second_dig_fltr_timebase_src(self) -> str: ...
    @ci_two_edge_sep_second_dig_fltr_timebase_src.setter
    def ci_two_edge_sep_second_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_two_edge_sep_second_dig_fltr_timebase_src.deleter
    def ci_two_edge_sep_second_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_two_edge_sep_second_dig_sync_enable(self) -> bool: ...
    @ci_two_edge_sep_second_dig_sync_enable.setter
    def ci_two_edge_sep_second_dig_sync_enable(self, val: bool) -> None: ...
    @ci_two_edge_sep_second_dig_sync_enable.deleter
    def ci_two_edge_sep_second_dig_sync_enable(self) -> None: ...
    @property
    def ci_two_edge_sep_second_edge(self) -> Edge: ...
    @ci_two_edge_sep_second_edge.setter
    def ci_two_edge_sep_second_edge(self, val: Edge) -> None: ...
    @ci_two_edge_sep_second_edge.deleter
    def ci_two_edge_sep_second_edge(self) -> None: ...
    @property
    def ci_two_edge_sep_second_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_two_edge_sep_second_logic_lvl_behavior.setter
    def ci_two_edge_sep_second_logic_lvl_behavior(
        self, val: LogicLvlBehavior
    ) -> None: ...
    @ci_two_edge_sep_second_logic_lvl_behavior.deleter
    def ci_two_edge_sep_second_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_two_edge_sep_second_term(self) -> str: ...
    @ci_two_edge_sep_second_term.setter
    def ci_two_edge_sep_second_term(self, val: str) -> None: ...
    @ci_two_edge_sep_second_term.deleter
    def ci_two_edge_sep_second_term(self) -> None: ...
    @property
    def ci_two_edge_sep_second_term_cfg(self) -> TerminalConfiguration: ...
    @ci_two_edge_sep_second_term_cfg.setter
    def ci_two_edge_sep_second_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_two_edge_sep_second_term_cfg.deleter
    def ci_two_edge_sep_second_term_cfg(self) -> None: ...
    @property
    def ci_two_edge_sep_units(self) -> TimeUnits: ...
    @ci_two_edge_sep_units.setter
    def ci_two_edge_sep_units(self, val: TimeUnits) -> None: ...
    @ci_two_edge_sep_units.deleter
    def ci_two_edge_sep_units(self) -> None: ...
    @property
    def ci_usb_xfer_req_count(self) -> int: ...
    @ci_usb_xfer_req_count.setter
    def ci_usb_xfer_req_count(self, val: int) -> None: ...
    @ci_usb_xfer_req_count.deleter
    def ci_usb_xfer_req_count(self) -> None: ...
    @property
    def ci_usb_xfer_req_size(self) -> int: ...
    @ci_usb_xfer_req_size.setter
    def ci_usb_xfer_req_size(self, val: int) -> None: ...
    @ci_usb_xfer_req_size.deleter
    def ci_usb_xfer_req_size(self) -> None: ...
    @property
    def ci_velocity_a_input_dig_fltr_enable(self) -> bool: ...
    @ci_velocity_a_input_dig_fltr_enable.setter
    def ci_velocity_a_input_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_velocity_a_input_dig_fltr_enable.deleter
    def ci_velocity_a_input_dig_fltr_enable(self) -> None: ...
    @property
    def ci_velocity_a_input_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_velocity_a_input_dig_fltr_min_pulse_width.setter
    def ci_velocity_a_input_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_velocity_a_input_dig_fltr_min_pulse_width.deleter
    def ci_velocity_a_input_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_velocity_a_input_dig_fltr_timebase_rate(self) -> float: ...
    @ci_velocity_a_input_dig_fltr_timebase_rate.setter
    def ci_velocity_a_input_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_velocity_a_input_dig_fltr_timebase_rate.deleter
    def ci_velocity_a_input_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_velocity_a_input_dig_fltr_timebase_src(self) -> str: ...
    @ci_velocity_a_input_dig_fltr_timebase_src.setter
    def ci_velocity_a_input_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_velocity_a_input_dig_fltr_timebase_src.deleter
    def ci_velocity_a_input_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_velocity_a_input_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_velocity_a_input_logic_lvl_behavior.setter
    def ci_velocity_a_input_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_velocity_a_input_logic_lvl_behavior.deleter
    def ci_velocity_a_input_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_velocity_a_input_term(self) -> str: ...
    @ci_velocity_a_input_term.setter
    def ci_velocity_a_input_term(self, val: str) -> None: ...
    @ci_velocity_a_input_term.deleter
    def ci_velocity_a_input_term(self) -> None: ...
    @property
    def ci_velocity_a_input_term_cfg(self) -> TerminalConfiguration: ...
    @ci_velocity_a_input_term_cfg.setter
    def ci_velocity_a_input_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_velocity_a_input_term_cfg.deleter
    def ci_velocity_a_input_term_cfg(self) -> None: ...
    @property
    def ci_velocity_ang_encoder_pulses_per_rev(self) -> int: ...
    @ci_velocity_ang_encoder_pulses_per_rev.setter
    def ci_velocity_ang_encoder_pulses_per_rev(self, val: int) -> None: ...
    @ci_velocity_ang_encoder_pulses_per_rev.deleter
    def ci_velocity_ang_encoder_pulses_per_rev(self) -> None: ...
    @property
    def ci_velocity_ang_encoder_units(self) -> AngularVelocityUnits: ...
    @ci_velocity_ang_encoder_units.setter
    def ci_velocity_ang_encoder_units(self, val: AngularVelocityUnits) -> None: ...
    @ci_velocity_ang_encoder_units.deleter
    def ci_velocity_ang_encoder_units(self) -> None: ...
    @property
    def ci_velocity_b_input_dig_fltr_enable(self) -> bool: ...
    @ci_velocity_b_input_dig_fltr_enable.setter
    def ci_velocity_b_input_dig_fltr_enable(self, val: bool) -> None: ...
    @ci_velocity_b_input_dig_fltr_enable.deleter
    def ci_velocity_b_input_dig_fltr_enable(self) -> None: ...
    @property
    def ci_velocity_b_input_dig_fltr_min_pulse_width(self) -> float: ...
    @ci_velocity_b_input_dig_fltr_min_pulse_width.setter
    def ci_velocity_b_input_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ci_velocity_b_input_dig_fltr_min_pulse_width.deleter
    def ci_velocity_b_input_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ci_velocity_b_input_dig_fltr_timebase_rate(self) -> float: ...
    @ci_velocity_b_input_dig_fltr_timebase_rate.setter
    def ci_velocity_b_input_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ci_velocity_b_input_dig_fltr_timebase_rate.deleter
    def ci_velocity_b_input_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ci_velocity_b_input_dig_fltr_timebase_src(self) -> str: ...
    @ci_velocity_b_input_dig_fltr_timebase_src.setter
    def ci_velocity_b_input_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ci_velocity_b_input_dig_fltr_timebase_src.deleter
    def ci_velocity_b_input_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ci_velocity_b_input_logic_lvl_behavior(self) -> LogicLvlBehavior: ...
    @ci_velocity_b_input_logic_lvl_behavior.setter
    def ci_velocity_b_input_logic_lvl_behavior(self, val: LogicLvlBehavior) -> None: ...
    @ci_velocity_b_input_logic_lvl_behavior.deleter
    def ci_velocity_b_input_logic_lvl_behavior(self) -> None: ...
    @property
    def ci_velocity_b_input_term(self) -> str: ...
    @ci_velocity_b_input_term.setter
    def ci_velocity_b_input_term(self, val: str) -> None: ...
    @ci_velocity_b_input_term.deleter
    def ci_velocity_b_input_term(self) -> None: ...
    @property
    def ci_velocity_b_input_term_cfg(self) -> TerminalConfiguration: ...
    @ci_velocity_b_input_term_cfg.setter
    def ci_velocity_b_input_term_cfg(self, val: TerminalConfiguration) -> None: ...
    @ci_velocity_b_input_term_cfg.deleter
    def ci_velocity_b_input_term_cfg(self) -> None: ...
    @property
    def ci_velocity_div(self) -> int: ...
    @ci_velocity_div.setter
    def ci_velocity_div(self, val: int) -> None: ...
    @ci_velocity_div.deleter
    def ci_velocity_div(self) -> None: ...
    @property
    def ci_velocity_encoder_decoding_type(self) -> EncoderType: ...
    @ci_velocity_encoder_decoding_type.setter
    def ci_velocity_encoder_decoding_type(self, val: EncoderType) -> None: ...
    @ci_velocity_encoder_decoding_type.deleter
    def ci_velocity_encoder_decoding_type(self) -> None: ...
    @property
    def ci_velocity_lin_encoder_dist_per_pulse(self) -> float: ...
    @ci_velocity_lin_encoder_dist_per_pulse.setter
    def ci_velocity_lin_encoder_dist_per_pulse(self, val: float) -> None: ...
    @ci_velocity_lin_encoder_dist_per_pulse.deleter
    def ci_velocity_lin_encoder_dist_per_pulse(self) -> None: ...
    @property
    def ci_velocity_lin_encoder_units(self) -> VelocityUnits: ...
    @ci_velocity_lin_encoder_units.setter
    def ci_velocity_lin_encoder_units(self, val: VelocityUnits) -> None: ...
    @ci_velocity_lin_encoder_units.deleter
    def ci_velocity_lin_encoder_units(self) -> None: ...
    @property
    def ci_velocity_meas_time(self) -> float: ...
    @ci_velocity_meas_time.setter
    def ci_velocity_meas_time(self, val: float) -> None: ...
    @ci_velocity_meas_time.deleter
    def ci_velocity_meas_time(self) -> None: ...
