from ...task.channels._channel import Channel
from ...constants import (
    ConstrainedGenMode,
    DataTransferActiveTransferMode,
    Edge,
    FrequencyUnits,
    Level,
    OutputDataTransferCondition,
    TimeUnits,
    UsageTypeCO,
)

class COChannel(Channel):
    def __repr__(self) -> str: ...
    @property
    def co_auto_incr_cnt(self) -> int: ...
    @co_auto_incr_cnt.setter
    def co_auto_incr_cnt(self, val: int) -> None: ...
    @co_auto_incr_cnt.deleter
    def co_auto_incr_cnt(self) -> None: ...
    @property
    def co_constrained_gen_mode(self) -> ConstrainedGenMode: ...
    @co_constrained_gen_mode.setter
    def co_constrained_gen_mode(self, val: ConstrainedGenMode) -> None: ...
    @co_constrained_gen_mode.deleter
    def co_constrained_gen_mode(self) -> None: ...
    @property
    def co_count(self) -> int: ...
    @property
    def co_ctr_timebase_active_edge(self) -> Edge: ...
    @co_ctr_timebase_active_edge.setter
    def co_ctr_timebase_active_edge(self, val: Edge) -> None: ...
    @co_ctr_timebase_active_edge.deleter
    def co_ctr_timebase_active_edge(self) -> None: ...
    @property
    def co_ctr_timebase_dig_fltr_enable(self) -> bool: ...
    @co_ctr_timebase_dig_fltr_enable.setter
    def co_ctr_timebase_dig_fltr_enable(self, val: bool) -> None: ...
    @co_ctr_timebase_dig_fltr_enable.deleter
    def co_ctr_timebase_dig_fltr_enable(self) -> None: ...
    @property
    def co_ctr_timebase_dig_fltr_min_pulse_width(self) -> float: ...
    @co_ctr_timebase_dig_fltr_min_pulse_width.setter
    def co_ctr_timebase_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @co_ctr_timebase_dig_fltr_min_pulse_width.deleter
    def co_ctr_timebase_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def co_ctr_timebase_dig_fltr_timebase_rate(self) -> float: ...
    @co_ctr_timebase_dig_fltr_timebase_rate.setter
    def co_ctr_timebase_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @co_ctr_timebase_dig_fltr_timebase_rate.deleter
    def co_ctr_timebase_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def co_ctr_timebase_dig_fltr_timebase_src(self) -> str: ...
    @co_ctr_timebase_dig_fltr_timebase_src.setter
    def co_ctr_timebase_dig_fltr_timebase_src(self, val: str) -> None: ...
    @co_ctr_timebase_dig_fltr_timebase_src.deleter
    def co_ctr_timebase_dig_fltr_timebase_src(self) -> None: ...
    @property
    def co_ctr_timebase_dig_sync_enable(self) -> bool: ...
    @co_ctr_timebase_dig_sync_enable.setter
    def co_ctr_timebase_dig_sync_enable(self, val: bool) -> None: ...
    @co_ctr_timebase_dig_sync_enable.deleter
    def co_ctr_timebase_dig_sync_enable(self) -> None: ...
    @property
    def co_ctr_timebase_master_timebase_div(self) -> int: ...
    @co_ctr_timebase_master_timebase_div.setter
    def co_ctr_timebase_master_timebase_div(self, val: int) -> None: ...
    @co_ctr_timebase_master_timebase_div.deleter
    def co_ctr_timebase_master_timebase_div(self) -> None: ...
    @property
    def co_ctr_timebase_rate(self) -> float: ...
    @co_ctr_timebase_rate.setter
    def co_ctr_timebase_rate(self, val: float) -> None: ...
    @co_ctr_timebase_rate.deleter
    def co_ctr_timebase_rate(self) -> None: ...
    @property
    def co_ctr_timebase_src(self) -> str: ...
    @co_ctr_timebase_src.setter
    def co_ctr_timebase_src(self, val: str) -> None: ...
    @co_ctr_timebase_src.deleter
    def co_ctr_timebase_src(self) -> None: ...
    @property
    def co_data_xfer_mech(self) -> DataTransferActiveTransferMode: ...
    @co_data_xfer_mech.setter
    def co_data_xfer_mech(self, val: DataTransferActiveTransferMode) -> None: ...
    @co_data_xfer_mech.deleter
    def co_data_xfer_mech(self) -> None: ...
    @property
    def co_data_xfer_req_cond(self) -> OutputDataTransferCondition: ...
    @co_data_xfer_req_cond.setter
    def co_data_xfer_req_cond(self, val: OutputDataTransferCondition) -> None: ...
    @co_data_xfer_req_cond.deleter
    def co_data_xfer_req_cond(self) -> None: ...
    @property
    def co_enable_initial_delay_on_retrigger(self) -> bool: ...
    @co_enable_initial_delay_on_retrigger.setter
    def co_enable_initial_delay_on_retrigger(self, val: bool) -> None: ...
    @co_enable_initial_delay_on_retrigger.deleter
    def co_enable_initial_delay_on_retrigger(self) -> None: ...
    @property
    def co_mem_map_enable(self) -> bool: ...
    @co_mem_map_enable.setter
    def co_mem_map_enable(self, val: bool) -> None: ...
    @co_mem_map_enable.deleter
    def co_mem_map_enable(self) -> None: ...
    @property
    def co_output_state(self) -> Level: ...
    @property
    def co_output_type(self) -> UsageTypeCO: ...
    @property
    def co_prescaler(self) -> int: ...
    @co_prescaler.setter
    def co_prescaler(self, val: int) -> None: ...
    @co_prescaler.deleter
    def co_prescaler(self) -> None: ...
    @property
    def co_pulse_done(self) -> bool: ...
    @property
    def co_pulse_duty_cyc(self) -> float: ...
    @co_pulse_duty_cyc.setter
    def co_pulse_duty_cyc(self, val: float) -> None: ...
    @co_pulse_duty_cyc.deleter
    def co_pulse_duty_cyc(self) -> None: ...
    @property
    def co_pulse_freq(self) -> float: ...
    @co_pulse_freq.setter
    def co_pulse_freq(self, val: float) -> None: ...
    @co_pulse_freq.deleter
    def co_pulse_freq(self) -> None: ...
    @property
    def co_pulse_freq_initial_delay(self) -> float: ...
    @co_pulse_freq_initial_delay.setter
    def co_pulse_freq_initial_delay(self, val: float) -> None: ...
    @co_pulse_freq_initial_delay.deleter
    def co_pulse_freq_initial_delay(self) -> None: ...
    @property
    def co_pulse_freq_units(self) -> FrequencyUnits: ...
    @co_pulse_freq_units.setter
    def co_pulse_freq_units(self, val: FrequencyUnits) -> None: ...
    @co_pulse_freq_units.deleter
    def co_pulse_freq_units(self) -> None: ...
    @property
    def co_pulse_high_ticks(self) -> int: ...
    @co_pulse_high_ticks.setter
    def co_pulse_high_ticks(self, val: int) -> None: ...
    @co_pulse_high_ticks.deleter
    def co_pulse_high_ticks(self) -> None: ...
    @property
    def co_pulse_high_time(self) -> float: ...
    @co_pulse_high_time.setter
    def co_pulse_high_time(self, val: float) -> None: ...
    @co_pulse_high_time.deleter
    def co_pulse_high_time(self) -> None: ...
    @property
    def co_pulse_idle_state(self) -> Level: ...
    @co_pulse_idle_state.setter
    def co_pulse_idle_state(self, val: Level) -> None: ...
    @co_pulse_idle_state.deleter
    def co_pulse_idle_state(self) -> None: ...
    @property
    def co_pulse_low_ticks(self) -> int: ...
    @co_pulse_low_ticks.setter
    def co_pulse_low_ticks(self, val: int) -> None: ...
    @co_pulse_low_ticks.deleter
    def co_pulse_low_ticks(self) -> None: ...
    @property
    def co_pulse_low_time(self) -> float: ...
    @co_pulse_low_time.setter
    def co_pulse_low_time(self, val: float) -> None: ...
    @co_pulse_low_time.deleter
    def co_pulse_low_time(self) -> None: ...
    @property
    def co_pulse_term(self) -> str: ...
    @co_pulse_term.setter
    def co_pulse_term(self, val: str) -> None: ...
    @co_pulse_term.deleter
    def co_pulse_term(self) -> None: ...
    @property
    def co_pulse_ticks_initial_delay(self) -> int: ...
    @co_pulse_ticks_initial_delay.setter
    def co_pulse_ticks_initial_delay(self, val: int) -> None: ...
    @co_pulse_ticks_initial_delay.deleter
    def co_pulse_ticks_initial_delay(self) -> None: ...
    @property
    def co_pulse_time_initial_delay(self) -> float: ...
    @co_pulse_time_initial_delay.setter
    def co_pulse_time_initial_delay(self, val: float) -> None: ...
    @co_pulse_time_initial_delay.deleter
    def co_pulse_time_initial_delay(self) -> None: ...
    @property
    def co_pulse_time_units(self) -> TimeUnits: ...
    @co_pulse_time_units.setter
    def co_pulse_time_units(self, val: TimeUnits) -> None: ...
    @co_pulse_time_units.deleter
    def co_pulse_time_units(self) -> None: ...
    @property
    def co_rdy_for_new_val(self) -> bool: ...
    @property
    def co_usb_xfer_req_count(self) -> int: ...
    @co_usb_xfer_req_count.setter
    def co_usb_xfer_req_count(self, val: int) -> None: ...
    @co_usb_xfer_req_count.deleter
    def co_usb_xfer_req_count(self) -> None: ...
    @property
    def co_usb_xfer_req_size(self) -> int: ...
    @co_usb_xfer_req_size.setter
    def co_usb_xfer_req_size(self, val: int) -> None: ...
    @co_usb_xfer_req_size.deleter
    def co_usb_xfer_req_size(self) -> None: ...
    @property
    def co_use_only_on_brd_mem(self) -> bool: ...
    @co_use_only_on_brd_mem.setter
    def co_use_only_on_brd_mem(self, val: bool) -> None: ...
    @co_use_only_on_brd_mem.deleter
    def co_use_only_on_brd_mem(self) -> None: ...
