from collections.abc import Iterator

from ...system.device import Device

class DeviceCollection:
    def __contains__(self, item: str | Device) -> bool: ...
    def __getitem__(self, index: int | slice | str) -> Device | list[Device]: ...
    def __iter__(self) -> Iterator[Device]: ...
    def __len__(self) -> int: ...
    @property
    def device_names(self) -> list[str]: ...
