from collections.abc import Iterator, Sequence
from typing import Any

class PersistedTaskCollection(Sequence[str]):
    def __contains__(self, item: str | Any) -> bool: ...
    def __getitem__(self, index: int | slice | str) -> Any: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    @property
    def task_names(self) -> list[str]: ...
