from collections.abc import Iterator

class PhysicalChannel:
    @property
    def name(self) -> str: ...

class AIPhysicalChannelCollection:
    @property
    def channel_names(self) -> list[str]: ...
    def __iter__(self) -> Iterator[PhysicalChannel]: ...

class AOPhysicalChannelCollection(AIPhysicalChannelCollection): ...
class CIPhysicalChannelCollection(AIPhysicalChannelCollection): ...
class COPhysicalChannelCollection(AIPhysicalChannelCollection): ...
class DILinesCollection(AIPhysicalChannelCollection): ...
class DIPortsCollection(AIPhysicalChannelCollection): ...
class DOLinesCollection(AIPhysicalChannelCollection): ...
class DOPortsCollection(AIPhysicalChannelCollection): ...
