from numpy import ndarray
from ..stream_writers._channel_writer_base import ChannelWriterBase

class AnalogUnscaledWriter(ChannelWriterBase):
    def write_int16(self, data: ndarray, timeout: float = 10.0) -> int: ...
    def write_int32(self, data: ndarray, timeout: float = 10.0) -> int: ...
    def write_uint16(self, data: ndarray, timeout: float = 10.0) -> int: ...
    def write_uint32(self, data: ndarray, timeout: float = 10.0) -> int: ...
