from .._grpc_interpreter import GrpcStubInterpreter
from ..constants import (
    DeassertCondition,
    DigitalWidthUnits,
    ExportAction,
    Level,
    Polarity,
    Signal,
)
from .._lib import TaskHandle

class ExportSignals:
    def __init__(
        self, task_handle: TaskHandle, interpreter: GrpcStubInterpreter
    ) -> None: ...
    @property
    def adv_cmplt_event_delay(self) -> float: ...
    @adv_cmplt_event_delay.setter
    def adv_cmplt_event_delay(self, val: float) -> None: ...
    @adv_cmplt_event_delay.deleter
    def adv_cmplt_event_delay(self) -> None: ...
    @property
    def adv_cmplt_event_output_term(self) -> str: ...
    @adv_cmplt_event_output_term.setter
    def adv_cmplt_event_output_term(self, val: str) -> None: ...
    @adv_cmplt_event_output_term.deleter
    def adv_cmplt_event_output_term(self) -> None: ...
    @property
    def adv_cmplt_event_pulse_polarity(self) -> Polarity: ...
    @adv_cmplt_event_pulse_polarity.setter
    def adv_cmplt_event_pulse_polarity(self, val: Polarity) -> None: ...
    @adv_cmplt_event_pulse_polarity.deleter
    def adv_cmplt_event_pulse_polarity(self) -> None: ...
    @property
    def adv_cmplt_event_pulse_width(self) -> float: ...
    @adv_cmplt_event_pulse_width.setter
    def adv_cmplt_event_pulse_width(self, val: float) -> None: ...
    @adv_cmplt_event_pulse_width.deleter
    def adv_cmplt_event_pulse_width(self) -> None: ...
    @property
    def adv_trig_output_term(self) -> str: ...
    @adv_trig_output_term.setter
    def adv_trig_output_term(self, val: str) -> None: ...
    @adv_trig_output_term.deleter
    def adv_trig_output_term(self) -> None: ...
    @property
    def adv_trig_pulse_polarity(self) -> Polarity: ...
    @property
    def adv_trig_pulse_width(self) -> float: ...
    @adv_trig_pulse_width.setter
    def adv_trig_pulse_width(self, val: float) -> None: ...
    @adv_trig_pulse_width.deleter
    def adv_trig_pulse_width(self) -> None: ...
    @property
    def adv_trig_pulse_width_units(self) -> DigitalWidthUnits: ...
    @adv_trig_pulse_width_units.setter
    def adv_trig_pulse_width_units(self, val: DigitalWidthUnits) -> None: ...
    @adv_trig_pulse_width_units.deleter
    def adv_trig_pulse_width_units(self) -> None: ...
    @property
    def ai_conv_clk_output_term(self) -> str: ...
    @ai_conv_clk_output_term.setter
    def ai_conv_clk_output_term(self, val: str) -> None: ...
    @ai_conv_clk_output_term.deleter
    def ai_conv_clk_output_term(self) -> None: ...
    @property
    def ai_conv_clk_pulse_polarity(self) -> Polarity: ...
    @property
    def ai_hold_cmplt_event_output_term(self) -> str: ...
    @ai_hold_cmplt_event_output_term.setter
    def ai_hold_cmplt_event_output_term(self, val: str) -> None: ...
    @ai_hold_cmplt_event_output_term.deleter
    def ai_hold_cmplt_event_output_term(self) -> None: ...
    @property
    def ai_hold_cmplt_event_pulse_polarity(self) -> Polarity: ...
    @ai_hold_cmplt_event_pulse_polarity.setter
    def ai_hold_cmplt_event_pulse_polarity(self, val: Polarity) -> None: ...
    @ai_hold_cmplt_event_pulse_polarity.deleter
    def ai_hold_cmplt_event_pulse_polarity(self) -> None: ...
    @property
    def change_detect_event_output_term(self) -> str: ...
    @change_detect_event_output_term.setter
    def change_detect_event_output_term(self, val: str) -> None: ...
    @change_detect_event_output_term.deleter
    def change_detect_event_output_term(self) -> None: ...
    @property
    def change_detect_event_pulse_polarity(self) -> Polarity: ...
    @change_detect_event_pulse_polarity.setter
    def change_detect_event_pulse_polarity(self, val: Polarity) -> None: ...
    @change_detect_event_pulse_polarity.deleter
    def change_detect_event_pulse_polarity(self) -> None: ...
    @property
    def ctr_out_event_output_behavior(self) -> ExportAction: ...
    @ctr_out_event_output_behavior.setter
    def ctr_out_event_output_behavior(self, val: ExportAction) -> None: ...
    @ctr_out_event_output_behavior.deleter
    def ctr_out_event_output_behavior(self) -> None: ...
    @property
    def ctr_out_event_output_term(self) -> str: ...
    @ctr_out_event_output_term.setter
    def ctr_out_event_output_term(self, val: str) -> None: ...
    @ctr_out_event_output_term.deleter
    def ctr_out_event_output_term(self) -> None: ...
    @property
    def ctr_out_event_pulse_polarity(self) -> Polarity: ...
    @ctr_out_event_pulse_polarity.setter
    def ctr_out_event_pulse_polarity(self, val: Polarity) -> None: ...
    @ctr_out_event_pulse_polarity.deleter
    def ctr_out_event_pulse_polarity(self) -> None: ...
    @property
    def ctr_out_event_toggle_idle_state(self) -> Level: ...
    @ctr_out_event_toggle_idle_state.setter
    def ctr_out_event_toggle_idle_state(self, val: Level) -> None: ...
    @ctr_out_event_toggle_idle_state.deleter
    def ctr_out_event_toggle_idle_state(self) -> None: ...
    @property
    def data_active_event_lvl_active_lvl(self) -> Polarity: ...
    @data_active_event_lvl_active_lvl.setter
    def data_active_event_lvl_active_lvl(self, val: Polarity) -> None: ...
    @data_active_event_lvl_active_lvl.deleter
    def data_active_event_lvl_active_lvl(self) -> None: ...
    @property
    def data_active_event_output_term(self) -> str: ...
    @data_active_event_output_term.setter
    def data_active_event_output_term(self, val: str) -> None: ...
    @data_active_event_output_term.deleter
    def data_active_event_output_term(self) -> None: ...
    @property
    def divided_samp_clk_timebase_output_term(self) -> str: ...
    @divided_samp_clk_timebase_output_term.setter
    def divided_samp_clk_timebase_output_term(self, val: str) -> None: ...
    @divided_samp_clk_timebase_output_term.deleter
    def divided_samp_clk_timebase_output_term(self) -> None: ...
    @property
    def exported_10_mhz_ref_clk_output_term(self) -> str: ...
    @exported_10_mhz_ref_clk_output_term.setter
    def exported_10_mhz_ref_clk_output_term(self, val: str) -> None: ...
    @exported_10_mhz_ref_clk_output_term.deleter
    def exported_10_mhz_ref_clk_output_term(self) -> None: ...
    @property
    def exported_20_mhz_timebase_output_term(self) -> str: ...
    @exported_20_mhz_timebase_output_term.setter
    def exported_20_mhz_timebase_output_term(self, val: str) -> None: ...
    @exported_20_mhz_timebase_output_term.deleter
    def exported_20_mhz_timebase_output_term(self) -> None: ...
    @property
    def hshk_event_delay(self) -> float: ...
    @hshk_event_delay.setter
    def hshk_event_delay(self, val: float) -> None: ...
    @hshk_event_delay.deleter
    def hshk_event_delay(self) -> None: ...
    @property
    def hshk_event_interlocked_assert_on_start(self) -> bool: ...
    @hshk_event_interlocked_assert_on_start.setter
    def hshk_event_interlocked_assert_on_start(self, val: bool) -> None: ...
    @hshk_event_interlocked_assert_on_start.deleter
    def hshk_event_interlocked_assert_on_start(self) -> None: ...
    @property
    def hshk_event_interlocked_asserted_lvl(self) -> Level: ...
    @hshk_event_interlocked_asserted_lvl.setter
    def hshk_event_interlocked_asserted_lvl(self, val: Level) -> None: ...
    @hshk_event_interlocked_asserted_lvl.deleter
    def hshk_event_interlocked_asserted_lvl(self) -> None: ...
    @property
    def hshk_event_interlocked_deassert_delay(self) -> float: ...
    @hshk_event_interlocked_deassert_delay.setter
    def hshk_event_interlocked_deassert_delay(self, val: float) -> None: ...
    @hshk_event_interlocked_deassert_delay.deleter
    def hshk_event_interlocked_deassert_delay(self) -> None: ...
    @property
    def hshk_event_output_behavior(self) -> ExportAction: ...
    @hshk_event_output_behavior.setter
    def hshk_event_output_behavior(self, val: ExportAction) -> None: ...
    @hshk_event_output_behavior.deleter
    def hshk_event_output_behavior(self) -> None: ...
    @property
    def hshk_event_output_term(self) -> str: ...
    @hshk_event_output_term.setter
    def hshk_event_output_term(self, val: str) -> None: ...
    @hshk_event_output_term.deleter
    def hshk_event_output_term(self) -> None: ...
    @property
    def hshk_event_pulse_polarity(self) -> Polarity: ...
    @hshk_event_pulse_polarity.setter
    def hshk_event_pulse_polarity(self, val: Polarity) -> None: ...
    @hshk_event_pulse_polarity.deleter
    def hshk_event_pulse_polarity(self) -> None: ...
    @property
    def hshk_event_pulse_width(self) -> float: ...
    @hshk_event_pulse_width.setter
    def hshk_event_pulse_width(self, val: float) -> None: ...
    @hshk_event_pulse_width.deleter
    def hshk_event_pulse_width(self) -> None: ...
    @property
    def pause_trig_lvl_active_lvl(self) -> Polarity: ...
    @pause_trig_lvl_active_lvl.setter
    def pause_trig_lvl_active_lvl(self, val: Polarity) -> None: ...
    @pause_trig_lvl_active_lvl.deleter
    def pause_trig_lvl_active_lvl(self) -> None: ...
    @property
    def pause_trig_output_term(self) -> str: ...
    @pause_trig_output_term.setter
    def pause_trig_output_term(self, val: str) -> None: ...
    @pause_trig_output_term.deleter
    def pause_trig_output_term(self) -> None: ...
    @property
    def rdy_for_start_event_lvl_active_lvl(self) -> Polarity: ...
    @rdy_for_start_event_lvl_active_lvl.setter
    def rdy_for_start_event_lvl_active_lvl(self, val: Polarity) -> None: ...
    @rdy_for_start_event_lvl_active_lvl.deleter
    def rdy_for_start_event_lvl_active_lvl(self) -> None: ...
    @property
    def rdy_for_start_event_output_term(self) -> str: ...
    @rdy_for_start_event_output_term.setter
    def rdy_for_start_event_output_term(self, val: str) -> None: ...
    @rdy_for_start_event_output_term.deleter
    def rdy_for_start_event_output_term(self) -> None: ...
    @property
    def rdy_for_xfer_event_deassert_cond(self) -> DeassertCondition: ...
    @rdy_for_xfer_event_deassert_cond.setter
    def rdy_for_xfer_event_deassert_cond(self, val: DeassertCondition) -> None: ...
    @rdy_for_xfer_event_deassert_cond.deleter
    def rdy_for_xfer_event_deassert_cond(self) -> None: ...
    @property
    def rdy_for_xfer_event_deassert_cond_custom_threshold(self) -> int: ...
    @rdy_for_xfer_event_deassert_cond_custom_threshold.setter
    def rdy_for_xfer_event_deassert_cond_custom_threshold(self, val: int) -> None: ...
    @rdy_for_xfer_event_deassert_cond_custom_threshold.deleter
    def rdy_for_xfer_event_deassert_cond_custom_threshold(self) -> None: ...
    @property
    def rdy_for_xfer_event_lvl_active_lvl(self) -> Polarity: ...
    @rdy_for_xfer_event_lvl_active_lvl.setter
    def rdy_for_xfer_event_lvl_active_lvl(self, val: Polarity) -> None: ...
    @rdy_for_xfer_event_lvl_active_lvl.deleter
    def rdy_for_xfer_event_lvl_active_lvl(self) -> None: ...
    @property
    def rdy_for_xfer_event_output_term(self) -> str: ...
    @rdy_for_xfer_event_output_term.setter
    def rdy_for_xfer_event_output_term(self, val: str) -> None: ...
    @rdy_for_xfer_event_output_term.deleter
    def rdy_for_xfer_event_output_term(self) -> None: ...
    @property
    def ref_trig_output_term(self) -> str: ...
    @ref_trig_output_term.setter
    def ref_trig_output_term(self, val: str) -> None: ...
    @ref_trig_output_term.deleter
    def ref_trig_output_term(self) -> None: ...
    @property
    def ref_trig_pulse_polarity(self) -> Polarity: ...
    @ref_trig_pulse_polarity.setter
    def ref_trig_pulse_polarity(self, val: Polarity) -> None: ...
    @ref_trig_pulse_polarity.deleter
    def ref_trig_pulse_polarity(self) -> None: ...
    @property
    def samp_clk_delay_offset(self) -> float: ...
    @samp_clk_delay_offset.setter
    def samp_clk_delay_offset(self, val: float) -> None: ...
    @samp_clk_delay_offset.deleter
    def samp_clk_delay_offset(self) -> None: ...
    @property
    def samp_clk_output_behavior(self) -> ExportAction: ...
    @samp_clk_output_behavior.setter
    def samp_clk_output_behavior(self, val: ExportAction) -> None: ...
    @samp_clk_output_behavior.deleter
    def samp_clk_output_behavior(self) -> None: ...
    @property
    def samp_clk_output_term(self) -> str: ...
    @samp_clk_output_term.setter
    def samp_clk_output_term(self, val: str) -> None: ...
    @samp_clk_output_term.deleter
    def samp_clk_output_term(self) -> None: ...
    @property
    def samp_clk_pulse_polarity(self) -> Polarity: ...
    @samp_clk_pulse_polarity.setter
    def samp_clk_pulse_polarity(self, val: Polarity) -> None: ...
    @samp_clk_pulse_polarity.deleter
    def samp_clk_pulse_polarity(self) -> None: ...
    @property
    def samp_clk_timebase_output_term(self) -> str: ...
    @samp_clk_timebase_output_term.setter
    def samp_clk_timebase_output_term(self, val: str) -> None: ...
    @samp_clk_timebase_output_term.deleter
    def samp_clk_timebase_output_term(self) -> None: ...
    @property
    def start_trig_output_term(self) -> str: ...
    @start_trig_output_term.setter
    def start_trig_output_term(self, val: str) -> None: ...
    @start_trig_output_term.deleter
    def start_trig_output_term(self) -> None: ...
    @property
    def start_trig_pulse_polarity(self) -> Polarity: ...
    @start_trig_pulse_polarity.setter
    def start_trig_pulse_polarity(self, val: Polarity) -> None: ...
    @start_trig_pulse_polarity.deleter
    def start_trig_pulse_polarity(self) -> None: ...
    @property
    def sync_pulse_event_output_term(self) -> str: ...
    @sync_pulse_event_output_term.setter
    def sync_pulse_event_output_term(self, val: str) -> None: ...
    @sync_pulse_event_output_term.deleter
    def sync_pulse_event_output_term(self) -> None: ...
    @property
    def watchdog_expired_event_output_term(self) -> str: ...
    @watchdog_expired_event_output_term.setter
    def watchdog_expired_event_output_term(self, val: str) -> None: ...
    @watchdog_expired_event_output_term.deleter
    def watchdog_expired_event_output_term(self) -> None: ...
    def export_signal(self, signal_id: Signal, output_terminal: str) -> None: ...
