from typing import Any

from numpy.typing import NDArray
import pathlib
from .._grpc_interpreter import GrpcStubInterpreter
from .._library_interpreter import LibraryInterpreter
from .._lib import TaskHandle
from ..task.channels import Channel
from ..constants import (
    LoggingMode,
    LoggingOperation,
    OverwriteMode,
    READ_ALL_AVAILABLE,
    ReadRelativeTo,
    WaitMode,
)
from ..constants import WaveformAttributeMode

class InStream:
    """
    Exposes an input data stream on a DAQmx task.

    The input data stream be used to control reading behavior and can be
    used in conjunction with reader classes to read samples from an
    NI-DAQmx task.
    """

    __slots__ = (
        "_task",
        "_handle",
        "_interpreter",
        "_timeout",
        "_waveform_attribute_mode",
    )

    def __init__(
        self,
        task_handle: TaskHandle,
        interpreter: GrpcStubInterpreter | LibraryInterpreter,
    ) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, val: float) -> None: ...
    @timeout.deleter
    def timeout(self) -> None: ...
    @property
    def accessory_insertion_or_removal_detected(self) -> bool: ...
    @property
    def auto_start(self) -> bool: ...
    @auto_start.setter
    def auto_start(self, val: bool) -> None: ...
    @auto_start.deleter
    def auto_start(self) -> None: ...
    @property
    def aux_power_error_chans(self) -> list[str]: ...
    @property
    def aux_power_error_chans_exist(self) -> bool: ...
    @property
    def avail_samp_per_chan(self) -> int: ...
    @property
    def change_detect_overflowed(self) -> bool: ...
    @property
    def channels_to_read(self) -> Channel: ...
    @channels_to_read.setter
    def channels_to_read(self, val: Channel) -> None: ...
    @channels_to_read.deleter
    def channels_to_read(self) -> None: ...
    @property
    def common_mode_range_error_chans(self) -> list[str]: ...
    @property
    def common_mode_range_error_chans_exist(self) -> bool: ...
    @property
    def curr_read_pos(self) -> int: ...
    @property
    def devs_with_inserted_or_removed_accessories(self) -> list[str]: ...
    @property
    def di_num_booleans_per_chan(self) -> int: ...
    @property
    def excit_fault_chans(self) -> list[str]: ...
    @property
    def excit_fault_chans_exist(self) -> bool: ...
    @property
    def input_buf_size(self) -> int: ...
    @input_buf_size.setter
    def input_buf_size(self, val: int) -> None: ...
    @input_buf_size.deleter
    def input_buf_size(self) -> None: ...
    @property
    def input_limits_fault_chans(self) -> list[str]: ...
    @property
    def input_limits_fault_chans_exist(self) -> bool: ...
    @property
    def input_onbrd_buf_size(self) -> int: ...
    @property
    def logging_file_path(self) -> pathlib.Path | None: ...
    @logging_file_path.setter
    def logging_file_path(self, val: str | pathlib.PurePath | None) -> None: ...
    @logging_file_path.deleter
    def logging_file_path(self) -> None: ...
    @property
    def logging_file_preallocation_size(self) -> int: ...
    @logging_file_preallocation_size.setter
    def logging_file_preallocation_size(self, val: int) -> None: ...
    @logging_file_preallocation_size.deleter
    def logging_file_preallocation_size(self) -> None: ...
    @property
    def logging_file_write_size(self) -> int: ...
    @logging_file_write_size.setter
    def logging_file_write_size(self, val: int) -> None: ...
    @logging_file_write_size.deleter
    def logging_file_write_size(self) -> None: ...
    @property
    def logging_mode(self) -> LoggingMode: ...
    @logging_mode.setter
    def logging_mode(self, val: LoggingMode) -> None: ...
    @logging_mode.deleter
    def logging_mode(self) -> None: ...
    @property
    def logging_pause(self) -> bool: ...
    @logging_pause.setter
    def logging_pause(self, val: bool) -> None: ...
    @logging_pause.deleter
    def logging_pause(self) -> None: ...
    @property
    def logging_samps_per_file(self) -> int: ...
    @logging_samps_per_file.setter
    def logging_samps_per_file(self, val: int) -> None: ...
    @logging_samps_per_file.deleter
    def logging_samps_per_file(self) -> None: ...
    @property
    def logging_tdms_group_name(self) -> str: ...
    @logging_tdms_group_name.setter
    def logging_tdms_group_name(self, val: str) -> None: ...
    @logging_tdms_group_name.deleter
    def logging_tdms_group_name(self) -> None: ...
    @property
    def logging_tdms_operation(self) -> LoggingOperation: ...
    @logging_tdms_operation.setter
    def logging_tdms_operation(self, val: LoggingOperation) -> None: ...
    @logging_tdms_operation.deleter
    def logging_tdms_operation(self) -> None: ...
    @property
    def num_chans(self) -> int: ...
    @property
    def offset(self) -> int: ...
    @offset.setter
    def offset(self, val: int) -> None: ...
    @offset.deleter
    def offset(self) -> None: ...
    @property
    def open_chans(self) -> list[str]: ...
    @property
    def open_chans_details(self) -> list[str]: ...
    @property
    def open_chans_exist(self) -> bool: ...
    @property
    def open_current_loop_chans(self) -> list[str]: ...
    @property
    def open_current_loop_chans_exist(self) -> bool: ...
    @property
    def open_thrmcpl_chans(self) -> list[str]: ...
    @property
    def open_thrmcpl_chans_exist(self) -> bool: ...
    @property
    def overcurrent_chans(self) -> list[str]: ...
    @property
    def overcurrent_chans_exist(self) -> bool: ...
    @property
    def overloaded_chans(self) -> list[str]: ...
    @property
    def overloaded_chans_exist(self) -> bool: ...
    @property
    def overtemperature_chans(self) -> list[str]: ...
    @property
    def overtemperature_chans_exist(self) -> bool: ...
    @property
    def overwrite(self) -> OverwriteMode: ...
    @overwrite.setter
    def overwrite(self, val: OverwriteMode) -> None: ...
    @overwrite.deleter
    def overwrite(self) -> None: ...
    @property
    def pll_unlocked_chans(self) -> list[str]: ...
    @property
    def pll_unlocked_chans_exist(self) -> bool: ...
    @property
    def power_supply_fault_chans(self) -> list[str]: ...
    @property
    def power_supply_fault_chans_exist(self) -> bool: ...
    @property
    def raw_data_width(self) -> int: ...
    @property
    def read_all_avail_samp(self) -> bool: ...
    @read_all_avail_samp.setter
    def read_all_avail_samp(self, val: bool) -> None: ...
    @read_all_avail_samp.deleter
    def read_all_avail_samp(self) -> None: ...
    @property
    def relative_to(self) -> ReadRelativeTo: ...
    @relative_to.setter
    def relative_to(self, val: ReadRelativeTo) -> None: ...
    @relative_to.deleter
    def relative_to(self) -> None: ...
    @property
    def remote_sense_error_chans(self) -> list[str]: ...
    @property
    def remote_sense_error_chans_exist(self) -> bool: ...
    @property
    def reverse_voltage_error_chans(self) -> list[str]: ...
    @property
    def reverse_voltage_error_chans_exist(self) -> bool: ...
    @property
    def sleep_time(self) -> float: ...
    @sleep_time.setter
    def sleep_time(self, val: float) -> None: ...
    @sleep_time.deleter
    def sleep_time(self) -> None: ...
    @property
    def sync_unlocked_chans(self) -> list[str]: ...
    @property
    def sync_unlocked_chans_exist(self) -> bool: ...
    @property
    def total_samp_per_chan_acquired(self) -> int: ...
    @property
    def wait_mode(self) -> WaitMode: ...
    @wait_mode.setter
    def wait_mode(self, val: WaitMode) -> None: ...
    @wait_mode.deleter
    def wait_mode(self) -> None: ...
    def get_channels_buffer_size(self) -> int: ...
    def _calculate_num_samps_per_chan(self, num_samps_per_chan: int) -> int: ...
    def configure_logging(
        self,
        file_path: str | pathlib.PurePath,
        logging_mode: LoggingMode = LoggingMode.LOG_AND_READ,
        group_name: str = "",
        operation: LoggingOperation = LoggingOperation.OPEN_OR_CREATE,
    ) -> None: ...
    def read(
        self, number_of_samples_per_channel: int = READ_ALL_AVAILABLE
    ) -> NDArray[Any]: ...
    @property
    def waveform_attribute_mode(self) -> WaveformAttributeMode: ...
    @waveform_attribute_mode.setter
    def waveform_attribute_mode(self, val: WaveformAttributeMode) -> None: ...
    @waveform_attribute_mode.deleter
    def waveform_attribute_mode(self) -> None: ...
