from numpy import ndarray
from .._grpc_interpreter import GrpcStubInterpreter

from ..constants import (
    RegenerationMode,
    WaitMode,
    WriteRelativeTo,
)
from .._lib import TaskHandle

class OutStream:
    def __init__(
        self, task_handle: TaskHandle, interpreter: GrpcStubInterpreter
    ) -> None: ...
    @property
    def auto_start(self) -> bool: ...
    @auto_start.setter
    def auto_start(self, val: bool) -> None: ...
    @auto_start.deleter
    def auto_start(self) -> None: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, val: float) -> None: ...
    @timeout.deleter
    def timeout(self) -> None: ...
    @property
    def accessory_insertion_or_removal_detected(self) -> bool: ...
    @property
    def curr_write_pos(self) -> int: ...
    @property
    def devs_with_inserted_or_removed_accessories(self) -> list[str]: ...
    @property
    def do_num_booleans_per_chan(self) -> int: ...
    @property
    def external_overvoltage_chans(self) -> list[str]: ...
    @property
    def external_overvoltage_chans_exist(self) -> bool: ...
    @property
    def num_chans(self) -> int: ...
    @property
    def offset(self) -> int: ...
    @offset.setter
    def offset(self, val: int) -> None: ...
    @offset.deleter
    def offset(self) -> None: ...
    @property
    def open_current_loop_chans(self) -> list[str]: ...
    @property
    def open_current_loop_chans_exist(self) -> bool: ...
    @property
    def output_buf_size(self) -> int: ...
    @output_buf_size.setter
    def output_buf_size(self, val: int) -> None: ...
    @output_buf_size.deleter
    def output_buf_size(self) -> None: ...
    @property
    def output_onbrd_buf_size(self) -> int: ...
    @output_onbrd_buf_size.setter
    def output_onbrd_buf_size(self, val: int) -> None: ...
    @output_onbrd_buf_size.deleter
    def output_onbrd_buf_size(self) -> None: ...
    @property
    def overcurrent_chans(self) -> list[str]: ...
    @property
    def overcurrent_chans_exist(self) -> bool: ...
    @property
    def overloaded_chans(self) -> list[str]: ...
    @property
    def overloaded_chans_exist(self) -> bool: ...
    @property
    def overtemperature_chans(self) -> list[str]: ...
    @property
    def overtemperature_chans_exist(self) -> bool: ...
    @property
    def power_supply_fault_chans(self) -> list[str]: ...
    @property
    def power_supply_fault_chans_exist(self) -> bool: ...
    @property
    def raw_data_width(self) -> int: ...
    @property
    def regen_mode(self) -> RegenerationMode: ...
    @regen_mode.setter
    def regen_mode(self, val: RegenerationMode) -> None: ...
    @regen_mode.deleter
    def regen_mode(self) -> None: ...
    @property
    def relative_to(self) -> WriteRelativeTo: ...
    @relative_to.setter
    def relative_to(self, val: WriteRelativeTo) -> None: ...
    @relative_to.deleter
    def relative_to(self) -> None: ...
    @property
    def sleep_time(self) -> float: ...
    @sleep_time.setter
    def sleep_time(self, val: float) -> None: ...
    @sleep_time.deleter
    def sleep_time(self) -> None: ...
    @property
    def space_avail(self) -> int: ...
    @property
    def sync_unlocked_chans(self) -> list[str]: ...
    @property
    def sync_unlocked_chans_exist(self) -> bool: ...
    @property
    def total_samp_per_chan_generated(self) -> int: ...
    @property
    def wait_mode(self) -> WaitMode: ...
    @wait_mode.setter
    def wait_mode(self, val: WaitMode) -> None: ...
    @wait_mode.deleter
    def wait_mode(self) -> None: ...
    def write(self, numpy_array: ndarray) -> int: ...
    def get_channels_buffer_size(self) -> int: ...
