from types import TracebackType

from ..grpc_session_options import GrpcSessionOptions
from ..task.collections._ai_channel_collection import AIChannelCollection
from ..task.collections._di_channel_collection import DIChannelCollection
from ..task.collections._do_channel_collection import DOChannelCollection
from ..task._in_stream import InStream
from ..task._timing import Timing

class Task:
    def __init__(
        self, new_task_name: str = ..., *, grpc_options: GrpcSessionOptions | None = ...
    ) -> None: ...
    def __enter__(self) -> "Task": ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def close(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def ai_channels(self) -> AIChannelCollection: ...
    @property
    def di_channels(self) -> DIChannelCollection: ...
    @property
    def do_channels(self) -> DOChannelCollection: ...
    @property
    def in_stream(self) -> InStream: ...
    @property
    def timing(self) -> Timing: ...
