from ...constants import (
    Edge,
    Timescale,
    TriggerType,
    Level,
)
from ..._lib import TaskHandle
from ..._base_interpreter import BaseInterpreter
from datetime import datetime

class ArmStartTrigger:
    def __init__(
        self, task_handle: TaskHandle, interpreter: BaseInterpreter
    ) -> None: ...
    @property
    def dig_edge_dig_fltr_enable(self) -> bool: ...
    @dig_edge_dig_fltr_enable.setter
    def dig_edge_dig_fltr_enable(self, val: bool) -> None: ...
    @dig_edge_dig_fltr_enable.deleter
    def dig_edge_dig_fltr_enable(self) -> None: ...
    @property
    def dig_edge_dig_fltr_min_pulse_width(self) -> float: ...
    @dig_edge_dig_fltr_min_pulse_width.setter
    def dig_edge_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @dig_edge_dig_fltr_min_pulse_width.deleter
    def dig_edge_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def dig_edge_dig_fltr_timebase_rate(self) -> float: ...
    @dig_edge_dig_fltr_timebase_rate.setter
    def dig_edge_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @dig_edge_dig_fltr_timebase_rate.deleter
    def dig_edge_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def dig_edge_dig_fltr_timebase_src(self) -> str: ...
    @dig_edge_dig_fltr_timebase_src.setter
    def dig_edge_dig_fltr_timebase_src(self, val: str) -> None: ...
    @dig_edge_dig_fltr_timebase_src.deleter
    def dig_edge_dig_fltr_timebase_src(self) -> None: ...
    @property
    def dig_edge_dig_sync_enable(self) -> bool: ...
    @dig_edge_dig_sync_enable.setter
    def dig_edge_dig_sync_enable(self, val: bool) -> None: ...
    @dig_edge_dig_sync_enable.deleter
    def dig_edge_dig_sync_enable(self) -> None: ...
    @property
    def dig_edge_edge(self) -> Edge: ...
    @dig_edge_edge.setter
    def dig_edge_edge(self, val: Edge) -> None: ...
    @dig_edge_edge.deleter
    def dig_edge_edge(self) -> None: ...
    @property
    def dig_edge_src(self) -> str: ...
    @dig_edge_src.setter
    def dig_edge_src(self, val: str) -> None: ...
    @dig_edge_src.deleter
    def dig_edge_src(self) -> None: ...
    @property
    def term(self) -> str: ...
    @property
    def time_timescale(self) -> Timescale: ...
    @time_timescale.setter
    def time_timescale(self, val: Timescale) -> None: ...
    @time_timescale.deleter
    def time_timescale(self) -> None: ...
    @property
    def time_when(self) -> datetime: ...
    @time_when.setter
    def time_when(self, val: datetime) -> None: ...
    @time_when.deleter
    def time_when(self) -> None: ...
    @property
    def timestamp_enable(self) -> bool: ...
    @timestamp_enable.setter
    def timestamp_enable(self, val: bool) -> None: ...
    @timestamp_enable.deleter
    def timestamp_enable(self) -> None: ...
    @property
    def timestamp_timescale(self) -> Timescale: ...
    @timestamp_timescale.setter
    def timestamp_timescale(self, val: Timescale) -> None: ...
    @timestamp_timescale.deleter
    def timestamp_timescale(self) -> None: ...
    @property
    def timestamp_val(self) -> datetime: ...
    @property
    def trig_type(self) -> TriggerType: ...
    @trig_type.setter
    def trig_type(self, val: TriggerType) -> None: ...
    @trig_type.deleter
    def trig_type(self) -> None: ...

    from ...constants import Level, TriggerType

class HandshakeTrigger:
    def __init__(
        self, task_handle: TaskHandle, interpreter: BaseInterpreter
    ) -> None: ...
    @property
    def interlocked_asserted_lvl(self) -> Level: ...
    @interlocked_asserted_lvl.setter
    def interlocked_asserted_lvl(self, val: Level) -> None: ...
    @interlocked_asserted_lvl.deleter
    def interlocked_asserted_lvl(self) -> None: ...
    @property
    def interlocked_src(self) -> str: ...
    @interlocked_src.setter
    def interlocked_src(self, val: str) -> None: ...
    @interlocked_src.deleter
    def interlocked_src(self) -> None: ...
    @property
    def trig_type(self) -> TriggerType: ...
    @trig_type.setter
    def trig_type(self, val: TriggerType) -> None: ...
    @trig_type.deleter
    def trig_type(self) -> None: ...
