from ..._base_interpreter import BaseInterpreter
from ...system.physical_channel import PhysicalChannel
from ..._lib import TaskHandle
from ...constants import (
    ActiveLevel,
    Coupling,
    DigitalPatternCondition,
    Level,
    TriggerType,
    WindowTriggerCondition2,
)

class PauseTrigger:
    def __init__(
        self, task_handle: TaskHandle, interpreter: BaseInterpreter
    ) -> None: ...
    @property
    def anlg_lvl_coupling(self) -> Coupling: ...
    @anlg_lvl_coupling.setter
    def anlg_lvl_coupling(self, val: Coupling) -> None: ...
    @anlg_lvl_coupling.deleter
    def anlg_lvl_coupling(self) -> None: ...
    @property
    def anlg_lvl_dig_fltr_enable(self) -> bool: ...
    @anlg_lvl_dig_fltr_enable.setter
    def anlg_lvl_dig_fltr_enable(self, val: bool) -> None: ...
    @anlg_lvl_dig_fltr_enable.deleter
    def anlg_lvl_dig_fltr_enable(self) -> None: ...
    @property
    def anlg_lvl_dig_fltr_min_pulse_width(self) -> float: ...
    @anlg_lvl_dig_fltr_min_pulse_width.setter
    def anlg_lvl_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @anlg_lvl_dig_fltr_min_pulse_width.deleter
    def anlg_lvl_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def anlg_lvl_dig_fltr_timebase_rate(self) -> float: ...
    @anlg_lvl_dig_fltr_timebase_rate.setter
    def anlg_lvl_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @anlg_lvl_dig_fltr_timebase_rate.deleter
    def anlg_lvl_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def anlg_lvl_dig_fltr_timebase_src(self) -> str: ...
    @anlg_lvl_dig_fltr_timebase_src.setter
    def anlg_lvl_dig_fltr_timebase_src(self, val: str) -> None: ...
    @anlg_lvl_dig_fltr_timebase_src.deleter
    def anlg_lvl_dig_fltr_timebase_src(self) -> None: ...
    @property
    def anlg_lvl_dig_sync_enable(self) -> bool: ...
    @anlg_lvl_dig_sync_enable.setter
    def anlg_lvl_dig_sync_enable(self, val: bool) -> None: ...
    @anlg_lvl_dig_sync_enable.deleter
    def anlg_lvl_dig_sync_enable(self) -> None: ...
    @property
    def anlg_lvl_hyst(self) -> float: ...
    @anlg_lvl_hyst.setter
    def anlg_lvl_hyst(self, val: float) -> None: ...
    @anlg_lvl_hyst.deleter
    def anlg_lvl_hyst(self) -> None: ...
    @property
    def anlg_lvl_lvl(self) -> float: ...
    @anlg_lvl_lvl.setter
    def anlg_lvl_lvl(self, val: float) -> None: ...
    @anlg_lvl_lvl.deleter
    def anlg_lvl_lvl(self) -> None: ...
    @property
    def anlg_lvl_src(self) -> str: ...
    @anlg_lvl_src.setter
    def anlg_lvl_src(self, val: str) -> None: ...
    @anlg_lvl_src.deleter
    def anlg_lvl_src(self) -> None: ...
    @property
    def anlg_lvl_when(self) -> ActiveLevel: ...
    @anlg_lvl_when.setter
    def anlg_lvl_when(self, val: ActiveLevel) -> None: ...
    @anlg_lvl_when.deleter
    def anlg_lvl_when(self) -> None: ...
    @property
    def anlg_win_btm(self) -> float: ...
    @anlg_win_btm.setter
    def anlg_win_btm(self, val: float) -> None: ...
    @anlg_win_btm.deleter
    def anlg_win_btm(self) -> None: ...
    @property
    def anlg_win_coupling(self) -> Coupling: ...
    @anlg_win_coupling.setter
    def anlg_win_coupling(self, val: Coupling) -> None: ...
    @anlg_win_coupling.deleter
    def anlg_win_coupling(self) -> None: ...
    @property
    def anlg_win_dig_fltr_enable(self) -> bool: ...
    @anlg_win_dig_fltr_enable.setter
    def anlg_win_dig_fltr_enable(self, val: bool) -> None: ...
    @anlg_win_dig_fltr_enable.deleter
    def anlg_win_dig_fltr_enable(self) -> None: ...
    @property
    def anlg_win_dig_fltr_min_pulse_width(self) -> float: ...
    @anlg_win_dig_fltr_min_pulse_width.setter
    def anlg_win_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @anlg_win_dig_fltr_min_pulse_width.deleter
    def anlg_win_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def anlg_win_dig_fltr_timebase_rate(self) -> float: ...
    @anlg_win_dig_fltr_timebase_rate.setter
    def anlg_win_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @anlg_win_dig_fltr_timebase_rate.deleter
    def anlg_win_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def anlg_win_dig_fltr_timebase_src(self) -> str: ...
    @anlg_win_dig_fltr_timebase_src.setter
    def anlg_win_dig_fltr_timebase_src(self, val: str) -> None: ...
    @anlg_win_dig_fltr_timebase_src.deleter
    def anlg_win_dig_fltr_timebase_src(self) -> None: ...
    @property
    def anlg_win_dig_sync_enable(self) -> bool: ...
    @anlg_win_dig_sync_enable.setter
    def anlg_win_dig_sync_enable(self, val: bool) -> None: ...
    @anlg_win_dig_sync_enable.deleter
    def anlg_win_dig_sync_enable(self) -> None: ...
    @property
    def anlg_win_src(self) -> str: ...
    @anlg_win_src.setter
    def anlg_win_src(self, val: str) -> None: ...
    @anlg_win_src.deleter
    def anlg_win_src(self) -> None: ...
    @property
    def anlg_win_top(self) -> float: ...
    @anlg_win_top.setter
    def anlg_win_top(self, val: float) -> None: ...
    @anlg_win_top.deleter
    def anlg_win_top(self) -> None: ...
    @property
    def anlg_win_when(self) -> WindowTriggerCondition2: ...
    @anlg_win_when.setter
    def anlg_win_when(self, val: WindowTriggerCondition2) -> None: ...
    @anlg_win_when.deleter
    def anlg_win_when(self) -> None: ...
    @property
    def dig_lvl_dig_fltr_enable(self) -> bool: ...
    @dig_lvl_dig_fltr_enable.setter
    def dig_lvl_dig_fltr_enable(self, val: bool) -> None: ...
    @dig_lvl_dig_fltr_enable.deleter
    def dig_lvl_dig_fltr_enable(self) -> None: ...
    @property
    def dig_lvl_dig_fltr_min_pulse_width(self) -> float: ...
    @dig_lvl_dig_fltr_min_pulse_width.setter
    def dig_lvl_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @dig_lvl_dig_fltr_min_pulse_width.deleter
    def dig_lvl_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def dig_lvl_dig_fltr_timebase_rate(self) -> float: ...
    @dig_lvl_dig_fltr_timebase_rate.setter
    def dig_lvl_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @dig_lvl_dig_fltr_timebase_rate.deleter
    def dig_lvl_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def dig_lvl_dig_fltr_timebase_src(self) -> str: ...
    @dig_lvl_dig_fltr_timebase_src.setter
    def dig_lvl_dig_fltr_timebase_src(self, val: str) -> None: ...
    @dig_lvl_dig_fltr_timebase_src.deleter
    def dig_lvl_dig_fltr_timebase_src(self) -> None: ...
    @property
    def dig_lvl_dig_sync_enable(self) -> bool: ...
    @dig_lvl_dig_sync_enable.setter
    def dig_lvl_dig_sync_enable(self, val: bool) -> None: ...
    @dig_lvl_dig_sync_enable.deleter
    def dig_lvl_dig_sync_enable(self) -> None: ...
    @property
    def dig_lvl_src(self) -> str: ...
    @dig_lvl_src.setter
    def dig_lvl_src(self, val: str) -> None: ...
    @dig_lvl_src.deleter
    def dig_lvl_src(self) -> None: ...
    @property
    def dig_lvl_when(self) -> Level: ...
    @dig_lvl_when.setter
    def dig_lvl_when(self, val: Level) -> None: ...
    @dig_lvl_when.deleter
    def dig_lvl_when(self) -> None: ...
    @property
    def dig_pattern_pattern(self) -> str: ...
    @dig_pattern_pattern.setter
    def dig_pattern_pattern(self, val: str) -> None: ...
    @dig_pattern_pattern.deleter
    def dig_pattern_pattern(self) -> None: ...
    @property
    def dig_pattern_src(self) -> PhysicalChannel: ...
    @dig_pattern_src.setter
    def dig_pattern_src(self, val: PhysicalChannel) -> None: ...
    @dig_pattern_src.deleter
    def dig_pattern_src(self) -> None: ...
    @property
    def dig_pattern_when(self) -> DigitalPatternCondition: ...
    @dig_pattern_when.setter
    def dig_pattern_when(self, val: DigitalPatternCondition) -> None: ...
    @dig_pattern_when.deleter
    def dig_pattern_when(self) -> None: ...
    @property
    def term(self) -> str: ...
    @property
    def trig_type(self) -> TriggerType: ...
    @trig_type.setter
    def trig_type(self, val: TriggerType) -> None: ...
    @trig_type.deleter
    def trig_type(self) -> None: ...
