from datetime import datetime
from ..._base_interpreter import BaseInterpreter
from ...system.physical_channel import PhysicalChannel
from ..._lib import TaskHandle
from ...constants import (
    Coupling,
    DigitalPatternCondition,
    Edge,
    Slope,
    Timescale,
    TriggerType,
    WindowTriggerCondition1,
)

class ReferenceTrigger:
    def __init__(
        self, task_handle: TaskHandle, interpreter: BaseInterpreter
    ) -> None: ...
    @property
    def anlg_edge_coupling(self) -> Coupling: ...
    @anlg_edge_coupling.setter
    def anlg_edge_coupling(self, val: Coupling) -> None: ...
    @anlg_edge_coupling.deleter
    def anlg_edge_coupling(self) -> None: ...
    @property
    def anlg_edge_dig_fltr_enable(self) -> bool: ...
    @anlg_edge_dig_fltr_enable.setter
    def anlg_edge_dig_fltr_enable(self, val: bool) -> None: ...
    @anlg_edge_dig_fltr_enable.deleter
    def anlg_edge_dig_fltr_enable(self) -> None: ...
    @property
    def anlg_edge_dig_fltr_min_pulse_width(self) -> float: ...
    @anlg_edge_dig_fltr_min_pulse_width.setter
    def anlg_edge_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @anlg_edge_dig_fltr_min_pulse_width.deleter
    def anlg_edge_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def anlg_edge_dig_fltr_timebase_rate(self) -> float: ...
    @anlg_edge_dig_fltr_timebase_rate.setter
    def anlg_edge_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @anlg_edge_dig_fltr_timebase_rate.deleter
    def anlg_edge_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def anlg_edge_dig_fltr_timebase_src(self) -> str: ...
    @anlg_edge_dig_fltr_timebase_src.setter
    def anlg_edge_dig_fltr_timebase_src(self, val: str) -> None: ...
    @anlg_edge_dig_fltr_timebase_src.deleter
    def anlg_edge_dig_fltr_timebase_src(self) -> None: ...
    @property
    def anlg_edge_dig_sync_enable(self) -> bool: ...
    @anlg_edge_dig_sync_enable.setter
    def anlg_edge_dig_sync_enable(self, val: bool) -> None: ...
    @anlg_edge_dig_sync_enable.deleter
    def anlg_edge_dig_sync_enable(self) -> None: ...
    @property
    def anlg_edge_hyst(self) -> float: ...
    @anlg_edge_hyst.setter
    def anlg_edge_hyst(self, val: float) -> None: ...
    @anlg_edge_hyst.deleter
    def anlg_edge_hyst(self) -> None: ...
    @property
    def anlg_edge_lvl(self) -> float: ...
    @anlg_edge_lvl.setter
    def anlg_edge_lvl(self, val: float) -> None: ...
    @anlg_edge_lvl.deleter
    def anlg_edge_lvl(self) -> None: ...
    @property
    def anlg_edge_slope(self) -> Slope: ...
    @anlg_edge_slope.setter
    def anlg_edge_slope(self, val: Slope) -> None: ...
    @anlg_edge_slope.deleter
    def anlg_edge_slope(self) -> None: ...
    @property
    def anlg_edge_src(self) -> str: ...
    @anlg_edge_src.setter
    def anlg_edge_src(self, val: str) -> None: ...
    @anlg_edge_src.deleter
    def anlg_edge_src(self) -> None: ...
    @property
    def anlg_multi_edge_couplings(self) -> Coupling: ...
    @anlg_multi_edge_couplings.setter
    def anlg_multi_edge_couplings(self, val: Coupling) -> None: ...
    @anlg_multi_edge_couplings.deleter
    def anlg_multi_edge_couplings(self) -> None: ...
    @property
    def anlg_multi_edge_hysts(self) -> list[float]: ...
    @anlg_multi_edge_hysts.setter
    def anlg_multi_edge_hysts(self, val: list[float]) -> None: ...
    @anlg_multi_edge_hysts.deleter
    def anlg_multi_edge_hysts(self) -> None: ...
    @property
    def anlg_multi_edge_lvls(self) -> list[float]: ...
    @anlg_multi_edge_lvls.setter
    def anlg_multi_edge_lvls(self, val: list[float]) -> None: ...
    @anlg_multi_edge_lvls.deleter
    def anlg_multi_edge_lvls(self) -> None: ...
    @property
    def anlg_multi_edge_slopes(self) -> Slope: ...
    @anlg_multi_edge_slopes.setter
    def anlg_multi_edge_slopes(self, val: Slope) -> None: ...
    @anlg_multi_edge_slopes.deleter
    def anlg_multi_edge_slopes(self) -> None: ...
    @property
    def anlg_multi_edge_srcs(self) -> str: ...
    @anlg_multi_edge_srcs.setter
    def anlg_multi_edge_srcs(self, val: str) -> None: ...
    @anlg_multi_edge_srcs.deleter
    def anlg_multi_edge_srcs(self) -> None: ...
    @property
    def anlg_win_btm(self) -> float: ...
    @anlg_win_btm.setter
    def anlg_win_btm(self, val: float) -> None: ...
    @anlg_win_btm.deleter
    def anlg_win_btm(self) -> None: ...
    @property
    def anlg_win_coupling(self) -> Coupling: ...
    @anlg_win_coupling.setter
    def anlg_win_coupling(self, val: Coupling) -> None: ...
    @anlg_win_coupling.deleter
    def anlg_win_coupling(self) -> None: ...
    @property
    def anlg_win_dig_fltr_enable(self) -> bool: ...
    @anlg_win_dig_fltr_enable.setter
    def anlg_win_dig_fltr_enable(self, val: bool) -> None: ...
    @anlg_win_dig_fltr_enable.deleter
    def anlg_win_dig_fltr_enable(self) -> None: ...
    @property
    def anlg_win_dig_fltr_min_pulse_width(self) -> float: ...
    @anlg_win_dig_fltr_min_pulse_width.setter
    def anlg_win_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @anlg_win_dig_fltr_min_pulse_width.deleter
    def anlg_win_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def anlg_win_dig_fltr_timebase_rate(self) -> float: ...
    @anlg_win_dig_fltr_timebase_rate.setter
    def anlg_win_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @anlg_win_dig_fltr_timebase_rate.deleter
    def anlg_win_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def anlg_win_dig_fltr_timebase_src(self) -> str: ...
    @anlg_win_dig_fltr_timebase_src.setter
    def anlg_win_dig_fltr_timebase_src(self, val: str) -> None: ...
    @anlg_win_dig_fltr_timebase_src.deleter
    def anlg_win_dig_fltr_timebase_src(self) -> None: ...
    @property
    def anlg_win_dig_sync_enable(self) -> bool: ...
    @anlg_win_dig_sync_enable.setter
    def anlg_win_dig_sync_enable(self, val: bool) -> None: ...
    @anlg_win_dig_sync_enable.deleter
    def anlg_win_dig_sync_enable(self) -> None: ...
    @property
    def anlg_win_src(self) -> str: ...
    @anlg_win_src.setter
    def anlg_win_src(self, val: str) -> None: ...
    @anlg_win_src.deleter
    def anlg_win_src(self) -> None: ...
    @property
    def anlg_win_top(self) -> float: ...
    @anlg_win_top.setter
    def anlg_win_top(self, val: float) -> None: ...
    @anlg_win_top.deleter
    def anlg_win_top(self) -> None: ...
    @property
    def anlg_win_trig_when(self) -> WindowTriggerCondition1: ...
    @anlg_win_trig_when.setter
    def anlg_win_trig_when(self, val: WindowTriggerCondition1) -> None: ...
    @anlg_win_trig_when.deleter
    def anlg_win_trig_when(self) -> None: ...
    @property
    def auto_trig_enable(self) -> bool: ...
    @auto_trig_enable.setter
    def auto_trig_enable(self, val: bool) -> None: ...
    @auto_trig_enable.deleter
    def auto_trig_enable(self) -> None: ...
    @property
    def auto_triggered(self) -> bool: ...
    @property
    def delay(self) -> float: ...
    @delay.setter
    def delay(self, val: float) -> None: ...
    @delay.deleter
    def delay(self) -> None: ...
    @property
    def dig_edge_dig_fltr_enable(self) -> bool: ...
    @dig_edge_dig_fltr_enable.setter
    def dig_edge_dig_fltr_enable(self, val: bool) -> None: ...
    @dig_edge_dig_fltr_enable.deleter
    def dig_edge_dig_fltr_enable(self) -> None: ...
    @property
    def dig_edge_dig_fltr_min_pulse_width(self) -> float: ...
    @dig_edge_dig_fltr_min_pulse_width.setter
    def dig_edge_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @dig_edge_dig_fltr_min_pulse_width.deleter
    def dig_edge_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def dig_edge_dig_fltr_timebase_rate(self) -> float: ...
    @dig_edge_dig_fltr_timebase_rate.setter
    def dig_edge_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @dig_edge_dig_fltr_timebase_rate.deleter
    def dig_edge_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def dig_edge_dig_fltr_timebase_src(self) -> str: ...
    @dig_edge_dig_fltr_timebase_src.setter
    def dig_edge_dig_fltr_timebase_src(self, val: str) -> None: ...
    @dig_edge_dig_fltr_timebase_src.deleter
    def dig_edge_dig_fltr_timebase_src(self) -> None: ...
    @property
    def dig_edge_dig_sync_enable(self) -> bool: ...
    @dig_edge_dig_sync_enable.setter
    def dig_edge_dig_sync_enable(self, val: bool) -> None: ...
    @dig_edge_dig_sync_enable.deleter
    def dig_edge_dig_sync_enable(self) -> None: ...
    @property
    def dig_edge_edge(self) -> Edge: ...
    @dig_edge_edge.setter
    def dig_edge_edge(self, val: Edge) -> None: ...
    @dig_edge_edge.deleter
    def dig_edge_edge(self) -> None: ...
    @property
    def dig_edge_src(self) -> str: ...
    @dig_edge_src.setter
    def dig_edge_src(self, val: str) -> None: ...
    @dig_edge_src.deleter
    def dig_edge_src(self) -> None: ...
    @property
    def dig_pattern_pattern(self) -> str: ...
    @dig_pattern_pattern.setter
    def dig_pattern_pattern(self, val: str) -> None: ...
    @dig_pattern_pattern.deleter
    def dig_pattern_pattern(self) -> None: ...
    @property
    def dig_pattern_src(self) -> PhysicalChannel: ...
    @dig_pattern_src.setter
    def dig_pattern_src(self, val: PhysicalChannel) -> None: ...
    @dig_pattern_src.deleter
    def dig_pattern_src(self) -> None: ...
    @property
    def dig_pattern_trig_when(self) -> DigitalPatternCondition: ...
    @dig_pattern_trig_when.setter
    def dig_pattern_trig_when(self, val: DigitalPatternCondition) -> None: ...
    @dig_pattern_trig_when.deleter
    def dig_pattern_trig_when(self) -> None: ...
    @property
    def max_num_trigs_to_detect(self) -> int: ...
    @max_num_trigs_to_detect.setter
    def max_num_trigs_to_detect(self, val: int) -> None: ...
    @max_num_trigs_to_detect.deleter
    def max_num_trigs_to_detect(self) -> None: ...
    @property
    def pretrig_samples(self) -> int: ...
    @pretrig_samples.setter
    def pretrig_samples(self, val: int) -> None: ...
    @pretrig_samples.deleter
    def pretrig_samples(self) -> None: ...
    @property
    def retrigger_win(self) -> float: ...
    @retrigger_win.setter
    def retrigger_win(self, val: float) -> None: ...
    @retrigger_win.deleter
    def retrigger_win(self) -> None: ...
    @property
    def retriggerable(self) -> bool: ...
    @retriggerable.setter
    def retriggerable(self, val: bool) -> None: ...
    @retriggerable.deleter
    def retriggerable(self) -> None: ...
    @property
    def term(self) -> str: ...
    @property
    def timestamp_enable(self) -> bool: ...
    @timestamp_enable.setter
    def timestamp_enable(self, val: bool) -> None: ...
    @timestamp_enable.deleter
    def timestamp_enable(self) -> None: ...
    @property
    def timestamp_timescale(self) -> Timescale: ...
    @timestamp_timescale.setter
    def timestamp_timescale(self, val: Timescale) -> None: ...
    @timestamp_timescale.deleter
    def timestamp_timescale(self) -> None: ...
    @property
    def timestamp_val(self) -> datetime: ...
    @property
    def trig_type(self) -> TriggerType: ...
    @trig_type.setter
    def trig_type(self, val: TriggerType) -> None: ...
    @trig_type.deleter
    def trig_type(self) -> None: ...
    @property
    def trig_win(self) -> float: ...
    @trig_win.setter
    def trig_win(self, val: float) -> None: ...
    @trig_win.deleter
    def trig_win(self) -> None: ...
    def cfg_anlg_edge_ref_trig(
        self,
        trigger_source: str,
        pretrigger_samples: int,
        trigger_slope: Slope = Slope.RISING,
        trigger_level: float = 0.0,
    ) -> None: ...
    def cfg_anlg_multi_edge_ref_trig(
        self,
        trigger_sources: str,
        pretrigger_samples: int,
        trigger_slope_array: list[Slope] | None = None,
        trigger_level_array: list[float] | None = None,
    ) -> None: ...
    def cfg_anlg_window_ref_trig(
        self,
        trigger_source: str,
        window_top: float,
        window_bottom: float,
        pretrigger_samples: int,
        trigger_when: WindowTriggerCondition1 = WindowTriggerCondition1.ENTERING_WINDOW,
    ) -> None: ...
    def cfg_dig_edge_ref_trig(
        self,
        trigger_source: str,
        pretrigger_samples: int,
        trigger_edge: Edge = Edge.RISING,
    ) -> None: ...
    def cfg_dig_pattern_ref_trig(
        self,
        trigger_source: str,
        trigger_pattern: str,
        pretrigger_samples: int,
        trigger_when: DigitalPatternCondition = DigitalPatternCondition.PATTERN_MATCHES,
    ) -> None: ...
    def disable_ref_trig(self) -> None: ...
