from ...constants import (
    ActiveOrInactiveEdgeSelection,
    DataTransferActiveTransferMode,
    InputDataTransferCondition,
    LogicFamily,
)
from ._channel import Channel

class DIChannel(Channel):
    def __repr__(self) -> str: ...
    @property
    def di_acquire_on(self) -> ActiveOrInactiveEdgeSelection: ...
    @di_acquire_on.setter
    def di_acquire_on(self, val: ActiveOrInactiveEdgeSelection) -> None: ...
    @di_acquire_on.deleter
    def di_acquire_on(self) -> None: ...
    @property
    def di_data_xfer_mech(self) -> DataTransferActiveTransferMode: ...
    @di_data_xfer_mech.setter
    def di_data_xfer_mech(self, val: DataTransferActiveTransferMode) -> None: ...
    @di_data_xfer_mech.deleter
    def di_data_xfer_mech(self) -> None: ...
    @property
    def di_data_xfer_req_cond(self) -> InputDataTransferCondition: ...
    @di_data_xfer_req_cond.setter
    def di_data_xfer_req_cond(self, val: InputDataTransferCondition) -> None: ...
    @di_data_xfer_req_cond.deleter
    def di_data_xfer_req_cond(self) -> None: ...
    @property
    def di_dig_fltr_enable(self) -> bool: ...
    @di_dig_fltr_enable.setter
    def di_dig_fltr_enable(self, val: bool) -> None: ...
    @di_dig_fltr_enable.deleter
    def di_dig_fltr_enable(self) -> None: ...
    @property
    def di_dig_fltr_enable_bus_mode(self) -> bool: ...
    @di_dig_fltr_enable_bus_mode.setter
    def di_dig_fltr_enable_bus_mode(self, val: bool) -> None: ...
    @di_dig_fltr_enable_bus_mode.deleter
    def di_dig_fltr_enable_bus_mode(self) -> None: ...
    @property
    def di_dig_fltr_min_pulse_width(self) -> float: ...
    @di_dig_fltr_min_pulse_width.setter
    def di_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @di_dig_fltr_min_pulse_width.deleter
    def di_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def di_dig_fltr_timebase_rate(self) -> float: ...
    @di_dig_fltr_timebase_rate.setter
    def di_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @di_dig_fltr_timebase_rate.deleter
    def di_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def di_dig_fltr_timebase_src(self) -> str: ...
    @di_dig_fltr_timebase_src.setter
    def di_dig_fltr_timebase_src(self, val: str) -> None: ...
    @di_dig_fltr_timebase_src.deleter
    def di_dig_fltr_timebase_src(self) -> None: ...
    @property
    def di_dig_sync_enable(self) -> bool: ...
    @di_dig_sync_enable.setter
    def di_dig_sync_enable(self, val: bool) -> None: ...
    @di_dig_sync_enable.deleter
    def di_dig_sync_enable(self) -> None: ...
    @property
    def di_invert_lines(self) -> bool: ...
    @di_invert_lines.setter
    def di_invert_lines(self, val: bool) -> None: ...
    @di_invert_lines.deleter
    def di_invert_lines(self) -> None: ...
    @property
    def di_logic_family(self) -> LogicFamily: ...
    @di_logic_family.setter
    def di_logic_family(self, val: LogicFamily) -> None: ...
    @di_logic_family.deleter
    def di_logic_family(self) -> None: ...
    @property
    def di_mem_map_enable(self) -> bool: ...
    @di_mem_map_enable.setter
    def di_mem_map_enable(self, val: bool) -> None: ...
    @di_mem_map_enable.deleter
    def di_mem_map_enable(self) -> None: ...
    @property
    def di_num_lines(self) -> int: ...
    @property
    def di_tristate(self) -> bool: ...
    @di_tristate.setter
    def di_tristate(self, val: bool) -> None: ...
    @di_tristate.deleter
    def di_tristate(self) -> None: ...
    @property
    def di_usb_xfer_req_count(self) -> int: ...
    @di_usb_xfer_req_count.setter
    def di_usb_xfer_req_count(self, val: int) -> None: ...
    @di_usb_xfer_req_count.deleter
    def di_usb_xfer_req_count(self) -> None: ...
    @property
    def di_usb_xfer_req_size(self) -> int: ...
    @di_usb_xfer_req_size.setter
    def di_usb_xfer_req_size(self, val: int) -> None: ...
    @di_usb_xfer_req_size.deleter
    def di_usb_xfer_req_size(self) -> None: ...
