from typing import NoReturn
from datetime import datetime
from ..system.physical_channel import PhysicalChannel
from ..system.device import Device
from .._base_interpreter import BaseInterpreter
from .._lib import TaskHandle
from ..constants import (
    AcquisitionType,
    DigitalWidthUnits,
    Edge,
    HandshakeStartCondition,
    Level,
    MIOAIConvertTimebaseSource,
    OverflowBehavior,
    Polarity,
    SampleInputDataWhen,
    SampleTimingType,
    SyncPulseType,
    Timescale,
    UnderflowBehavior,
)

class Timing:
    def __init__(
        self,
        task_handle: TaskHandle,
        interpreter: BaseInterpreter,
        active_devs: str | Device | None = None,
    ) -> None: ...
    def __getitem__(self, dev: str | Device) -> Timing: ...
    def _raise_device_context_not_supported_error(self) -> NoReturn: ...
    @property
    def ai_conv_active_edge(self) -> Edge: ...
    @ai_conv_active_edge.setter
    def ai_conv_active_edge(self, val: Edge) -> None: ...
    @ai_conv_active_edge.deleter
    def ai_conv_active_edge(self) -> None: ...
    @property
    def ai_conv_dig_fltr_enable(self) -> bool: ...
    @ai_conv_dig_fltr_enable.setter
    def ai_conv_dig_fltr_enable(self, val: bool) -> None: ...
    @ai_conv_dig_fltr_enable.deleter
    def ai_conv_dig_fltr_enable(self) -> None: ...
    @property
    def ai_conv_dig_fltr_min_pulse_width(self) -> float: ...
    @ai_conv_dig_fltr_min_pulse_width.setter
    def ai_conv_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @ai_conv_dig_fltr_min_pulse_width.deleter
    def ai_conv_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def ai_conv_dig_fltr_timebase_rate(self) -> float: ...
    @ai_conv_dig_fltr_timebase_rate.setter
    def ai_conv_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @ai_conv_dig_fltr_timebase_rate.deleter
    def ai_conv_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def ai_conv_dig_fltr_timebase_src(self) -> str: ...
    @ai_conv_dig_fltr_timebase_src.setter
    def ai_conv_dig_fltr_timebase_src(self, val: str) -> None: ...
    @ai_conv_dig_fltr_timebase_src.deleter
    def ai_conv_dig_fltr_timebase_src(self) -> None: ...
    @property
    def ai_conv_dig_sync_enable(self) -> bool: ...
    @ai_conv_dig_sync_enable.setter
    def ai_conv_dig_sync_enable(self, val: bool) -> None: ...
    @ai_conv_dig_sync_enable.deleter
    def ai_conv_dig_sync_enable(self) -> None: ...
    @property
    def ai_conv_max_rate(self) -> float: ...
    @property
    def ai_conv_rate(self) -> float: ...
    @ai_conv_rate.setter
    def ai_conv_rate(self, val: float) -> None: ...
    @ai_conv_rate.deleter
    def ai_conv_rate(self) -> None: ...
    @property
    def ai_conv_src(self) -> str: ...
    @ai_conv_src.setter
    def ai_conv_src(self, val: str) -> None: ...
    @ai_conv_src.deleter
    def ai_conv_src(self) -> None: ...
    @property
    def ai_conv_timebase_div(self) -> int: ...
    @ai_conv_timebase_div.setter
    def ai_conv_timebase_div(self, val: int) -> None: ...
    @ai_conv_timebase_div.deleter
    def ai_conv_timebase_div(self) -> None: ...
    @property
    def ai_conv_timebase_src(self) -> MIOAIConvertTimebaseSource: ...
    @ai_conv_timebase_src.setter
    def ai_conv_timebase_src(self, val: MIOAIConvertTimebaseSource) -> None: ...
    @ai_conv_timebase_src.deleter
    def ai_conv_timebase_src(self) -> None: ...
    @property
    def change_detect_di_falling_edge_physical_chans(self) -> PhysicalChannel: ...
    @change_detect_di_falling_edge_physical_chans.setter
    def change_detect_di_falling_edge_physical_chans(
        self, val: PhysicalChannel
    ) -> None: ...
    @change_detect_di_falling_edge_physical_chans.deleter
    def change_detect_di_falling_edge_physical_chans(self) -> None: ...
    @property
    def change_detect_di_rising_edge_physical_chans(self) -> PhysicalChannel: ...
    @change_detect_di_rising_edge_physical_chans.setter
    def change_detect_di_rising_edge_physical_chans(
        self, val: PhysicalChannel
    ) -> None: ...
    @change_detect_di_rising_edge_physical_chans.deleter
    def change_detect_di_rising_edge_physical_chans(self) -> None: ...
    @property
    def change_detect_di_tristate(self) -> bool: ...
    @change_detect_di_tristate.setter
    def change_detect_di_tristate(self, val: bool) -> None: ...
    @change_detect_di_tristate.deleter
    def change_detect_di_tristate(self) -> None: ...
    @property
    def delay_from_samp_clk_delay(self) -> float: ...
    @delay_from_samp_clk_delay.setter
    def delay_from_samp_clk_delay(self, val: float) -> None: ...
    @delay_from_samp_clk_delay.deleter
    def delay_from_samp_clk_delay(self) -> None: ...
    @property
    def delay_from_samp_clk_delay_units(self) -> DigitalWidthUnits: ...
    @delay_from_samp_clk_delay_units.setter
    def delay_from_samp_clk_delay_units(self, val: DigitalWidthUnits) -> None: ...
    @delay_from_samp_clk_delay_units.deleter
    def delay_from_samp_clk_delay_units(self) -> None: ...
    @property
    def first_samp_clk_offset(self) -> float: ...
    @first_samp_clk_offset.setter
    def first_samp_clk_offset(self, val: float) -> None: ...
    @first_samp_clk_offset.deleter
    def first_samp_clk_offset(self) -> None: ...
    @property
    def first_samp_clk_timescale(self) -> Timescale: ...
    @first_samp_clk_timescale.setter
    def first_samp_clk_timescale(self, val: Timescale) -> None: ...
    @first_samp_clk_timescale.deleter
    def first_samp_clk_timescale(self) -> None: ...
    @property
    def first_samp_clk_when(self) -> datetime: ...
    @first_samp_clk_when.setter
    def first_samp_clk_when(self, val: datetime) -> None: ...
    @first_samp_clk_when.deleter
    def first_samp_clk_when(self) -> None: ...
    @property
    def first_samp_timestamp_enable(self) -> bool: ...
    @first_samp_timestamp_enable.setter
    def first_samp_timestamp_enable(self, val: bool) -> None: ...
    @first_samp_timestamp_enable.deleter
    def first_samp_timestamp_enable(self) -> None: ...
    @property
    def first_samp_timestamp_timescale(self) -> Timescale: ...
    @first_samp_timestamp_timescale.setter
    def first_samp_timestamp_timescale(self, val: Timescale) -> None: ...
    @first_samp_timestamp_timescale.deleter
    def first_samp_timestamp_timescale(self) -> None: ...
    @property
    def first_samp_timestamp_val(self) -> datetime: ...
    @property
    def hshk_delay_after_xfer(self) -> float: ...
    @hshk_delay_after_xfer.setter
    def hshk_delay_after_xfer(self, val: float) -> None: ...
    @hshk_delay_after_xfer.deleter
    def hshk_delay_after_xfer(self) -> None: ...
    @property
    def hshk_sample_input_data_when(self) -> SampleInputDataWhen: ...
    @hshk_sample_input_data_when.setter
    def hshk_sample_input_data_when(self, val: SampleInputDataWhen) -> None: ...
    @hshk_sample_input_data_when.deleter
    def hshk_sample_input_data_when(self) -> None: ...
    @property
    def hshk_start_cond(self) -> HandshakeStartCondition: ...
    @hshk_start_cond.setter
    def hshk_start_cond(self, val: HandshakeStartCondition) -> None: ...
    @hshk_start_cond.deleter
    def hshk_start_cond(self) -> None: ...
    @property
    def implicit_underflow_behavior(self) -> UnderflowBehavior: ...
    @implicit_underflow_behavior.setter
    def implicit_underflow_behavior(self, val: UnderflowBehavior) -> None: ...
    @implicit_underflow_behavior.deleter
    def implicit_underflow_behavior(self) -> None: ...
    @property
    def master_timebase_rate(self) -> float: ...
    @master_timebase_rate.setter
    def master_timebase_rate(self, val: float) -> None: ...
    @master_timebase_rate.deleter
    def master_timebase_rate(self) -> None: ...
    @property
    def master_timebase_src(self) -> str: ...
    @master_timebase_src.setter
    def master_timebase_src(self, val: str) -> None: ...
    @master_timebase_src.deleter
    def master_timebase_src(self) -> None: ...
    @property
    def ref_clk_rate(self) -> float: ...
    @ref_clk_rate.setter
    def ref_clk_rate(self, val: float) -> None: ...
    @ref_clk_rate.deleter
    def ref_clk_rate(self) -> None: ...
    @property
    def ref_clk_src(self) -> str: ...
    @ref_clk_src.setter
    def ref_clk_src(self, val: str) -> None: ...
    @ref_clk_src.deleter
    def ref_clk_src(self) -> None: ...
    @property
    def samp_clk_active_edge(self) -> Edge: ...
    @samp_clk_active_edge.setter
    def samp_clk_active_edge(self, val: Edge) -> None: ...
    @samp_clk_active_edge.deleter
    def samp_clk_active_edge(self) -> None: ...
    @property
    def samp_clk_dig_fltr_enable(self) -> bool: ...
    @samp_clk_dig_fltr_enable.setter
    def samp_clk_dig_fltr_enable(self, val: bool) -> None: ...
    @samp_clk_dig_fltr_enable.deleter
    def samp_clk_dig_fltr_enable(self) -> None: ...
    @property
    def samp_clk_dig_fltr_min_pulse_width(self) -> float: ...
    @samp_clk_dig_fltr_min_pulse_width.setter
    def samp_clk_dig_fltr_min_pulse_width(self, val: float) -> None: ...
    @samp_clk_dig_fltr_min_pulse_width.deleter
    def samp_clk_dig_fltr_min_pulse_width(self) -> None: ...
    @property
    def samp_clk_dig_fltr_timebase_rate(self) -> float: ...
    @samp_clk_dig_fltr_timebase_rate.setter
    def samp_clk_dig_fltr_timebase_rate(self, val: float) -> None: ...
    @samp_clk_dig_fltr_timebase_rate.deleter
    def samp_clk_dig_fltr_timebase_rate(self) -> None: ...
    @property
    def samp_clk_dig_fltr_timebase_src(self) -> str: ...
    @samp_clk_dig_fltr_timebase_src.setter
    def samp_clk_dig_fltr_timebase_src(self, val: str) -> None: ...
    @samp_clk_dig_fltr_timebase_src.deleter
    def samp_clk_dig_fltr_timebase_src(self) -> None: ...
    @property
    def samp_clk_dig_sync_enable(self) -> bool: ...
    @samp_clk_dig_sync_enable.setter
    def samp_clk_dig_sync_enable(self, val: bool) -> None: ...
    @samp_clk_dig_sync_enable.deleter
    def samp_clk_dig_sync_enable(self) -> None: ...
    @property
    def samp_clk_max_rate(self) -> float: ...
    @property
    def samp_clk_overrun_behavior(self) -> OverflowBehavior: ...
    @samp_clk_overrun_behavior.setter
    def samp_clk_overrun_behavior(self, val: OverflowBehavior) -> None: ...
    @samp_clk_overrun_behavior.deleter
    def samp_clk_overrun_behavior(self) -> None: ...
    @property
    def samp_clk_rate(self) -> float: ...
    @samp_clk_rate.setter
    def samp_clk_rate(self, val: float) -> None: ...
    @samp_clk_rate.deleter
    def samp_clk_rate(self) -> None: ...
    @property
    def samp_clk_src(self) -> str: ...
    @samp_clk_src.setter
    def samp_clk_src(self, val: str) -> None: ...
    @samp_clk_src.deleter
    def samp_clk_src(self) -> None: ...
    @property
    def samp_clk_term(self) -> str: ...
    @property
    def samp_clk_timebase_active_edge(self) -> Edge: ...
    @samp_clk_timebase_active_edge.setter
    def samp_clk_timebase_active_edge(self, val: Edge) -> None: ...
    @samp_clk_timebase_active_edge.deleter
    def samp_clk_timebase_active_edge(self) -> None: ...
    @property
    def samp_clk_timebase_div(self) -> int: ...
    @samp_clk_timebase_div.setter
    def samp_clk_timebase_div(self, val: int) -> None: ...
    @samp_clk_timebase_div.deleter
    def samp_clk_timebase_div(self) -> None: ...
    @property
    def samp_clk_timebase_master_timebase_div(self) -> int: ...
    @samp_clk_timebase_master_timebase_div.setter
    def samp_clk_timebase_master_timebase_div(self, val: int) -> None: ...
    @samp_clk_timebase_master_timebase_div.deleter
    def samp_clk_timebase_master_timebase_div(self) -> None: ...
    @property
    def samp_clk_timebase_rate(self) -> float: ...
    @samp_clk_timebase_rate.setter
    def samp_clk_timebase_rate(self, val: float) -> None: ...
    @samp_clk_timebase_rate.deleter
    def samp_clk_timebase_rate(self) -> None: ...
    @property
    def samp_clk_timebase_src(self) -> str: ...
    @samp_clk_timebase_src.setter
    def samp_clk_timebase_src(self, val: str) -> None: ...
    @samp_clk_timebase_src.deleter
    def samp_clk_timebase_src(self) -> None: ...
    @property
    def samp_clk_timebase_term(self) -> str: ...
    @property
    def samp_clk_underflow_behavior(self) -> UnderflowBehavior: ...
    @samp_clk_underflow_behavior.setter
    def samp_clk_underflow_behavior(self, val: UnderflowBehavior) -> None: ...
    @samp_clk_underflow_behavior.deleter
    def samp_clk_underflow_behavior(self) -> None: ...
    @property
    def samp_clk_write_wfm_use_initial_wfm_dt(self) -> bool: ...
    @samp_clk_write_wfm_use_initial_wfm_dt.setter
    def samp_clk_write_wfm_use_initial_wfm_dt(self, val: bool) -> None: ...
    @samp_clk_write_wfm_use_initial_wfm_dt.deleter
    def samp_clk_write_wfm_use_initial_wfm_dt(self) -> None: ...
    @property
    def samp_quant_samp_mode(self) -> AcquisitionType: ...
    @samp_quant_samp_mode.setter
    def samp_quant_samp_mode(self, val: AcquisitionType) -> None: ...
    @samp_quant_samp_mode.deleter
    def samp_quant_samp_mode(self) -> None: ...
    @property
    def samp_quant_samp_per_chan(self) -> int: ...
    @samp_quant_samp_per_chan.setter
    def samp_quant_samp_per_chan(self, val: int) -> None: ...
    @samp_quant_samp_per_chan.deleter
    def samp_quant_samp_per_chan(self) -> None: ...
    @property
    def samp_timing_engine(self) -> int: ...
    @samp_timing_engine.setter
    def samp_timing_engine(self, val: int) -> None: ...
    @samp_timing_engine.deleter
    def samp_timing_engine(self) -> None: ...
    @property
    def samp_timing_type(self) -> SampleTimingType: ...
    @samp_timing_type.setter
    def samp_timing_type(self, val: SampleTimingType) -> None: ...
    @samp_timing_type.deleter
    def samp_timing_type(self) -> None: ...
    @property
    def simultaneous_ao_enable(self) -> bool: ...
    @simultaneous_ao_enable.setter
    def simultaneous_ao_enable(self, val: bool) -> None: ...
    @simultaneous_ao_enable.deleter
    def simultaneous_ao_enable(self) -> None: ...
    @property
    def sync_clk_interval(self) -> int: ...
    @sync_clk_interval.setter
    def sync_clk_interval(self, val: int) -> None: ...
    @sync_clk_interval.deleter
    def sync_clk_interval(self) -> None: ...
    @property
    def sync_pulse_min_delay_to_start(self) -> float: ...
    @sync_pulse_min_delay_to_start.setter
    def sync_pulse_min_delay_to_start(self, val: float) -> None: ...
    @sync_pulse_min_delay_to_start.deleter
    def sync_pulse_min_delay_to_start(self) -> None: ...
    @property
    def sync_pulse_reset_delay(self) -> float: ...
    @sync_pulse_reset_delay.setter
    def sync_pulse_reset_delay(self, val: float) -> None: ...
    @sync_pulse_reset_delay.deleter
    def sync_pulse_reset_delay(self) -> None: ...
    @property
    def sync_pulse_reset_time(self) -> float: ...
    @property
    def sync_pulse_src(self) -> str: ...
    @sync_pulse_src.setter
    def sync_pulse_src(self, val: str) -> None: ...
    @sync_pulse_src.deleter
    def sync_pulse_src(self) -> None: ...
    @property
    def sync_pulse_sync_time(self) -> float: ...
    @property
    def sync_pulse_term(self) -> str: ...
    @property
    def sync_pulse_time_timescale(self) -> Timescale: ...
    @sync_pulse_time_timescale.setter
    def sync_pulse_time_timescale(self, val: Timescale) -> None: ...
    @sync_pulse_time_timescale.deleter
    def sync_pulse_time_timescale(self) -> None: ...
    @property
    def sync_pulse_time_when(self) -> datetime: ...
    @sync_pulse_time_when.setter
    def sync_pulse_time_when(self, val: datetime) -> None: ...
    @sync_pulse_time_when.deleter
    def sync_pulse_time_when(self) -> None: ...
    @property
    def sync_pulse_type(self) -> SyncPulseType: ...
    @sync_pulse_type.setter
    def sync_pulse_type(self, val: SyncPulseType) -> None: ...
    @sync_pulse_type.deleter
    def sync_pulse_type(self) -> None: ...
    def cfg_burst_handshaking_timing_export_clock(
        self,
        sample_clk_rate: float,
        sample_clk_outp_term: str,
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
        sample_clk_pulse_polarity: Polarity = Polarity.ACTIVE_HIGH,
        pause_when: Level = Level.HIGH,
        ready_event_active_level: Polarity = Polarity.ACTIVE_HIGH,
    ) -> None: ...
    def cfg_burst_handshaking_timing_import_clock(
        self,
        sample_clk_rate: float,
        sample_clk_src: str,
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
        sample_clk_active_edge: Edge = Edge.RISING,
        pause_when: Level = Level.HIGH,
        ready_event_active_level: Polarity = Polarity.ACTIVE_HIGH,
    ) -> None: ...
    def cfg_change_detection_timing(
        self,
        rising_edge_chan: str = "",
        falling_edge_chan: str = "",
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
    ) -> None: ...
    def cfg_handshaking_timing(
        self,
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
    ) -> None: ...
    def cfg_implicit_timing(
        self,
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
    ) -> None: ...
    def cfg_pipelined_samp_clk_timing(
        self,
        rate: float,
        source: str = "",
        active_edge: Edge = Edge.RISING,
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
    ) -> None: ...
    def cfg_samp_clk_timing(
        self,
        rate: float,
        source: str = "",
        active_edge: Edge = Edge.RISING,
        sample_mode: AcquisitionType = AcquisitionType.FINITE,
        samps_per_chan: int = 1000,
    ) -> None: ...
