from ...grpc_session_options import GrpcSessionOptions
from ..._base_interpreter import BaseInterpreter

class PersistedChannel:
    def __init__(
        self, name: str, *, grpc_options: GrpcSessionOptions | None
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def author(self) -> str: ...
    @property
    def allow_interactive_editing(self) -> bool: ...
    @property
    def allow_interactive_deletion(self) -> bool: ...
    def delete(self) -> None: ...

class _PersistedChannelAlternateConstructor(PersistedChannel):
    def __init__(self, name: str, interpreter: BaseInterpreter) -> None: ...
