from ...constants import Level, TriggerType
from ..._grpc_interpreter import GrpcStubInterpreter
from ..._lib import TaskHandle

class HandshakeTrigger:
    """
    Represents the handshake trigger configurations for a DAQmx task.
    """

    __slots__ = ("_handle", "_interpreter")

    def __init__(
        self, task_handle: TaskHandle, interpreter: GrpcStubInterpreter
    ) -> None: ...
    @property
    def interlocked_asserted_lvl(self) -> Level: ...
    @interlocked_asserted_lvl.setter
    def interlocked_asserted_lvl(self, val: Level) -> None: ...
    @interlocked_asserted_lvl.deleter
    def interlocked_asserted_lvl(self) -> None: ...
    @property
    def interlocked_src(self) -> str: ...
    @interlocked_src.setter
    def interlocked_src(self, val: str) -> None: ...
    @interlocked_src.deleter
    def interlocked_src(self) -> None: ...
    @property
    def trig_type(self) -> TriggerType: ...
    @trig_type.setter
    def trig_type(self, val: TriggerType) -> None: ...
    @trig_type.deleter
    def trig_type(self) -> None: ...
