from ..._base_interpreter import BaseInterpreter
from ...scale import Scale

class PersistedScale:
    @property
    def name(self) -> str: ...
    @property
    def author(self) -> str: ...
    @property
    def allow_interactive_editing(self) -> bool: ...
    @property
    def allow_interactive_deletion(self) -> bool: ...
    def delete(self) -> None: ...
    def load(self) -> Scale: ...

class _PersistedScaleAlternateConstructor(PersistedScale):
    def __init__(self, name: str, interpreter: BaseInterpreter) -> None: ...
