from ...task._task import Task
from ...grpc_session_options import GrpcSessionOptions
from typing import Any
from ..._grpc_interpreter import GrpcStubInterpreter

class PersistedTask:
    """
    Represents a saved DAQmx task.

    Use the DAQmx Persisted Task properties to query information about
    programmatically saved tasks.
    """

    __slots__ = ["_name", "_interpreter", "__weakref__"]

    def __init__(
        self, name: str, *, grpc_options: GrpcSessionOptions | None = ...
    ) -> None: ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: Any) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def author(self) -> str: ...
    @property
    def allow_interactive_editing(self) -> bool: ...
    @property
    def allow_interactive_deletion(self) -> bool: ...
    def delete(self) -> None: ...
    def load(self) -> Task: ...

class _PersistedTaskAlternateConstructor(PersistedTask):
    def __init__(
        self,
        name: str,
        interpreter: GrpcStubInterpreter,
    ) -> None: ...
