from ...task.channels._ai_channel import AIChannel
from ...task.collections._channel_collection import ChannelCollection
from ..._base_interpreter import BaseInterpreter
from ..._lib import TaskHandle
from ...constants import (
    ACExcitWireMode,
    AccelChargeSensitivityUnits,
    AccelSensitivityUnits,
    AccelUnits,
    AngleUnits,
    BridgeConfiguration,
    BridgeElectricalUnits,
    BridgePhysicalUnits,
    BridgeUnits,
    CJCSource,
    ChargeUnits,
    CurrentShuntResistorLocation,
    CurrentUnits,
    EddyCurrentProxProbeSensitivityUnits,
    ExcitationSource,
    ForceIEPESensorSensitivityUnits,
    ForceUnits,
    FrequencyUnits,
    LVDTSensitivityUnits,
    LengthUnits,
    PressureUnits,
    RTDType,
    RVDTSensitivityUnits,
    ResistanceConfiguration,
    ResistanceUnits,
    SoundPressureUnits,
    StrainGageBridgeType,
    StrainGageRosetteMeasurementType,
    StrainGageRosetteType,
    StrainUnits,
    TEDSUnits,
    TemperatureUnits,
    TerminalConfiguration,
    ThermocoupleType,
    TorqueUnits,
    VelocityIEPESensorSensitivityUnits,
    VelocityUnits,
    VoltageUnits,
)

class AIChannelCollection(ChannelCollection):
    def __init__(
        self, task_handle: TaskHandle, interpreter: BaseInterpreter
    ) -> None: ...
    def _create_chan(
        self, physical_channel: str = "", name_to_assign_to_channel: str = ""
    ) -> AIChannel: ...
    def add_ai_accel_4_wire_dc_voltage_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: AccelUnits = AccelUnits.G,
        sensitivity: float = 1000.0,
        sensitivity_units: AccelSensitivityUnits = AccelSensitivityUnits.MILLIVOLTS_PER_G,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 0.0,
        use_excit_for_scaling: bool = False,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_accel_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: AccelUnits = AccelUnits.G,
        sensitivity: float = 1000.0,
        sensitivity_units: AccelSensitivityUnits = AccelSensitivityUnits.MILLIVOLTS_PER_G,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.004,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_accel_charge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: AccelUnits = AccelUnits.G,
        sensitivity: float = 100.0,
        sensitivity_units: AccelChargeSensitivityUnits = AccelChargeSensitivityUnits.PICO_COULOMBS_PER_G,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_bridge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -0.002,
        max_val: float = 0.002,
        units: BridgeUnits = BridgeUnits.VOLTS_PER_VOLT,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_charge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -0.000000001,
        max_val: float = 0.000000001,
        units: ChargeUnits = ChargeUnits.COULOMBS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_current_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -0.01,
        max_val: float = 0.01,
        units: CurrentUnits = CurrentUnits.AMPS,
        shunt_resistor_loc: CurrentShuntResistorLocation = CurrentShuntResistorLocation.LET_DRIVER_CHOOSE,
        ext_shunt_resistor_val: float = 249.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_current_rms_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -0.01,
        max_val: float = 0.01,
        units: CurrentUnits = CurrentUnits.AMPS,
        shunt_resistor_loc: CurrentShuntResistorLocation = CurrentShuntResistorLocation.LET_DRIVER_CHOOSE,
        ext_shunt_resistor_val: float = 249.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_force_bridge_polynomial_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: ForceUnits = ForceUnits.POUNDS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        forward_coeffs: list[float] | None = None,
        reverse_coeffs: list[float] | None = None,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.POUNDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_force_bridge_table_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: ForceUnits = ForceUnits.POUNDS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        electrical_vals: list[float] | None = None,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        physical_vals: list[float] | None = None,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.POUNDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_force_bridge_two_point_lin_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: ForceUnits = ForceUnits.POUNDS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        first_electrical_val: float = 0.0,
        second_electrical_val: float = 2.0,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        first_physical_val: float = 0.0,
        second_physical_val: float = 100.0,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.POUNDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_force_iepe_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -2000.0,
        max_val: float = 2000.0,
        units: ForceUnits = ForceUnits.NEWTONS,
        sensitivity: float = 2.25,
        sensitivity_units: ForceIEPESensorSensitivityUnits = ForceIEPESensorSensitivityUnits.MILLIVOLTS_PER_NEWTON,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.004,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_freq_voltage_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 1,
        max_val: float = 100,
        units: FrequencyUnits = FrequencyUnits.HZ,
        threshold_level: float = 0.0,
        hysteresis: float = 0.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_microphone_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        units: SoundPressureUnits = SoundPressureUnits.PA,
        mic_sensitivity: float = 10.0,
        max_snd_press_level: float = 100.0,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.004,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_pos_eddy_curr_prox_probe_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 0.00254,
        units: LengthUnits = LengthUnits.METERS,
        sensitivity: float = 200.0,
        sensitivity_units: EddyCurrentProxProbeSensitivityUnits = EddyCurrentProxProbeSensitivityUnits.MILLIVOLTS_PER_MIL,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_pos_lvdt_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -0.1,
        max_val: float = 0.1,
        units: LengthUnits = LengthUnits.METERS,
        sensitivity: float = 50.0,
        sensitivity_units: LVDTSensitivityUnits = LVDTSensitivityUnits.MILLIVOLTS_PER_VOLT_PER_MILLIMETER,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 1.0,
        voltage_excit_freq: float = 2500.0,
        ac_excit_wire_mode: ACExcitWireMode = ACExcitWireMode.FOUR_WIRE,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_pos_rvdt_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -70.0,
        max_val: float = 70.0,
        units: AngleUnits = AngleUnits.DEGREES,
        sensitivity: float = 50.0,
        sensitivity_units: RVDTSensitivityUnits = RVDTSensitivityUnits.MILLIVOLTS_PER_VOLT_PER_DEGREE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 1.0,
        voltage_excit_freq: float = 2500.0,
        ac_excit_wire_mode: ACExcitWireMode = ACExcitWireMode.FOUR_WIRE,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_power_chan(
        self,
        physical_channel: str,
        voltage_setpoint: float,
        current_setpoint: float,
        output_enable: bool,
        name_to_assign_to_channel: str = "",
    ) -> AIChannel: ...
    def add_ai_pressure_bridge_polynomial_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: PressureUnits = PressureUnits.POUNDS_PER_SQ_INCH,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        forward_coeffs: list[float] | None = None,
        reverse_coeffs: list[float] | None = None,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.POUNDS_PER_SQ_INCH,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_pressure_bridge_table_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: PressureUnits = PressureUnits.POUNDS_PER_SQ_INCH,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        electrical_vals: list[float] | None = None,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        physical_vals: list[float] | None = None,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.POUNDS_PER_SQ_INCH,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_pressure_bridge_two_point_lin_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: PressureUnits = PressureUnits.POUNDS_PER_SQ_INCH,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        first_electrical_val: float = 0.0,
        second_electrical_val: float = 2.0,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        first_physical_val: float = 0.0,
        second_physical_val: float = 100.0,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.POUNDS_PER_SQ_INCH,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_resistance_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 100.0,
        max_val: float = 1000.0,
        units: ResistanceUnits = ResistanceUnits.OHMS,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.TWO_WIRE,
        current_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        current_excit_val: float = 0.001,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_rosette_strain_gage_chan(
        self,
        physical_channel: str,
        rosette_type: StrainGageRosetteType,
        gage_orientation: float,
        rosette_meas_types: list[StrainGageRosetteMeasurementType],
        name_to_assign_to_channel: str = "",
        min_val: float = -0.001,
        max_val: float = 0.001,
        strain_config: StrainGageBridgeType = StrainGageBridgeType.QUARTER_BRIDGE_I,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        gage_factor: float = 2.0,
        nominal_gage_resistance: float = 350.0,
        poisson_ratio: float = 0.3,
        lead_wire_resistance: float = 0.0,
    ) -> AIChannel: ...
    def add_ai_rtd_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        rtd_type: RTDType = RTDType.PT_3750,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.TWO_WIRE,
        current_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        current_excit_val: float = 0.0025,
        r_0: float = 100.0,
    ) -> AIChannel: ...
    def add_ai_strain_gage_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -0.001,
        max_val: float = 0.001,
        units: StrainUnits = StrainUnits.STRAIN,
        strain_config: StrainGageBridgeType = StrainGageBridgeType.FULL_BRIDGE_I,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        gage_factor: float = 2.0,
        initial_bridge_voltage: float = 0.0,
        nominal_gage_resistance: float = 350.0,
        poisson_ratio: float = 0.30,
        lead_wire_resistance: float = 0.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_temp_built_in_sensor_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        units: TemperatureUnits = TemperatureUnits.DEG_C,
    ) -> AIChannel: ...
    def add_ai_thrmcpl_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        thermocouple_type: ThermocoupleType = ThermocoupleType.J,
        cjc_source: CJCSource = CJCSource.CONSTANT_USER_VALUE,
        cjc_val: float = 25.0,
        cjc_channel: str = "",
    ) -> AIChannel: ...
    def add_ai_thrmstr_chan_iex(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.FOUR_WIRE,
        current_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        current_excit_val: float = 0.00015,
        a: float = 0.001295361,
        b: float = 0.0002343159,
        c: float = 0.0000001018703,
    ) -> AIChannel: ...
    def add_ai_thrmstr_chan_vex(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.FOUR_WIRE,
        voltage_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        voltage_excit_val: float = 2.5,
        a: float = 0.001295361,
        b: float = 0.0002343159,
        c: float = 0.0000001018703,
        r_1: float = 5000.0,
    ) -> AIChannel: ...
    def add_ai_torque_bridge_polynomial_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: TorqueUnits = TorqueUnits.INCH_POUNDS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        forward_coeffs: list[float] | None = None,
        reverse_coeffs: list[float] | None = None,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.INCH_POUNDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_torque_bridge_table_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: TorqueUnits = TorqueUnits.INCH_POUNDS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        electrical_vals: list[float] | None = None,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        physical_vals: list[float] | None = None,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.INCH_POUNDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_torque_bridge_two_point_lin_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: TorqueUnits = TorqueUnits.INCH_POUNDS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.FULL_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        nominal_bridge_resistance: float = 350.0,
        first_electrical_val: float = 0.0,
        second_electrical_val: float = 2.0,
        electrical_units: BridgeElectricalUnits = BridgeElectricalUnits.MILLIVOLTS_PER_VOLT,
        first_physical_val: float = 0.0,
        second_physical_val: float = 100.0,
        physical_units: BridgePhysicalUnits = BridgePhysicalUnits.INCH_POUNDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_velocity_iepe_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -50.0,
        max_val: float = 50.0,
        units: VelocityUnits = VelocityUnits.INCHES_PER_SECOND,
        sensitivity: float = 100.0,
        sensitivity_units: VelocityIEPESensorSensitivityUnits = VelocityIEPESensorSensitivityUnits.MILLIVOLTS_PER_INCH_PER_SECOND,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.002,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_voltage_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: VoltageUnits = VoltageUnits.VOLTS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_voltage_chan_with_excit(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -10.0,
        max_val: float = 10.0,
        units: VoltageUnits = VoltageUnits.VOLTS,
        bridge_config: BridgeConfiguration = BridgeConfiguration.NO_BRIDGE,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 0.0,
        use_excit_for_scaling: bool = False,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_ai_voltage_rms_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: VoltageUnits = VoltageUnits.VOLTS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_accel_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: AccelUnits = AccelUnits.G,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.004,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_bridge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -0.002,
        max_val: float = 0.002,
        units: TEDSUnits = TEDSUnits.FROM_TEDS,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_current_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -0.01,
        max_val: float = 0.01,
        units: TEDSUnits = TEDSUnits.FROM_TEDS,
        shunt_resistor_loc: CurrentShuntResistorLocation = CurrentShuntResistorLocation.LET_DRIVER_CHOOSE,
        ext_shunt_resistor_val: float = 249.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_force_bridge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: ForceUnits = ForceUnits.POUNDS,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_force_iepe_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -2000.0,
        max_val: float = 2000.0,
        units: ForceUnits = ForceUnits.NEWTONS,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.001,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_microphone_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        units: SoundPressureUnits = SoundPressureUnits.PA,
        max_snd_press_level: float = 100.0,
        current_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        current_excit_val: float = 0.004,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_pos_lvdt_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -0.1,
        max_val: float = 0.1,
        units: LengthUnits = LengthUnits.METERS,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 1.0,
        voltage_excit_freq: float = 2500.0,
        ac_excit_wire_mode: ACExcitWireMode = ACExcitWireMode.FOUR_WIRE,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_pos_rvdt_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -70.0,
        max_val: float = 70.0,
        units: AngleUnits = AngleUnits.DEGREES,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 1.0,
        voltage_excit_freq: float = 2500.0,
        ac_excit_wire_mode: ACExcitWireMode = ACExcitWireMode.FOUR_WIRE,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_pressure_bridge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: PressureUnits = PressureUnits.POUNDS_PER_SQ_INCH,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_resistance_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 100.0,
        max_val: float = 1000.0,
        units: TEDSUnits = TEDSUnits.FROM_TEDS,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.TWO_WIRE,
        current_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        current_excit_val: float = 0.001,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_rtd_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.TWO_WIRE,
        current_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        current_excit_val: float = 0.0025,
    ) -> AIChannel: ...
    def add_teds_ai_strain_gage_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -0.001,
        max_val: float = 0.001,
        units: StrainUnits = StrainUnits.STRAIN,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        initial_bridge_voltage: float = 0.0,
        lead_wire_resistance: float = 0.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_thrmcpl_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        cjc_source: CJCSource = CJCSource.CONSTANT_USER_VALUE,
        cjc_val: float = 25.0,
        cjc_channel: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_thrmstr_chan_iex(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.FOUR_WIRE,
        current_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        current_excit_val: float = 0.00015,
    ) -> AIChannel: ...
    def add_teds_ai_thrmstr_chan_vex(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = 0.0,
        max_val: float = 100.0,
        units: TemperatureUnits = TemperatureUnits.DEG_C,
        resistance_config: ResistanceConfiguration = ResistanceConfiguration.FOUR_WIRE,
        voltage_excit_source: ExcitationSource = ExcitationSource.EXTERNAL,
        voltage_excit_val: float = 2.5,
        r_1: float = 5000.0,
    ) -> AIChannel: ...
    def add_teds_ai_torque_bridge_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        min_val: float = -100.0,
        max_val: float = 100.0,
        units: TorqueUnits = TorqueUnits.INCH_POUNDS,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 2.5,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_voltage_chan(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -5.0,
        max_val: float = 5.0,
        units: TEDSUnits = TEDSUnits.FROM_TEDS,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
    def add_teds_ai_voltage_chan_with_excit(
        self,
        physical_channel: str = "",
        name_to_assign_to_channel: str = "",
        terminal_config: TerminalConfiguration = TerminalConfiguration.DEFAULT,
        min_val: float = -10.0,
        max_val: float = 10.0,
        units: TEDSUnits = TEDSUnits.FROM_TEDS,
        voltage_excit_source: ExcitationSource = ExcitationSource.INTERNAL,
        voltage_excit_val: float = 0.0,
        custom_scale_name: str = "",
    ) -> AIChannel: ...
