import pathlib

from ..constants import (
    AOPowerUpOutputBehavior,
    AcquisitionType,
    LogicFamily,
    SensorPowerType,
    TerminalConfiguration,
    UsageTypeAI,
    UsageTypeAO,
    UsageTypeCI,
    UsageTypeCO,
    WriteBasicTEDSOptions,
)
from ..grpc_session_options import GrpcSessionOptions
from typing import Union
from .._base_interpreter import BaseInterpreter

__all__ = ["PhysicalChannel"]

class PhysicalChannel:
    def __init__(
        self, name: str, *, grpc_options: GrpcSessionOptions | None = ...
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def ai_input_srcs(self) -> list[str]: ...
    @property
    def ai_meas_types(self) -> list[UsageTypeAI]: ...
    @property
    def ai_power_control_enable(self) -> bool: ...
    @ai_power_control_enable.setter
    def ai_power_control_enable(self, val: bool) -> None: ...
    @ai_power_control_enable.deleter
    def ai_power_control_enable(self) -> None: ...
    @property
    def ai_power_control_type(self) -> SensorPowerType: ...
    @ai_power_control_type.setter
    def ai_power_control_type(self, val: SensorPowerType) -> None: ...
    @ai_power_control_type.deleter
    def ai_power_control_type(self) -> None: ...
    @property
    def ai_power_control_voltage(self) -> float: ...
    @ai_power_control_voltage.setter
    def ai_power_control_voltage(self, val: float) -> None: ...
    @ai_power_control_voltage.deleter
    def ai_power_control_voltage(self) -> None: ...
    @property
    def ai_sensor_power_open_chan(self) -> bool: ...
    @property
    def ai_sensor_power_overcurrent(self) -> bool: ...
    @property
    def ai_sensor_power_types(self) -> list[SensorPowerType]: ...
    @property
    def ai_sensor_power_voltage_range_vals(self) -> list[float]: ...
    @property
    def ai_term_cfgs(self) -> list[TerminalConfiguration]: ...
    @property
    def ao_manual_control_amplitude(self) -> float: ...
    @property
    def ao_manual_control_enable(self) -> bool: ...
    @ao_manual_control_enable.setter
    def ao_manual_control_enable(self, val: bool) -> None: ...
    @ao_manual_control_enable.deleter
    def ao_manual_control_enable(self) -> None: ...
    @property
    def ao_manual_control_freq(self) -> float: ...
    @property
    def ao_manual_control_short_detected(self) -> bool: ...
    @property
    def ao_output_types(self) -> list[UsageTypeAO]: ...
    @property
    def ao_power_amp_channel_enable(self) -> bool: ...
    @ao_power_amp_channel_enable.setter
    def ao_power_amp_channel_enable(self, val: bool) -> None: ...
    @ao_power_amp_channel_enable.deleter
    def ao_power_amp_channel_enable(self) -> None: ...
    @property
    def ao_power_amp_gain(self) -> float: ...
    @property
    def ao_power_amp_offset(self) -> float: ...
    @property
    def ao_power_amp_overcurrent(self) -> bool: ...
    @property
    def ao_power_amp_scaling_coeff(self) -> list[float]: ...
    @property
    def ao_supported_power_up_output_types(self) -> list[AOPowerUpOutputBehavior]: ...
    @property
    def ao_term_cfgs(self) -> list[TerminalConfiguration]: ...
    @property
    def ci_meas_types(self) -> list[UsageTypeCI]: ...
    @property
    def co_output_types(self) -> list[UsageTypeCO]: ...
    @property
    def di_change_detect_supported(self) -> bool: ...
    @property
    def di_port_width(self) -> int: ...
    @property
    def di_samp_clk_supported(self) -> bool: ...
    @property
    def di_samp_modes(self) -> list[AcquisitionType]: ...
    @property
    def dig_port_logic_family(self) -> LogicFamily: ...
    @dig_port_logic_family.setter
    def dig_port_logic_family(self, val: LogicFamily) -> None: ...
    @dig_port_logic_family.deleter
    def dig_port_logic_family(self) -> None: ...
    @property
    def do_port_width(self) -> int: ...
    @property
    def do_samp_clk_supported(self) -> bool: ...
    @property
    def do_samp_modes(self) -> AcquisitionType: ...
    @property
    def teds_bit_stream(self) -> list[int]: ...
    @property
    def teds_mfg_id(self) -> int: ...
    @property
    def teds_model_num(self) -> int: ...
    @property
    def teds_serial_num(self) -> int: ...
    @property
    def teds_template_ids(self) -> list[int]: ...
    @property
    def teds_version_letter(self) -> str: ...
    @property
    def teds_version_num(self) -> int: ...
    def clear_teds(self) -> None: ...
    def configure_teds(
        self, file_path: Union[str, pathlib.PurePath] | None = None
    ) -> None: ...
    def write_to_teds_from_array(
        self,
        bit_stream: list[int] | None = ...,
        basic_teds_options: WriteBasicTEDSOptions | None = ...,
    ) -> None: ...
    def write_to_teds_from_file(
        self,
        file_path: Union[str, pathlib.PurePath] | None = ...,
        basic_teds_options: WriteBasicTEDSOptions = ...,
    ) -> None: ...

class _PhysicalChannelAlternateConstructor(PhysicalChannel):
    def __init__(self, name: str, interpreter: BaseInterpreter) -> None: ...
