from pathlib import Path

def get_dotenv_search_path() -> Path: ...
def _has_dotenv_file(dir: Path) -> bool: ...
def _get_script_or_exe_path() -> Path | None: ...
def _get_caller_path() -> Path | None: ...
def _get_package_path() -> Path: ...
